### ISSUE TITLE
Probleme in lokaler Entwicklungsumgebung

### ISSUE THREAD

**Issue by NGWNGW** [tbaddade/redaxo_url#10]
Hi, 

ich habe nun, nachdem Issue #7 behoben wurde, die neueste Version aus Github gezogen.

Lokal arbeite ich hier seit kurzem mit Mamp, die "Detailseiten" leiten dort immer auf den Redaxo 404 Artikel. Auf dem Produktiv-Server werden die "Detailseiten" ohne Probleme angezeigt.

Hat das Addon eventuell Probleme mit abweichenden Ports? Lokal rufe ich die Seiten per http://beispielseite.dev:8888/ auf.

Gruß
Nico

**Comment by tbaddade** [comment]
Welche Config hast du genau angelegt und welche Urls werden generiert. Ggf. auch gern einmal die Cache Datei `pathlist.php` unter `redaxo/cache/addons/url/` senden.

**Comment by NGWNGW** [comment]
Hi, 

guter Hinweis mit der pathlist.php

Die Pathliste wird nur für Domains ohne Portangabe erstellt. Siehe /url/lib/Url/Rewriter/Generator.php Zeile 263:

`                            self::$paths[$url->getDomain()][$articleId][$entry['id']][$articleClangId] = $object;
`

**Comment by tbaddade** [comment]
Das meine ich nicht. Ich meine einerseits deine Config, also was du im AddOn eingestellt hast und was tatsächlich in der generierten pathlist steht.

**Comment by NGWNGW** [comment]
Ja, das war mir klar. Ich dachte nur ich erspare dir die Suche ;) $url->getDomain() gibt den Port eben nicht mit aus...

Hier die Infos:

pathlist.php
`{"localpage.dev":{"5":{"1":{"1":{"url":"\/referenzen\/details\/item1\/","fullUrl":"http:\/\/localpage.dev:8888\/referenzen\/details\/item1\/","pathNames":[],"fullPathNames":[],"urlParamKey":"","sitemap":false,"seoTitle":"","seoDescription":""}},"2":{"1":{"url":"\/referenzen\/details\/item2\/","fullUrl":"http:\/\/localpage.dev:8888\/referenzen\/details\/item2\/","pathNames":[],"fullPathNames":[],"urlParamKey":"","sitemap":false,"seoTitle":"","seoDescription":""}},...`

core/config.yml
`server: 'http://localpage.dev:8888/'`

Addon-Config
![bildschirmfoto 2016-07-05 um 20 02 13](https://cloud.githubusercontent.com/assets/1823782/16594584/68b5fd78-42eb-11e6-9b67-4e9b4c2e17e7.png)

**Temporärer** Fix für mich... 
`self::$paths[$url->getDomain()][$articleId][$entry['id']][$articleClangId] = $object; `
in
`self::$paths[$_SERVER['HTTP_HOST']][$articleId][$entry['id']][$articleClangId] = $object;`
umändern...

**Comment by tbaddade** [comment]
Da ich kein Mamp habe kann ich das nicht wirklich testen.

Kannst du mal vor dieser Zeile folgendes eintragen
https://github.com/tbaddade/redaxo_url/blob/master/lib/Url/Generator.php#L280

`echo '<pre>' . $currentUrl->getDomain() . ' == ' . $domain . '</pre>';`

Und das Ergebnis hier notieren.

**Comment by NGWNGW** [comment]
Ein Update auf die aktuelle Beta2 hat das Problem nun behoben.
