### ISSUE TITLE
Umbenennen / Verschieben / Kopieren von URL-Zielartikel generiert keine neue Pathlist

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#101]
Nach dem Umbenennen/Verschieben/Kopieren eines URL-Zielartikels werden noch URLs nach dem alten Schema generiert.

Korrekt wäre, neue URLs zu generieren.

**Comment by tbaddade** [comment]
Betrifft auch die Kategorien … EPs ART_MOVED und CAT_MOVED ergänzen

**Comment by alexplusde** [comment]
Prost! 🍺
