### ISSUE TITLE
Fehler beim Updaten von Ver. 1.0.1 auf Ver. 2.0.0-beta1

### ISSUE THREAD

**Issue by greatif** [tbaddade/redaxo_url#102]
![scr01](https://user-images.githubusercontent.com/8527203/54019921-c05c1d80-418c-11e9-9e94-9353df5f0461.png)

**Comment by tbaddade** [comment]
Hatte ich vorhin auch festgestellt. Scheinbar wird die update.php Datei nicht verwendet.

Aktuelle Lösung:
- Safe mode aktivieren
- Url-AddOn re-installieren

**Comment by tbaddade** [comment]
close via 6c58b476b1664ba2e0d89bfd3705acb8befe4445
