### ISSUE TITLE
Fehler nach Update aus Installer

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#103]
Bei der Installation erst:

```
Warning: include(/home/html/viphosting.de/_dev/redaxo/src/addons/.new.urlinstall.php) [<a href='https://php.net/manual/function.include'>function.include</a>]: failed to open stream: Datei oder Verzeichnis nicht gefunden in redaxo/src/core/lib/packages/package.php on line 231
```

danach WHOOPS

```
Error while executing statement "SELECT * FROM rex_url_generator_profile ORDER BY `table_name`"! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xyzabc.rex_url_generator_profile' doesn't exist
```

**Comment by tbaddade** [comment]
@gharlan Kannst du etwas zur Warning sagen? Kann es sein, dass die install.php Datei dadurch nicht angerufen und somit die Tabellen nicht erstellt werden konnten?

**Comment by gharlan** [comment]
https://github.com/tbaddade/redaxo_url/blob/master/update.php

Da fehlt ein `/`.

**Comment by tbaddade** [comment]
close via a900b8e7f5723750c531246957ce7ff80d24eff1

**Comment by tbaddade** [comment]
@alexplusde Beta3 ist im Installer … 5 Minuten warten und dann gern nochmal probieren

**Comment by alexplusde** [comment]
Scheint jetzt zu passen

**Comment by tbaddade** [comment]
Danke für die Rückmeldung
