### ISSUE TITLE
2.0-beta3: Class 'UrlSeo' not found

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#105]
Gibt's das jetzt nicht mehr?

**Comment by tbaddade** [comment]
Die Aliase sind rausgeflogen … probier mal

`$urlSeo = new Url\Seo();`

**Comment by alexplusde** [comment]
Klappt. Sollte in die README.md einfließen

**Comment by alexplusde** [comment]
bzw. war auch mal drin / gedacht:
https://github.com/alexplusde/redaxo_url/blob/dbffe5f72f05d5edba693aa727e3f874c8d4ceb3/README.md#seo-metadaten

**Comment by alexplusde** [comment]
Und wie komme ich an einen einzelnen Datensatz/ID ran? Da ist auch irgendwie viel in der README verloren gegangen. Nächstes Wochenende könnte ich mich um die readme kümmern, wenn ich die Info habe, wie das damit jetzt geht. (getId() und getData())

**Comment by olien** [comment]
Ist jetzt

`
$urlSeo = new Url\Seo();
echo $urlSeo->getTags();
`

richtig?

**Comment by tbaddade** [comment]
> richtig?

Vorerst ja. Wenn [dieser PR](https://github.com/yakamara/redaxo_yrewrite/pull/310) angenommen wird, wird sich Url an [diesem EP](https://github.com/yakamara/redaxo_yrewrite/pull/310/files#diff-cb340b86769723b7530eb59fee471648R101) einhängen und ein separater Aufruf über Url\Seo bräuchte es dann nicht mehr. Man kann dann den Aufruf von yrewrite belassen.

**Comment by olien** [comment]
und so lange habe ich ein Woops...

**Comment by tbaddade** [comment]
> und so lange habe ich ein Woops

was zeigt der Whoops?

**Comment by olien** [comment]
Hm. Wollte es jetzt in einem anderen Projekt nachstellen. Funktioniert... Ich guck mal zu Hause was ICH falsch mache :-(
