### ISSUE TITLE
Feature: YForm value "Im Frontend anzeigen"

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#108]
Ein Value, das im Table Manager bei Bedarf ein Link zur Frontend-Seite ausgibt, sofern eine URL generiert wurde (d.h. die Beschränkung stimmt).

Ich kann das selbst bauen und einen PR einfügen. 

Dazu müsste ich allerdings wissen, wie ich prüfe, ob es für den Datensatz eine URL erzeugt hat oder nicht. Wenn ich bspw. rex_getUrl($id, $clang, [$key => $id]) mit einem Datensatz ausfülle, woher weiß ich dann, dass es dafür eine URL gibt?

Gibt's da eine Methode innerhalb von URL?

**Comment by tbaddade** [comment]
> Wenn ich bspw. rex_getUrl($id, $clang, [$key => $id]) mit einem Datensatz ausfülle, woher weiß ich dann, dass es dafür eine URL gibt?

Wenn es dazu keine Url gibt, dann wurde diese nicht generiert und wäre ein Fehler. 
Dein YForm value wird sicherlich nur dort eingebunden, wo es auch ein Profil zu dieser Tabelle gibt. Oder ich verstehe dich noch nicht ganz.

**Comment by alexplusde** [comment]
Bisher war es so, dass dann durch rex_getUrl() trotzdem ein Link rauskommt und kein Fehler.

Aber ja, vlt schreiben wir aneinander vorbei. Das Anliegen sollte klar sein: im Table Manager einen Link zum Frontend pro Datensatz zeigen können. Mein Ansatz: eine url value für YForm.

**Comment by tbaddade** [comment]
> Bisher war es so, dass dann durch rex_getUrl() trotzdem ein Link rauskommt und kein Fehler.

das kann durchaus sein. Was aber m.E. nur passierte, wenn man diese Schreibweise verwendete `rex_getUrl($id, $clangId, ['id' => {n}])` … Wenn der UrlParamKey angegeben wurde, so sollte zumindest ein Url gefunden werden: `rex_getUrl('', '', ['param-id' => {n}])`

**Comment by alexplusde** [comment]
Klingt plausibel, dann fange ich mal an...

**Comment by tbaddade** [comment]
Könnte das nicht bereits via PHP-Value funktionieren?

**Comment by alexplusde** [comment]
Das funktioniert nicht via PHP-Value, da ich nicht an die ID des Datensatzes von PHP aus rankomme - nicht in der Liste. Ich habe aber nun eine Möglichkeit gefunden, PR folgt.

**Comment by tbaddade** [comment]
> PR folgt.

Dann im YForm Repository und das Issue kann hier zu?

**Comment by alexplusde** [comment]
Eigentlich sehe ich das value im Url-Repo, kannst es dir gleich anschauen...

**Comment by alexplusde** [comment]
Todo: Wenn keine URL generiert wurde, werden die Parameter nach dem Schema `?key=value` angehängt. Ich finde keine Methode, festzustellen, wann ich eine gültige URL bekommen habe und wann eine ungültige. Ist aber vielleicht auch nicht so schlimm. Falls doch: Bitte mir erklären, wie's geht oder direkt umsetzen.

**Comment by tbaddade** [comment]
Konntest du das Value schon einmal testen @alexplusde ?

**Comment by alexplusde** [comment]
Ja, leider auf einer nicht mehr vorhandenen Dummy-Installation. Inzwischen würde ich wohl einen FOR-Trick zum Manipulieren der Listenübersicht wahlen, fände ein Value jedoch weiterhin komfortabel.

Was kann ich tun?

**Comment by tbaddade** [comment]
Ich schließe mal, da es das value jetzt für YForm gibt
https://github.com/tbaddade/redaxo_url/blob/master/lib/yform/value/url.php

Wenn Probleme damit auftauchen, gern ein neues Issue aufmachen

**Comment by alexplusde** [comment]
Danke! Ich teste es alsbald.
