### ISSUE TITLE
Docs: Methode getUrl unklar

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_url#114]
![image](https://user-images.githubusercontent.com/3855487/54549103-a7801300-49a9-11e9-9f63-f40bdcd81f05.png)

Es sieht so aus, als müsste man das hier schreiben und es wäre nur umbrochen:

`rex_getUrl('', '', ['blog' => {id}])->getUrl(['blog' => {id}])`

Das ist natürlich Quark. 

ist mit der 2. Zeile das hier gemeint?

`rex_category::get($id)->getUrl(['blog' => {id}])`
`rex_article::get($id)->getUrl(['blog' => {id}])`

Dann würde ich das deutlicher schreiben wie:

Als Funktion: `rex_getUrl('', '', ['blog' => {id}])`
Als Methode in `rex_category` oder `rex_article`: `->getUrl(['blog' => {id}])`

**Comment by tbaddade** [comment]
> ist mit der 2. Zeile das hier gemeint?

Genau damit kann man die Unterkategorien innerhalb der Struktur der Url erreichen. Aber warte hier. Die Ausgabe wird noch überarbeitet, da fehlen ja noch weitere Daten.

**Comment by alexplusde** [comment]
Wenn du mir schreibst, was da fehlt, würde ich versuchen, die Ausgabe dazu beizusteuern...
