### ISSUE TITLE
URL 2.x kann nicht mit Punycode URLs umgehen

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#115]
![Bildschirmfoto von 2019-04-02 15-58-12](https://user-images.githubusercontent.com/4131072/55408494-63237400-5560-11e9-9ae1-605ee6c97b70.png)

**Comment by tbaddade** [comment]
Die Urls werden nach RFC 3986 geparsed.
https://tools.ietf.org/html/rfc3986

Man kann den Mode zwar ändern, bringt aber m.E. mehr Probleme mit sich. Muss ich mir noch mal genauer ansehen.

**Comment by tbaddade** [comment]
Du könntest an dieser Stelle den Mode mal ändern

https://github.com/tbaddade/redaxo_url/blob/master/lib/Url/Url.php#L34

Es gibt drei Modes

| Mode | Code |
| --- | --- |
| RFC3986 | `$this->uri = (new Uri($url));` (aktuell) |
| UTF-8 | `$this->uri = (new Uri($url, UriParser::MODE_UTF8));` | 
| IDNA2003 | `$this->uri = (new Uri($url, UriParser::MODE_IDNA2003));` |

**Comment by TobiasKrais** [comment]
Du hast recht. Das löst zumindest das Problem beim Speichern eines Profiles. Einen Pull Request habe ich dir gemacht.

Nebenbei: die Profile in Version 2 sind super. Da ist vollends alles drin, was ich in Version 1 vermisst habe! Danke!

**Comment by TobiasKrais** [comment]
Hinweis: auf der Testseite von der du die Zugangsdaten erhalten hast ist obiger Patch eingebaut.

**Comment by TobiasKrais** [comment]
Siehe noch die Kommentare zum Pull Request: https://github.com/tbaddade/redaxo_url/pull/116#issuecomment-520208723

**Comment by TobiasKrais** [comment]
Habe den PR erweitert: Es wird nun eine Spalte url_hash in die Datenbank hinzugefügt. Diese ersetzt den UNIQUE KEY "url". So kann das Feld "url" auf 1000 Zeichen erweitert werden und lange Punycode URLs sind möglich.

**Comment by alexplusde** [comment]
Ich würde es begrüßen, das Addon wieder in den Installer zu nehmen und ausreifen zu lassen. @tbaddade fühl dich nicht zu verantwortlich - wenn du keinen Support leisten kannst, ist das o.k., vielleicht kann ja @TobiasKrais mit mir ein wenig dazu abfangen?

**Comment by TobiasKrais** [comment]
Bin gerne dabei. Es hängt halt noch viel an einem Patch, das @lexplatt für YRewrite programmiert hat.

Hier noch ein PR, der im Zusammenhang mit diesem Issue steht: https://github.com/tbaddade/redaxo_url/pull/153. Er wäre nötig, um URL Encoded URLs für einzelne Sprachen zu ermöglichen.

**Comment by lexplatt** [comment]
wir könnten mal bei jan anklopfen um den PR von yrewrite voranzutreiben

**Comment by TobiasKrais** [comment]
Hab mal nachgefragt: https://github.com/yakamara/redaxo_yrewrite/pull/276

**Comment by TobiasKrais** [comment]
Danke fürs mergen des PR. Ist damit ja behoben. :-)
