### ISSUE TITLE
2.0-beta3: sitemap.xml Aufruf verursacht fatal error

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#117]
![Bildschirmfoto von 2019-04-02 22-26-33](https://user-images.githubusercontent.com/4131072/55433857-8ec15100-5596-11e9-9b9b-6ae2e42cb8bc.png)

**Comment by fietstouring** [comment]
**Error:** Call to a member function getUrl() on array
**File:** redaxo/src/addons/url/lib/Url/Seo.php
**Line:** 143

**Comment by tbaddade** [comment]
@lexplatt Magst du dir das mit der Sitemap ansehen?

**Comment by TobiasKrais** [comment]
Duplikat von dem hier: https://github.com/tbaddade/redaxo_url/issues/150, bzw. anders herum. Ich schließe den hier mal. Einer ist ja noch offen.
