### ISSUE TITLE
Funktion zum manuellen generieren der Pathlist fehlt

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#118]
Diese Funktion wäre nötig, wenn ein Datensatz geändert wird und kein EP aufgerufen wird. In Version 1.x gab es die Funktion ```UrlGenerator::generatePathFile([]);```

**Comment by TobiasKrais** [comment]
Ich glaube `\Url\Generator::execute()` kommt der Funktion am nächsten. Praktisch wäre es, wenn die Funktion einen optionalen Parameter "namespace" hat. Wird der Parameter nicht übergeben, werden alle URLs neu generiert, sonst nur die des Namensraumes.

**Comment by TobiasKrais** [comment]
In der aktuellen master Version funktioniert `rex_delete_cache()` um die Pathlist zu regenerieren.

**Comment by tbaddade** [comment]
Ich werden in der Übersicht für jedes Profile noch einen eigenen Link anbringen um den Cache separate löschen zu können. Wie bei den Typen vom MediaManager.

**Comment by TobiasKrais** [comment]
Cool! Kann man die hinterlegte Funktion auch im Code aufrufen?

**Comment by tbaddade** [comment]
Vermutlich wird es so werden ;)

**Comment by TobiasKrais** [comment]
Vielen Dank! Funktioniert hervorragend. Damit müsste https://github.com/tbaddade/redaxo_url/issues/99 auch erledigt sein, oder?

**Comment by TobiasKrais** [comment]
Frage: wenn ich via SQL ein Profil einfüge und dann folgenden Code aufrufe:
```$profiles = \Url\Profile::getAll();
if ($profiles) {
	foreach ($profiles as $profile) {
		$profile->deleteUrls();
		$profile->buildUrls();
	}
}
```
erhalte ich unten stehenden Fehler. Rufe ich aber `rex_delete_cache()` auf, kommt der Fehler nicht. Kannst du mir sagen, was ich falsch mache?

Hier die Fehlermeldung:

**Error:** Call to a member function getTableName() on null
**File:** redaxo/src/addons/url/pages/generator.profiles.php
**Line:** 99

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                               | Line     |
| -------------------------------------------- | -------------------------------------------------- | -------- |
| url_generate_column_data                     | redaxo/src/core/lib/util/formatter.php             | 351      |
| rex_formatter::custom                        | redaxo/src/core/lib/util/formatter.php             | 33       |
| rex_formatter::format                        | redaxo/src/core/lib/list.php                       | 903      |
| rex_list->formatValue                        | redaxo/src/core/lib/list.php                       | 1054     |
| rex_list->get                                | redaxo/src/addons/url/pages/generator.profiles.php | 152      |
| include                                      | redaxo/src/core/lib/packages/package.php           | 228      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php              | 474      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php              | 430      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/url/pages/index.php              | 17       |
| include                                      | redaxo/src/core/lib/packages/package.php           | 228      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php              | 474      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php              | 413      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                        | 215      |
| require                                      | redaxo/src/core/boot.php                           | 135      |
| require                                      | redaxo/index.php                                   | 9        |

</details>
<details>
<summary>System report (REDAXO 5.7.1, PHP 7.3.3-nmm1)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.7.1      |


| PHP           |            |
| ------------: | :--------- |
|       Version | 7.3.3-nmm1 |
|       OPcache | no         |
|        Xdebug | no         |


| Database      |                            |
| ------------: | :------------------------- |
|       Version | 5.6.38-nmm1-log            |
| Character set | latin1 (latin1_swedish_ci) |


| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |


| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/66.0 |
|      Protocol | HTTP/1.1     |
|         HTTPS | yes          |


| Packages                                         |             |
| -----------------------------------------------: | :---------- |
|                                         be_style | 2.7.1       |
|                              be_style/customizer | 2.7.0       |
|                                  be_style/redaxo | 2.7.0       |
|                                   cookie_consent | 3.0.0-beta3 |
|                                          cronjob | 2.4.1       |
|                                      d2u_address | 1.1.0       |
|                                       d2u_helper | 1.5.8       |
|                    d2u_helper/translation_helper | 1.5.8       |
|                                      d2u_history | 1.0.0       |
|                                         d2u_jobs | 1.0.8       |
|                           d2u_jobs/hr4you_import | 1.0.8       |
|                                      d2u_linkbox | 1.2.1       |
|                                    d2u_machinery | 1.2.6       |
|                   d2u_machinery/industry_sectors | 1.2.6       |
|         d2u_machinery/machine_features_extension | 1.2.6       |
| d2u_machinery/machine_steel_processing_extension | 1.2.6       |
|                      d2u_machinery/used_machines | 1.2.6       |
|                                         d2u_news | 1.1.1       |
|                                   d2u_news/fairs | 1.1.1       |
|                                      d2u_partner | 1.0         |
|                                   d2u_references | 1.0.5       |
|                                        d2u_staff | 1.0.1       |
|                                       d2u_videos | 1.0.7       |
|                                  emailobfuscator | 2.1.5       |
|                                          install | 2.5.0       |
|                                    media_manager | 2.6.0       |
|                        media_manager_autorewrite | 1.1.0       |
|                                        mediapool | 2.5.0       |
|                                         metainfo | 2.4.0       |
|                                          minibar | 1.0.9       |
|                                        phpmailer | 2.5.1       |
|                                            sprog | 1.2.0       |
|                                        structure | 2.7.0       |
|                                structure/content | 2.7.0       |
|                                         tinymce4 | 1.1.1       |
|                                              url | 2.0.0-beta3 |
|                                            users | 2.5.2       |
|                                             ycom | 3.0-beta4   |
|                                        ycom/auth | 3.0-beta4   |
|                                        ycom/docs | 3.0-beta4   |
|                                       ycom/group | 3.0-beta4   |
|                                  ycom/media_auth | 3.0-beta4   |
|                                            yform | 3.1         |
|                                       yform/docs | 3.1         |
|                                      yform/email | 3.1         |
|                                    yform/manager | 3.1         |
|                                         yrewrite | 2.5         |

</details>

**Comment by tbaddade** [comment]
Du müsstest nach dem einfügen diese Methode aufrufen
https://github.com/tbaddade/redaxo_url/blob/master/lib/Url/Profile.php#L644

**Comment by TobiasKrais** [comment]
Das hilft leider nicht. Wenn ich auf die Profile Seite geht kommt immernoch der gleiche Fehler.
