### ISSUE TITLE
Verison 1.0.0-beta2 kann nicht installiert werden

### ISSUE THREAD

**Issue by olien** [tbaddade/redaxo_url#12]
AddOn url konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "SHOW COLUMNS FROM `rex_url_generate`"! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rex5basic3.rex_url_generate' doesn't exist

**Comment by tbaddade** [comment]
War das Addon bereits installiert und wolltest es via Installer aktualisieren?

**Comment by olien** [comment]
Nein. Ganz frische Installation

**Comment by tbaddade** [comment]
Könntest du den kompletten Fehler schicken?

**Comment by tbaddade** [comment]
@olien Sollte mit dem Commit behoben sein https://github.com/tbaddade/redaxo_url/commit/209951527bce585517fe2f6c6f03fa15e5b31b2b

neue Beta ist im Installer verfügbar

**Comment by olien** [comment]
Bestätige. Funktioniert. Danke.
