### ISSUE TITLE
Profil verursacht Fatal Error im Frontend

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#120]
![Bildschirmfoto von 2019-04-06 22-12-26](https://user-images.githubusercontent.com/4131072/55674767-5b920100-58b9-11e9-8765-d5fec35e564e.png)

Version: 2.0.0-beta3
Redaxo 5.7.1

**Comment by TobiasKrais** [comment]
Fehler entsteht in dem Moment, im Profil im Feld "Spalten aus der die Url erzeugt wird" der Wert "name" ausgewählt wird. Wird "industry_sector_id" ausgewählt ist der Fehler weg.

**Comment by TobiasKrais** [comment]
![Bildschirmfoto von 2019-04-10 10-10-28](https://user-images.githubusercontent.com/4131072/55862546-f704c980-5b78-11e9-9a55-c0727923f077.png)

**Comment by tbaddade** [comment]
Verwendest du einen Filter? Könntest du einen Screenshot deiner Config schicken?

**Comment by TobiasKrais** [comment]
Hier schon mal der SQL Code der Config: https://github.com/TobiasKrais/d2u_machinery/blob/f1884b90fdd4bafb5d05cfc2a338dd41cdd87a64/plugins/used_machines/install.php#L108

**Comment by TobiasKrais** [comment]
![config](https://user-images.githubusercontent.com/4131072/55866875-929a3800-5b81-11e9-8197-98f4c910207d.png)

**Comment by tbaddade** [comment]
Heißt deine PrimaryKey Spalte in der `d2u_machinery_cat...` tatsächlich `category_id` ?

**Comment by TobiasKrais** [comment]
Genau ist er das: `PRIMARY KEY (category_id, clang_id)`
(Siehe https://github.com/TobiasKrais/d2u_machinery/blob/f1884b90fdd4bafb5d05cfc2a338dd41cdd87a64/install.php#L62)

**Comment by tbaddade** [comment]
Ich denke ich benötige von dir Beispieldatensätze. Mein Test mit einer Relation klappte korrekt.

**Comment by tbaddade** [comment]
> Fehler entsteht in dem Moment, im Profil im Feld "Spalten aus der die Url erzeugt wird" der Wert "name" ausgewählt wird.

Kurz nachgefragt: Hat jede Maschine auch einen Namen? Das erste Feld beim Label `Url` darf nicht leer sein. Wenn du dort dein Id-Feld auswählst und der Fehler kommt nicht, dann wird mind. ein Datensatz vermutlich keinen Namen haben.

**Comment by TobiasKrais** [comment]
Hier ein Screenshot des zu Grunde liegende VIEWs. Es gibt Maschinen nur in zwei Sprachen, im Profil sind aber alle Sprachen eingestellt - für 2 Sprachen gibt es also keinen Datensatz:
![Bildschirmfoto von 2019-05-24 21-41-14](https://user-images.githubusercontent.com/4131072/58352852-20e62700-7e6d-11e9-9565-9040a184d461.png)

Wenn ich die Codeänderung zurück nehme und im Profil in der URL die ID an die erste Stelle setze und den Namen an die zweite, dann ist der Fatal Error weg. Statt dessen erhalte ich eine 404 Fehlerseite!

**Comment by TobiasKrais** [comment]
Ist behoben. Danke!
