### ISSUE TITLE
Fehlermeldung "Eindeutigen Namensraum/Schlüssel vergeben, z.B. product-id"

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#122]
Beim aktuellen Stand des masters möchte ich folgendes Profil anlegen:
![Bildschirmfoto von 2019-04-07 11-18-19](https://user-images.githubusercontent.com/4131072/55681449-1ad0d100-5927-11e9-9f4b-de5894b76dd5.png)

Beim Speichern kommt folgende Fehlermeldung:
![Bildschirmfoto von 2019-04-07 11-18-42](https://user-images.githubusercontent.com/4131072/55681462-291eed00-5927-11e9-9fb0-d2e637e7485d.png)

Dabei spielt es keine Rolle, was ich in die Felder einfüge (nur eine Sprache oder mehrere, welcher Artikel). Meine Seite hat 5 Sprachen. In der 2.0.0-beta3 gab es den Fehler noch nicht.

**Comment by dtpop** [comment]
Hier gleicher Fehler.

**Comment by TobiasKrais** [comment]
Getestet: funktioniert wieder alles korrekt. Danke Thomas!
