### ISSUE TITLE
URL ruft Fehlerseite auf

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#124]
Version: 2.0.0-beta3
Redaxo: 5.7.1
Beispiel URL: https://test.kaltenbach.com/de/produkte/maschinen/bandsaegemaschinen/ wobei https://test.kaltenbach.com/de/produkte/maschinen/ der Artikel ist und bandsaegemaschinen/ vom URL Addon generiert wird.

Ausgeliefert wird der 404er Artikel mit dem Anhängsel bandsaegemaschinen/.

In der URL Tabelle gibt es folgenden (korrekten) Datensatz:
```
INSERT INTO `rex_url_generator_url` (`id`, `profile_id`, `article_id`, `clang_id`, `data_id`, `is_user_path`, `is_structure`, `url`, `sitemap`, `lastmod`, `seo`, `createdate`, `createuser`, `updatedate`, `updateuser`) VALUES
(2, 10, 1, 2, 7, 0, 0, '//test.kaltenbach.com/de/produkte/maschinen/bandsaegemaschinen/', 1, '2019-04-03T12:06:50+02:00', '{\"title\":\"Bands\\u00e4gemaschinen\",\"description\":\"\",\"image\":\"ps-startseite_produkte_bandsaegemaschinen.jpg\"}', '2019-04-07 11:48:03', 'tkrais', '2019-04-07 11:48:03', 'tkrais');
```

Aber: es wird nicht der richtige Artikel aufgerufen.

**Comment by tbaddade** [comment]
Könnte ich das mit den Datensätze aus den anderen Issues nachstellen?

**Comment by pschuchmann** [comment]
Hallo @TobiasKrais,

hast du den XCore in Verwendung? Falls ja, suche bitte mal nach dieser Passage und kommentiere sie aus.

```
// correct redaxo behaviour and send 404 if sitestartarticle = notfoundarticle
if (rexx::isFrontend()) {
	rex_extension::register('PACKAGES_INCLUDED', function(rex_extension_point $ep) {
		if (rexx::getSiteStartArticleId() == rexx::getNotfoundArticleId()) {
			if (!rexx::isCurrentUrlValid()) {
				rexx_utils::set404Status();
				rexx_utils::set404CustomPage();
			} else {
				if (rexx_utils::is404OfflineMode()) {
					rexx_utils::set404Status();
					rexx_utils::set404CustomPage();	
				}
			}
		}
	}, rex_extension::LATE);
}
```

**Comment by TobiasKrais** [comment]
@pschuchmann: XCore habe ich nicht in Verwendung. Sorry.

**Comment by pschuchmann** [comment]
@TobiasKrais Ah, ok. Start- und Fehlerartikel sind auch unterschiedlich?

**Comment by TobiasKrais** [comment]
@pschuchmann: Ja, Startartikel ist ID 1 und Fehlerartikel ID 20.

**Comment by pschuchmann** [comment]
@TobiasKrais Dann bin ich leider auch erstmal überfragt.

**Comment by TobiasKrais** [comment]
Danke trotzdem!

**Comment by alexplusde** [comment]
Wird die Datenbanktabelle extern befüllt?

Was passiert, wenn du das Neuaufbauen der URLs triggerst, bspw., indem du einen Artikel in der Struktur erstellst/umbenennst? @TobiasKrais

**Comment by TobiasKrais** [comment]
Meinst du mit Datenbanktabelle die `rex_url_generator_url`? Nein, nur das URL Addon befüllt sie. Aber das auch nicht korrekt (siehe dieser Bug https://github.com/tbaddade/redaxo_url/issues/127).

Die zweite Frage: als ich es zuletzt getestet habe, hat es nichts genutzt. Aktuell kann ich es nicht testen, da der Bug https://github.com/tbaddade/redaxo_url/issues/120 den Fatal Error im Frontend erzeugt. :-(

**Comment by TobiasKrais** [comment]
Ich sehe gerade, der Bugfix funktioniert nur, wenn man in YRewrite mehrere Domains drin hat. Wenn es nur eine ist, erhalte ich nach wie vor die 404er Seite.

**Comment by TobiasKrais** [comment]
@dtpop hatte eine super Idee: wenn man in der Zeile https://github.com/tbaddade/redaxo_url/blob/91edd6756644fd02859177f93969b98e286b0cdd/lib/Url/UrlManager.php#L267 den Wert auf `true` setzt, funktioniert das Auflösen der URL korrekt :-) - egal ob eine oder mehrere Domains.

**Comment by TobiasKrais** [comment]
Ist im aktuellen Git auch behoben. Danke!
