### ISSUE TITLE
Löschen des Profils löscht URLs nicht

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#125]
Version 2.0.0-beta3
Wenn ein Profil im Backend gelöscht wird, werden die URLs in der Tabelle rex_url_generator_url nicht gelöscht.

**Comment by alexplusde** [comment]
Sehe ich auch als Aspekt von #110

**Comment by TobiasKrais** [comment]
Ja, das könnte gut sein.

**Comment by TobiasKrais** [comment]
Funktioniert bei mir nicht. Wenn ich das Profil lösche bleiben die URLs in der Datenbank gespeichert.

**Comment by TobiasKrais** [comment]
Halt - Korrektur. Der Bugfix funktioniert. Der Fehler ist ein anderer.

**Comment by TobiasKrais** [comment]
Hintergrund: ich füge per SQL Befehl in die Profiltabelle des URL 2 Addons einen Datensatz ein. Er bekommt z.B. die ID 10. Direkt danach lösche ich per rex_delete_cache() den Redaxo Cache. Damit wird die URL Tabelle des URL 2 Addons gelöscht und neu aufgebaut. Spannend ist, dass er den URLs nun die Profil ID 9 zuweist, obwohl das Profil die ID 10 hat. Gehe ich nun her und lösche unter System manuell den Redaxo Cache wird die URL Tabelle abermals neu aufgebaut. Dieses mal wird den URLs die korrekte Profil ID 10 zugewiesen!??!

**Comment by TobiasKrais** [comment]
Wenn das löschen nicht über die ID, sondern über den namespace erfolgt würde der Fehler umgangen werden.

**Comment by tbaddade** [comment]
Der namespace kann mehrfach vergeben werden,. Da würden dann auch zusätzlich andere Profile gelöscht werden.
Der Index liegt auf `namespace article_id clang_id`

**Comment by TobiasKrais** [comment]
Oh, das ist ja sehr gut. Dieses Feature habe ich mir in Version 1.x schon gewünscht. Danke!
Den Fehler habe ich separat hier gemeldet: https://github.com/tbaddade/redaxo_url/issues/129

**Comment by tbaddade** [comment]
> Dieses Feature habe ich mir in Version 1.x schon gewünscht.

konnte man auch bereits in der 1er Version so machen.
Problematisch wurde es nur, wenn man einige Configs ohne namespace anlegte oder die Kombi `namespace + article_id + clang_id` gleich war.
