### ISSUE TITLE
Mehrsprachigkeit erzeugt zu viele URLs

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#127]
Version: 2.0.0-beta3
Szenario: URLs müssen in 4 Sprachen erzeugt werden.

Wird beim Erstellen eines Profils im Backend im Feld "In welchem Artikel erfolgt die Ausgabe" der Wert "alle Sprachen" ausgewählt, werden mir in meinem Szenario 1358  URLs angelegt (korrekt wären 280). Als Beispiel werden dabei folgende fehlerhafte URLs dabei generiert:
- //test.kaltenbach.com/en/products/machines/bandsawing-machines/kbs-620-dg/ (korrekt, Englisch)
- //test.kaltenbach.com/en/products/machines/bandsaegemaschinen/kbs-620-dg/ (falsch, wird aus Deutsch generiert)
- //test.kaltenbach.com/en/products/machines/scies-a-ruban/kbs-620-dg/ (falsch, wird aus Französisch generiert)
- //test.kaltenbach.com/en/products/machines/%D0%9B%D0%B5%D0%BD%D1%82%D0%BE%D1%87%D0%BD%D0%BE%D0%BF%D0%B8%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D1%81%D1%82%D0%B0%D0%BD%D0%BA%D0%B8/kbs-620-dg/ (falsch, wird aus Chinesisch generiert)
- //test.kaltenbach.com/en/products/machines/%E5%B8%A6%E9%94%AF%E5%88%87%E5%89%B2%E6%9C%BA%E5%BA%8A/kbs-620-dg/ (falsch, wird aus Russisch generiert - Russische Sprache ist darüber hinaus noch offline!)
Bei allen 5 genannten Datensätzen ist in der Spalte clang_id der Wert 1 (steht für Englisch) eingetragen.

**Comment by tbaddade** [comment]
> Wird beim Erstellen eines Profils im Backend im Feld "In welchem Artikel erfolgt die Ausgabe" der Wert "alle Sprachen" ausgewählt

Hast du dann die Sprache an der Tabelle zugewiesen?

**Comment by TobiasKrais** [comment]
Ja, in "Datensatz identifizieren" ist "clang_id" eingetragen. Auch in der Relationstabelle ist "clang_id" eingetragen.

Wenn ich beim Erstellen eines neuen Profiles nur eine Sprache angebe und speichere, werden 70 Datensätze erzeugt. Das ist korrekt. Bearbeite ich das Profil und wechsle auf alle Sprachen, werden insgesamt 280 Datensätze erstellt - auch korrekt. Der Fehler tritt nur beim neuen erstellen des Profils auf.

**Comment by tbaddade** [comment]
Könntest du mir auch hier Beispieldatensätze bereitstellen und einen Screenshot mitgeben, wie ich das reproduzieren kann?

**Comment by TobiasKrais** [comment]
Der Fehler liegt in diesen Zeilen: https://github.com/tbaddade/redaxo_url/blob/c40bc869d2f6723ab9204a7b7e645fb7a4dcc7bc/lib/Url/Profile.php#L601-L606
Hier eine Beispielquery vor den Zeilen:
```SELECT `data`.`machine_id` AS id, `data`.`machine_id` AS data_id, `data`.`clang_id` AS data_clang_id, `data`.`seo_description` AS data_seo_description, `data`.`picture` AS data_seo_image, `data`.`updatedate` AS data_sitemap_lastmod, `data`.`seo_title` AS data_seo_title, `data`.`name` AS data_segment_part_1 FROM `rex_d2u_machinery_url_machines` AS data WHERE (data.name != "" AND `data`.`name` IS NOT NULL) ORDER BY `data_id` asc```
Hier nach den Zeilen:
```SELECT `data`.`machine_id` AS id, `data`.`machine_id` AS data_id, `data`.`clang_id` AS data_clang_id, `data`.`seo_description` AS data_seo_description, `data`.`picture` AS data_seo_image, `data`.`updatedate` AS data_sitemap_lastmod, `data`.`seo_title` AS data_seo_title, `data`.`name` AS data_segment_part_1, `relation_1`.`category_id` AS relation_1_id, `relation_1`.`name` AS relation_1_segment_part_1 FROM `rex_d2u_machinery_url_machines` AS data LEFT JOIN `rex_d2u_machinery_url_machine_categories` AS relation_1 ON data.category_id = relation_1.category_id WHERE (data.name != "" AND `data`.`name` IS NOT NULL) ORDER BY `data_id` asc```
Letztere müsste aber so lauten:
```SELECT `data`.`machine_id` AS id, `data`.`machine_id` AS data_id, `data`.`clang_id` AS data_clang_id, `data`.`seo_description` AS data_seo_description, `data`.`picture` AS data_seo_image, `data`.`updatedate` AS data_sitemap_lastmod, `data`.`seo_title` AS data_seo_title, `data`.`name` AS data_segment_part_1, `relation_1`.`category_id` AS relation_1_id, `relation_1`.`name` AS relation_1_segment_part_1 FROM `rex_d2u_machinery_url_machines` AS data LEFT JOIN `rex_d2u_machinery_url_machine_categories` AS relation_1 ON data.category_id = relation_1.category_id AND data.clang_d = relation_1.clang_id WHERE (data.name != "" AND `data`.`name` IS NOT NULL) ORDER BY `data_id` asc```
Es fehlt im `JOIN` der Teil `AND data.clang_d = relation_1.clang_id` Ich komme nicht weiter. Kann mir jemand helfen?

**Comment by tbaddade** [comment]
> Bei allen 5 genannten Datensätzen ist in der Spalte clang_id der Wert 1 (steht für Englisch) eingetragen.

Dann ist das doch der eigentliche Fehler. Hier müssten die tatsächliche Sprach-Id bei dir eingetragen werden.

**Comment by TobiasKrais** [comment]
```SELECT `data`.`machine_id` AS id, `data`.`machine_id` AS data_id, `data`.`clang_id` AS data_clang_id, `data`.`seo_description` AS data_seo_description, `data`.`picture` AS data_seo_image, `data`.`updatedate` AS data_sitemap_lastmod, `data`.`seo_title` AS data_seo_title, `data`.`name` AS data_segment_part_1, `relation_1`.`category_id` AS relation_1_id, `relation_1`.`name` AS relation_1_segment_part_1 FROM `rex_d2u_machinery_url_machines` AS data LEFT JOIN `rex_d2u_machinery_url_machine_categories` AS relation_1 ON data.category_id = relation_1.category_id WHERE (data.name != "" AND `data`.`name` IS NOT NULL) ORDER BY `data_id` asc```
Dieser Code erzeugt folgendes Ergebnis:
![Bildschirmfoto von 2019-05-24 11-50-43](https://user-images.githubusercontent.com/4131072/58319674-62011b80-7e1a-11e9-85d8-f6e9b63a029a.png)

Wenn im im `JOIN` der Teil `AND data.clang_id = relation_1.clang_id` hinzugefügt wird, sieht das Ergebnis wie folgt aus:
![Bildschirmfoto von 2019-05-24 11-51-10](https://user-images.githubusercontent.com/4131072/58319779-8e1c9c80-7e1a-11e9-9a39-ddc87abdfba4.png)

**Comment by tbaddade** [comment]
> Bei allen 5 genannten Datensätzen ist in der Spalte clang_id der Wert 1 (steht für Englisch) eingetragen.

Dann ist diese Info von dir falsch? Zumindest scheinen die ClangIds korrekt eingetragen.

In dem Query fehlt das Join … Muss ich genauer prüfen, da hier in der Testumgebung keine zusätzlichen Urls erstellt werden.

**Comment by TobiasKrais** [comment]
> > Bei allen 5 genannten Datensätzen ist in der Spalte clang_id der Wert 1 (steht für Englisch) eingetragen.
> 
> Dann ist diese Info von dir falsch? Zumindest scheinen die ClangIds korrekt eingetragen.

Ja, damals habe ich nicht gesehen, dass es im Ergebnis weiter unten noch weitere Einträge zu der machine_id gibt. Noch ein kleiner Hinweis: ich habe in der Testumgebung nur noch 4 Sprachen im Einsatz, nicht mehr 5.

> In dem Query fehlt das Join … Muss ich genauer prüfen, da hier in der Testumgebung keine zusätzlichen Urls erstellt werden.

Das `JOIN` existiert, nur das `AND data.clang_id = relation_1.clang_id` nicht. Warum? Diese Zeile https://github.com/tbaddade/redaxo_url/blob/c40bc869d2f6723ab9204a7b7e645fb7a4dcc7bc/lib/Url/Profile.php#L604 gibt einen leeren Wert zurück (""). Hier müsste aber die Sprach-ID des Datensatzes für das `JOIN` übergeben werden.

**Comment by TobiasKrais** [comment]
Wenn diese Zeilen: https://github.com/tbaddade/redaxo_url/blob/c40bc869d2f6723ab9204a7b7e645fb7a4dcc7bc/lib/Url/Profile.php#L601-L606
wie folgt geändert werden:
```
		          $query = $relation->completeQuery(
		              $query,
		              $this->getColumnNameWithAlias('relation_'.$relation->getIndex()),
			      $this->getColumnNameWithAlias('clang_id'),
			      null
		          );
```
Dann wird das `AND data.clang_id = relation_1.clang_id` korrekt angehängt.

ABER: das löst das Problem nur, wenn in einem Profil im Feld "In welchem Artikel erfolgt die Ausgabe" in der Sprache "alle Sprachen" ausgewählt wird. Ist nur eine Sprache ausgewählt gibt es für die eine Sprache (wie bisher) mehrere Ergebnisse.

**Comment by tbaddade** [comment]
Ok danke für die Erläuterungen. Ich schaue es mir an.

**Comment by TobiasKrais** [comment]
Eigentlich wäre der Lösungsvorschlag schon ganz gut. Wenn nur eine Sprache ausgewählt wird, fehlt nur noch das `WHERE`, das die Auswahl auf eine Sprache begrenzt. Dann wäre es perfekt.

**Comment by TobiasKrais** [comment]
Auf der Testseite, von der du die Zugangsdaten hast, ist der Fix online.

**Comment by TobiasKrais** [comment]
Ist im aktuellen Git behoben. Danke!
