### ISSUE TITLE
Unterstützung für Open Graph Tags

### ISSUE THREAD

**Issue by greatif** [tbaddade/redaxo_url#128]
Während die SEO-Klasse schön komfortabel die Meta-Daten für Titel, Beschreibung etc. liefert, werden Open Graph Tags leider _(noch)_ nicht unterstützt. Viele Dienste, über die Beiträge von Blogs, News etc. geteilt werden können, greifen hierauf für eine ansprechende Darstellung zurück. _(siehe Beispiel-Grafik)_
Es wäre daher schön, wenn das Url-Addon neben den SEO-Tags auch gleich _(zumindest die wichtigsten)_ - og-Tags ausliefern würde, sodass man diese nicht "dazubasteln" muss:
```
<meta property="og:title" content="Titel" />
<meta property="og:description" content="Beschreibung." />
<meta property="og:type" content="blog, article etc." />
<meta property="og:url" content="https://domain.de/" />
<meta property="og:image" content="https://www.domain.de/bild.jpg" />
```

![opengraph](https://user-images.githubusercontent.com/8527203/55795654-9c139980-5ac8-11e9-88b2-ec2864c97d41.png)

**Comment by alexplusde** [comment]
Sollte das nicht auch erstmal yrewrite von Haus unterstützen?

**Comment by greatif** [comment]
@alexplusde in der Tat macht das das Sinn, wenn jemand das Url-Addon gar nicht nutzt, sondern nur yrewrite. Wenn man beides nutzt, dann greift man ja eigentlich nur auf die "speziellere" SEO-Klasse des Url-Addons zurück. So war mein Ausgangspunkt, sodass ich gar nicht an yrewrite gedacht habe. Aber prinzipiell hast Du m.E. vollkommen Recht, dass auch yrewrite og-Tag unterstützen sollte...

**Comment by alexplusde** [comment]
@greatif legst du da auch ein Issue an und verlinkst es hier?

**Comment by greatif** [comment]
@alexplusde

https://github.com/yakamara/redaxo_yrewrite/issues/271

**Comment by tbaddade** [comment]
Die Tags können direkt über den EP `URL_SEO_TAGS` beeinflusst werden.
