### ISSUE TITLE
Relationstabelle

### ISSUE THREAD

**Issue by fietstouring** [tbaddade/redaxo_url#134]
In URL v1 habe ich die Relationstabelle verwendet um Kategorien in den URLs abzubilden. Das hat tadellos funktioniert. In der neuen Version kann ich die Tabelle unter "Relationstabelle 1" zwar auswählen, die relevanten Parameter aus denen die URL erzeugt werden sollen werden aber nicht angezeigt. (im Quelltext sind sie da aber deaktiviert)... mach ich was falsch oder??

so sah es aus:
![relationstabelle](https://user-images.githubusercontent.com/1846849/57685213-bac0ff00-7637-11e9-840f-47d81abe321a.png)

und jetzt:
![Bildschirmfoto 2019-05-14 um 10 59 59](https://user-images.githubusercontent.com/1846849/57685219-be548600-7637-11e9-8b0c-6183e7ec3f51.png)

**Comment by tbaddade** [comment]
Welche Version verwendest du? Die Felder zu den Relationstabellen sollten ganz unten erscheinen.

**Comment by fietstouring** [comment]
ich hab das Addon gerade vor 30 Minuten von hier runtergeladen also 2.0.0-beta3

**Comment by fietstouring** [comment]
Bug?

**Comment by alexplusde** [comment]
Nochmal versucht, das Profil neu anzulegen?

**Comment by fietstouring** [comment]
das änderte nichts

**Comment by fietstouring** [comment]
`<div id="rex-relation_1_xxx_1_xxx_rex_action" class="rex-form-container" style="display:none">`

**Comment by alexplusde** [comment]
Ok, nur dass kein Missverständnis entsteht:
* Hast du URL1 auf 2beta geupdatet oder 2beta frisch installiert?
* Kannst du es komplett deinstallieren, den Cache (REDAXO und Browser) löschen, neu installieren und dann noch mal installieren?

Nur, um bestimmte Fehler mit dem Caching oder dem Updaten auszuschließen - das ist in der Beta hier evtl. noch ein Problem. Daher "beta"

**Comment by fietstouring** [comment]
ja hab ich gemacht. die DB-Tabellen löschen sich beim deinstallieren nicht, die hab ich auch gelöscht. 
Leider keine Änderung. Die URL wird zwar über das ausgewählte Feld in Relation 1 erweitert (wie schon vor dem Reinstallieren), die Auswahl des Feldes in der Relationstabelle ist aber immer noch nicht möglich.

**Comment by alexplusde** [comment]
Gibt es erkennbar Javascript-Fehler in der Browser-Konsole?

**Comment by alexplusde** [comment]
(Ansonsten mach dich gerne mal in Slack bemerkbar, falls du da bist - da lesen ein paar mehr mit...)

**Comment by tbaddade** [comment]
Kannst du mehr Infos geben zu

- REDAXO
- OS
- Browser
- Javascriptfehler

**Comment by fietstouring** [comment]
<details>
<summary>System report (REDAXO 5.7.1#9f0854f, PHP 7.2.10)</summary>

| REDAXO        |               |
| ------------: | :------------ |
|       Version | 5.7.1#9f0854f |


| PHP           |            |
| ------------: | :--------- |
|       Version | 7.2.10     |
|       OPcache | no         |
|        Xdebug | no         |


| Database      |                        |
| ------------: | :--------------------- |
|       Version | 5.7.23                 |
| Character set | utf8 (utf8_unicode_ci) |


| Server        |              |
| ------------: | :----------- |
|            OS | Darwin       |
|          SAPI | cgi-fcgi     |
|     Webserver | nginx/1.13.2 |


| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/74.0.3729.157 |
|      Protocol | HTTP/1.1             |
|         HTTPS | no                   |


| Packages                   |              |
| -------------------------: | :----------- |
|                     backup | 2.3.0        |
|                   be_style | 2.7.1        |
|        be_style/customizer | 2.7.0        |
|            be_style/redaxo | 2.7.0        |
|                    bloecks | 1.3.15       |
|           bloecks/cutncopy | 1.3.12       |
|             bloecks/status | 1.3.12       |
|               cache_warmup | 3.6.0        |
|                   ckeditor | 4.11.3.1     |
|                    cronjob | 2.4.1        |
|                  developer | 3.8.0        |
|           email_obfuscator | 2.0.0        |
|            global_settings | 2.1.0        |
|                    install | 2.5.0        |
|              massif_minify | 1.2.4-Hotifx |
|                     mblock | 3.1.0        |
|              media_manager | 2.6.0        |
|                  mediapool | 2.5.0        |
|                   metainfo | 2.4.0        |
|                      mform | 5.3.1        |
|                 mform/docs | 1.0          |
|                multiupload | 2.1.3        |
|         navigation_factory | 2.0.1        |
|                  phpmailer | 2.5.1        |
|                    project | dev          |
|           quick_navigation | 3.5.8        |
|                  search_it | 6.6.5        |
|    search_it/documentation | 6.6.5        |
|                      sprog | 1.2.0        |
|                  structure | 2.7.0        |
|          structure/content | 2.7.0        |
|           structure_tweaks | 1.1.1        |
|                      theme | 1.1.1        |
|                   ui_tools | 1.0.0        |
| ui_tools/jquery-minicolors | 2.2.7        |
|                        url | 2.0.0-beta3  |
|                      users | 2.5.2        |
|                      xcore | 1.1.3        |
|                      yform | 3.1.1        |
|                 yform/docs | 3.1.1        |
|                yform/email | 3.1.1        |
|              yform/manager | 3.1.1        |
|                 yform/rest | 3.1.1        |
|                yform/tools | 3.1.1        |
|            yform_usability | 1.4          |
|                   yrewrite | 2.5          |

</details>

**Comment by fietstouring** [comment]
keine JS Fehler

**Comment by fietstouring** [comment]
interessant, habe meine Tabellen in die Redaxo 5 Demo exportiert.
Dort funktioniert es. Gehe ich richtig in der Annahme, dass es sich um irgendeinen JS-Konflikt von einem Addon oder ähnliches handelt... bzw. wie gehe ich die Fehlersuche an?

**Comment by fietstouring** [comment]
hab den Fehler gefunden. Habe eine weitere Sprache in Redaxo angelegt. Funktioniert anscheinend nur mit mehr als einer Sprache.

**Comment by alexplusde** [comment]
Hm, das darf eigentlich nicht die Lösung sein, aber vielleicht kommt man der Sache damit näher...
