### ISSUE TITLE
Fehler bei Domain mit Umlaut!

### ISSUE THREAD

**Issue by dpf-dd** [tbaddade/redaxo_url#135]
Moin Thomas,

leider kann ich da nicht mit einem Screenshot dienen, aber ich habe soeben festgestellt, dass die aktuelle 2.x Beta noch ein Problem bei Domains mit Umlauten hat.

Sobald ich REDAXO auf einer Umlaute-Domain liegen habe und URL installiere, komme ich zwar in "Profile" rein - aber sobald ich eins anlege war es das. Jeder Klick auf das AddOn "URL" links in der Menüleiste führt nach dem Profilanlegen zu einem Whoops mit dem Fehler "Invalid URI...

**Comment by alexplusde** [comment]
Hast du versucht, die Umlaut-Domain kodiert einzutragen, also ohne Umlaut?

**Comment by tbaddade** [comment]
Der Whoop Screenshot würde schon weiterhelfen. Passiert das auch mit der Version 1.x ?

**Comment by dpf-dd** [comment]
@alexplusde 
Das nicht, dieses Projekt hatte noch eine Zweitdomain ohne Umlaut und ich bin direkt auf diese gewechselt. Danach lief das AddOn aber sofort und tat was es soll - ohne Whoops.

@tbaddade Dann werde ich heute Abend mal fix den Fehler reproduzieren und nen Screenshot erstellen.

**Comment by alexplusde** [comment]
@dpf-dd könntest du die Domain Mal als Punicode in YRewrite und/oder System direkt hinterlegen? Ich bin mir zu ca 99% sicher, dass es dann funktioniert.

Dann hätte man vielleicht nicht nur einen Workaround, sondern könnte auch an richtiger Stelle vielleicht eine Umcodierung erreichen oder zumindest in die Doku schreiben.

**Comment by dpf-dd** [comment]
Meinst du damit, dass ich bei yRewrite statt `börse.de` mal `www.xn--brse-5qa.de` versuchen soll?
Sorry, bin begrifflich bei dem Thema völlig ahnungslos (Punicode???)

**Comment by tbaddade** [comment]
> Meinst du damit, dass ich bei yRewrite statt z.B börse.de mal www.xn--brse-5qa.de versuchen soll?

genau das meinte @alexplusde 

> (Punicode???)

Suche mal nach `Punycode`

**Comment by alexplusde** [comment]
@dpf-dd läuft's damit? Ich vermute hier erstmal ein YRewrite-Problem

**Comment by tbaddade** [comment]
Kann hier zu oder sollte noch etwas gemacht werden?
ping @alexplusde @dpf-dd

**Comment by alexplusde** [comment]
Punycode ist für mich aktuell ein akzeptabler Workaround, weil auch YRewrite selbst sonst Probleme mit Umlaut-Domains hatte.

Kann das gerne prüfen, wenn eine aktuelle Version im Installer ist und ich in YRewrite wieder den Punycode entferne.

**Comment by tbaddade** [comment]
Danke dir für das Testen. Dann schließe ich zunächst einmal. Wenn noch Probleme sein sollten, dann gerne wieder öffnen.
