### ISSUE TITLE
Bei Deinstallation wird die Tabelle nicht gelöscht

### ISSUE THREAD

**Issue by gharlan** [tbaddade/redaxo_url#14]
Hatte ein Update von irgendeiner alpha gemacht. Danach bekam ich diesen Fehler:

> Error while executing statement "  SELECT      `id`,
>                            `article_id`,
>                            `clang_id`,
>                            `url`,
>                            `table`,
>                            `table_parameters`, 
>                            `relation_table`, 
>                            `relation_table_parameters`
>                FROM        rex_url_generate LIMIT 0,30"! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'relation_table' in 'field list'

Reinstallieren hat nicht geholfen. Daher dacht ich mir, probiere ich es mal mit Deinstallieren und wieder Installieren. Hat auch nicht geholfen, da die Tabelle eben nicht gelöscht wird.

**Comment by tbaddade** [comment]
Der Fehler sollte durch die update.php nicht mehr vorkommen. Bleibt die Frage, was alles nach einer Deinstallation gelöscht werden sollte. Wir handhaben das ja selbst unterschiedlich von Addon zu Addon. Was meinst du @gharlan ?

**Comment by gharlan** [comment]
Tabellen, die direkt zum Addon gehören, löschen wir eigentlich überall komplett. Würde ich hier auch machen.
