### ISSUE TITLE
Mehrfache Einschränkungen

### ISSUE THREAD

**Issue by pschuchmann** [tbaddade/redaxo_url#144]
Hey,

wir hatten eben den Fall, dass wir beim Anlegen einer Regel mehrere Felder als Einschränkung verwenden wollten. Auf Anhieb hat es nicht funktioniert und glücklicherweise hat sich das Problem nun anderweitig geregelt, dennoch wollte ich nachfragen, wie die `IN( .. )` Option sauber zu verwenden ist. In der Generator Klasse wird der Fall nicht wirklich bearbeitet und dementsprechend steigt das Backend aus. `NOT IN ( ... )` wiederum bearbeitet die Einschränkungen, aber hat zumindest mit meinen Einstellungen auch nicht funktioniert. 

Scheint verwandt zu sein mit #41, gibt es da Neues?

**Comment by tbaddade** [comment]
IN wird hier abgehandelt
https://github.com/tbaddade/redaxo_url/blob/1.0/lib/Url/Generator.php#L156

Mehrere Einschränkungen gehen erst ab der Version 2.x

**Comment by pschuchmann** [comment]
Ok, und wie kommt das dann schließlich in den SQL rein? Der ist nämlich bei uns leer geblieben. Eingegeben ist es als `wert1,wert2`

Folgende Fehlermeldung kommt zurück:
`
Error while executing statement "SELECT rex_item.id AS id,rex_item.city AS field_1,rex_item.itemname_1 AS field_2,rex_item.meta_title_1 AS seo_title,rex_item.meta_description_1 AS seo_description FROM rex_item  WHERE rex_item.city IS NOT NULL AND rex_item.city != '' AND rex_item.restriction IN  () "! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
`

**Comment by tbaddade** [comment]
Du musst an der Stelle `wert1` oder `wert2` eintragen. Das Feld/Spalte selbst beinhaltet dann `wert1,wert2,wert3`

**Comment by rkemmere** [comment]
Hallo Thomas,

wenn ich nur einen Wert abfrage nutze ich ja kein IN. 
IN wird ja genutzt um eben mehrere Werte zu kombinieren.

https://www.w3resource.com/mysql/comparision-functions-and-operators/in-function.php

Des Weiteren geht es mit aber auch mit einem Wert nicht.

**Comment by tbaddade** [comment]
> wenn ich nur einen Wert abfrage nutze ich ja kein IN.

Du willst die Datensätze auf einen Wert hin filtern.

Aus deinem Link
```
SELECT 10 IN(15,10,25);
```

Der eingetragene Wert wäre beim Filter dann `10` und deine ausgewählte Spalte enthält dann die Kommaseparierten Werte `15,10,25`. D.h. diese Spalte wird zum Bspl. via YForm select.multiple gefüllt. Falls `IN` nicht funktioniert könntest du es auch mit FIND_IN_SET testen.

**Comment by pschuchmann** [comment]
Der SQL sieht aber schon anders aus. Wir haben eben testweise einfach mal die Beschränkung auf eine gefüllte Medialist gelegt. Nehme ich nun einen Dateinamen aus dem Medienpool, müsste es laut deiner Beschreibung ja funktionieren, aber da raucht uns das Backend ab, weil der SQL nicht funktioniert.

`
SELECT rex_item.id AS id,rex_item.city AS field_1,rex_item.immo_name_1 AS field_2,rex_item.meta_title_1 AS seo_title,rex_item.meta_description_1 AS seo_description FROM rex_item WHERE rex_item.city IS NOT NULL AND rex_item.city != '' AND rex_item.picture IN () 
`
wurde versucht auszuführen, aber in dem Select erscheint die Beschränkung nicht und die möglichen Optionen erscheinen nicht in der IN Klausel.

**Comment by rkemmere** [comment]
Ich sehe die Operatoren auch als SQL Operatoren.
Demnach wäre der IN wir folgt:

`SELECT * FROM oc_delivery WHERE area_code IN ('batha','jeddah');`

Hierbei wäre die Beschränkung des area_code 'batha' und 'jeddah' in der Spalte area_code. Alle anderen Datensätze würden nicht angezeigt werden.

**Comment by rkemmere** [comment]
Ich habe mir den Code nochmal angeschaut. Es wird eine Abfrage nach INT gemacht, was doch an dieser Stelle gar keinen Sinn macht. Ein IN kann sowohl INT, TEXT oder auch FLOAT sein.

`        
                                foreach ($values as $key => $value) {
                                  if (!(int) $value > 0) {
                                    unset($values[$key]);
                                  }
                                }`

Nimmt man diese Einschränkung raus und schreibe die IN Bedingung im URL Addon richtig

`'batha','jeddah'` 

klappt auch die Generierung und die SQL Abfrage.

**Comment by tbaddade** [comment]
Sorry ich hatte hier nen Denkfehler drin … Das obige betraf m.E. FIND_IN_SET.

Im Select müsste ihr die Spalte auswählen, danach den Operator `IN(...)`. Als Werte dürfen nur Integer kommasepariert angegeben werden.

`area_code` -- `IN(...)` -- `1,2`

**Comment by rkemmere** [comment]
Laut meines Wissens und der MYSQL Dokumentation darf hier jeder value verwendet werden ungleich ob INT oder nicht.

https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#operator_in

**Comment by tbaddade** [comment]
Das mag sein, ist aber so in der Version 1. nicht vorgesehen und scheinbar bisher auch nicht gebraucht worden. Ihr könnt gern einen PR beisteuern.

**Comment by pschuchmann** [comment]
#145 sollte das nun beheben.

**Comment by tbaddade** [comment]
Danke für den PR
