### ISSUE TITLE
Ooops in der Sitemap beseitigen (Codevorschlag)

### ISSUE THREAD

**Issue by dtpop** [tbaddade/redaxo_url#150]
Ich schreib das mal als Issue und nicht als PR. Die Sitemap.xml verursacht in Url2 Beta 3 ein oooops, wenn in den Settings eingestellt ist, dass die Datensatz Urls auch in die Sitemap sollen (was in der Regel wünschenswert ist).
Hierfür müssen zwei Zeilen in der lib/Url/Seo.php ausgetauscht werden.
Zeile 143 neu:
`$url = Url::get($profileUrl['url']);`
Zeile 149 neu:
`"\n".'<lastmod>'.$profileUrl['lastmod'].'</lastmod>'.`
Ich hab das im Warehouse (Redaxo Shop Addon) gebraucht und mit der Änderung läuft es einwandfrei. Das Url AddOn ist der Knaller :+1:

**Comment by tbaddade** [comment]
Danke … @lexplatt hat bereits einen PR für [Seo](https://github.com/tbaddade/redaxo_url/pull/141) erstellt. Eventuell ist damit dein Problem beseitigt.

**Comment by TobiasKrais** [comment]
Der PR funktioniert auch: https://github.com/tbaddade/redaxo_url/pull/142

**Comment by tbaddade** [comment]
close via 3de25047b4768d86321445520bcd2f7d9dfee904
