### ISSUE TITLE
Idente Titel automatisch umschreiben

### ISSUE THREAD

**Issue by fietstouring** [tbaddade/redaxo_url#157]
Es wäre cool wenn das Addon bei identen Titeln von Einträgen (die eine idente URL erzeugen würden und daher nicht zulässig sind) diese automatisch umschreiben würde (z.b. mit einem fortlaufendem numerischen Suffix). Derzeit funktioniert nur eine bei Existenz von gleichlautenden Titeln/Urls daher muss man eindeutige Titel verwenden.

**Comment by tbaddade** [comment]
Ist es nicht sinnvoller, den Titel via YForm gleich auf unique validieren zu lassen?

**Comment by fietstouring** [comment]
Für meine Anwendung nicht. Da gibt es Events in einer Art Kalender, die immer den gleichen Titel haben und monatlich stattfinden. Da soll der Titel immer gleich sein.

**Comment by tbaddade** [comment]
Es geht aber darum das du eindeutige Urls haben willst?
Dann könntest du dich so zunächst behelfen.

<img width="1320" alt="Bildschirmfoto 2019-09-02 um 14 04 58" src="https://user-images.githubusercontent.com/338267/64113487-b9ecde00-cd8a-11e9-993c-6a7a2d8418c1.png">

**Comment by fietstouring** [comment]
Danke für den Hinweis! Ich denke dass ist eine zufriedenstellende Umsetzung für die Anwendung! Hab das gleich eingestellt.
