### ISSUE TITLE
Exception: Invalid URI bei Aufruf einer Seite im Backend

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#164]
Wenn ich im Sprog die Inhalte einer Sprache in eine andere Sprache kopieren möchte kommt folgender Fehler.

**InvalidArgumentException:** Invalid URI 'https://meinedomain.com/redaxo/index.php?page=sprog.copy.structure_content_generate&articles=1.1,7.1,10.1,40.1&params[clangFrom]=1&params[clangTo]=12&params[deleteBefore]=1'
**File:** redaxo/src/addons/url/vendor/Kit-UrlParser/src/Uri.php
**Line:** 54

<details>
<summary>Stacktrace</summary>

| Function                              | File                                                                    | Line     |
| ------------------------------------- | ----------------------------------------------------------------------- | -------- |
| Riimu\Kit\UrlParser\Uri->__construct  | redaxo/src/addons/url/lib/Url/Url.php                                   | 35       |
| Url\Url->__construct                  | redaxo/src/addons/url/lib/Url/Url.php                                   | 207      |
| Url\Url::getCurrent                   | redaxo/src/addons/url/lib/Url/UrlManager.php                            | 393      |
| Url\UrlManager::getRewriteUrl         | redaxo/src/addons/url/boot.php                                          | 74       |
| rex_package->{closure}                | redaxo/src/core/lib/extension.php                                       | 45       |
| rex_extension::registerPoint          | redaxo/src/addons/structure/functions/function_rex_url.php              | 41       |
| rex_getUrl                            | redaxo/src/addons/d2u_machinery/lib/category.php                        | 573      |
| Category->getURL                      | rex:///module/86/output                                                 | 38       |
| require                               | redaxo/cache/addons/structure/7.12.content                              | 35       |
| require                               | redaxo/src/addons/structure/plugins/content/lib/article_content.php     | 102      |
| rex_article_content->getArticle       | redaxo/src/addons/sprog/lib/Sprog/Copy/StructureContent.php             | 72       |
| Sprog\Copy\StructureContent::fire     | redaxo/src/addons/sprog/pages/sprog.copy.structure_content_generate.php | 19       |
| include                               | redaxo/src/core/lib/packages/package.php                                | 228      |
| rex_package->includeFile              | redaxo/src/core/lib/be/controller.php                                   | 474      |
| rex_be_controller::includePath        | redaxo/src/core/lib/be/controller.php                                   | 413      |
| rex_be_controller::includeCurrentPage | redaxo/src/core/backend.php                                             | 215      |
| require                               | redaxo/src/core/boot.php                                                | 135      |
| require                               | redaxo/index.php                                                        | 9        |

</details>
<details>
<summary>System report (REDAXO 5.8.0, PHP 7.3.11-nmm1)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.8.0      |

| PHP           |             |
| ------------: | :---------- |
|       Version | 7.3.11-nmm1 |
|       OPcache | no          |
|        Xdebug | no          |

| Database      |                            |
| ------------: | :------------------------- |
|       Version | 5.6.44-nmm1-log            |
| Character set | latin1 (latin1_swedish_ci) |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/70.0 |
|      Protocol | HTTP/1.1     |
|         HTTPS | yes          |

| Packages                                         |             |
| -----------------------------------------------: | :---------- |
|                                         be_style | 2.8.0       |
|                              be_style/customizer | 2.8.0       |
|                                  be_style/redaxo | 2.8.0       |
|                                          bloecks | 2.0.1       |
|                                   bloecks/status | 2.0.1       |
|                                   cookie_consent | 3.0.0-beta3 |
|                                          cronjob | 2.5.0       |
|                                      d2u_address | 1.1.1       |
|                                       d2u_helper | 1.6.1       |
|                    d2u_helper/translation_helper | 1.6.1       |
|                                      d2u_history | 1.0.0       |
|                                         d2u_jobs | 1.0.9       |
|                           d2u_jobs/hr4you_import | 1.0.9       |
|                                      d2u_linkbox | 1.2.2       |
|                                    d2u_machinery | 1.3.1       |
|                   d2u_machinery/industry_sectors | 1.3.1       |
|         d2u_machinery/machine_features_extension | 1.3.1       |
| d2u_machinery/machine_steel_processing_extension | 1.3.1       |
|                      d2u_machinery/used_machines | 1.3.1       |
|                                         d2u_news | 1.1.2       |
|                                   d2u_news/fairs | 1.1.2       |
|                                      d2u_partner | 1.0         |
|                                   d2u_references | 1.0.6       |
|                                        d2u_staff | 1.0.2       |
|                                       d2u_videos | 1.0.7       |
|                                  emailobfuscator | 2.1.5       |
|                                          install | 2.5.0       |
|                                    media_manager | 2.7.0       |
|                        media_manager_autorewrite | 1.1.0       |
|                                        mediapool | 2.6.0       |
|                                         metainfo | 2.5.0       |
|                                  multinewsletter | 3.2.5       |
|                                        phpmailer | 2.6.0       |
|                                            sprog | 1.2.0       |
|                                        structure | 2.8.0       |
|                                structure/content | 2.8.0       |
|                                         tinymce4 | 1.2.1       |
|                                              url | 2.0.0-beta3 |
|                                            users | 2.5.2       |
|                                             ycom | 3.0-beta4   |
|                                        ycom/auth | 3.0-beta4   |
|                                       ycom/group | 3.0-beta4   |
|                                  ycom/media_auth | 3.0-beta4   |
|                                            yform | 3.2         |
|                                       yform/docs | 3.2         |
|                                      yform/email | 3.2         |
|                                    yform/manager | 3.2         |
|                                         yrewrite | 2.6         |
|                                  yrewrite_scheme | 3.1.0       |

</details>

**Comment by TobiasKrais** [comment]
Warum wird der Code beim Kopieren von Sprog ausgeführt? Sonst ist der Bug in Sprog zu suchen.

**Comment by TobiasKrais** [comment]
Den Bug würde ich gerne lösen, hab aber keine Ahnung wo ich ansetzen kann :-(

**Comment by tbaddade** [comment]
Ich schau mir das bei Zeiten an. Habe da schon ne Idee.

**Comment by isospin** [comment]
Bin da auch gerade drauf gestoßen... (REDAXO 5.9.0, PHP 7.3.15)

**Comment by TobiasKrais** [comment]
Er stört sich an den eckigen Klammern. Es reicht als Testfall folgenden Parameter an eine URLanzuhängen: ?t[t]

**Comment by tbaddade** [comment]
https://github.com/Riimu/Kit-UrlParser/issues/3

**Comment by tbaddade** [comment]
Wie oft passiert das bei euch? Denn eigentlich kann es jederzeit auftreten, sobald die `[ ]` dabei sind. Ich würde daher gern erst einmal abwarten, ob Riikka die Lib aktualisiert.

**Comment by TobiasKrais** [comment]
Passiert bei mir im Frontend eigentlich nie, da ich die eckigen Klammern vermeide. Im Sprog Addon passiert es immer, wenn ich die Inhalte kopiere (siehe URL in meiner ursprünglichen Fehlermeldung).

**Comment by tbaddade** [comment]
Die Url wird im Sprog jetzt besser kodiert
https://github.com/tbaddade/redaxo_sprog/commit/098e0600055e055ca15ae741923fea8284f5dc32

**Comment by TobiasKrais** [comment]
Cool! Danke!

**Comment by tbaddade** [comment]
Passiert auch bei Relationen von YForm. @xong Kannst du den Bug hier verschreiben, sodass man diesen nachstellen kann.

**Comment by TobiasKrais** [comment]
Mega! Danke!
