### ISSUE TITLE
Bug: Backend URL wird deformiert

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#165]
Wenn ich die URL index.php?page=content&article_id=302&clang=3&ctype= aufrufen möchte
werde ich auf die URL index.php/page=content/index.php/page=content/index.php?page=structure weitergeleitet. Artikel ID ist in einem URL Profil hinterlegt. Der Fehler tritt nur bei einem Profil auf.

@rotzek hat den Fehler auch schon beobachtet.

Stefan Dannfald hat es dadurch gelöst, dass er einen älteren Stand der Git Versionen genommen hat, den er noch zur Verfügung hatte.

**Comment by TobiasKrais** [comment]
Das betrifft nur Artikel die nur ein Artikel ist. Bei Kategorien funktioniert es. Vermutung: der Bug liegt hier irgendwo drin: https://github.com/tbaddade/redaxo_url/blob/3dacaafa33a0e7390e79a5fd9b2e5bd8c0e17680/boot.php#L49-L59

Der Code sollte eigentlich verhindern, dass Kategorien nicht gelöscht werden können. Aber bei reinen Artikeln funktioniert das nicht. Dahingehend sollte der Code sowieso verbessert werden.

**Comment by dpf-dd** [comment]
[url.zip](https://github.com/tbaddade/redaxo_url/files/3907283/url.zip)

Diese Version habe ich ersatzweise genommen. Sie funktioniert bei mir und hat den Fehler noch nicht. Sie müsste aus dem Zeitraum April-September sein.

**Comment by TobiasKrais** [comment]
Danke @dpf-dd. Der Fehler liegt hier: https://github.com/tbaddade/redaxo_url/blob/3dacaafa33a0e7390e79a5fd9b2e5bd8c0e17680/lib/Url/UrlManager.php#L265-L270

**Comment by TobiasKrais** [comment]
https://www.kaltenbach.com/de/unternehmen/karriere/stellenangebote/berufserfahrene/softwareentwickler-8211-schwerpunkt-pc-m-w-d-11463?x=y

**Comment by TobiasKrais** [comment]
https://github.com/tbaddade/redaxo_url/issues/70
