### ISSUE TITLE
Fatal Error in Sitemap auf mehrsprachigen Seiten

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#169]
Beim Aufruf der sitemap.xml kommt nachfolgender Fehler. Für den Absturz verantwortlich ist folgender Commit: https://github.com/tbaddade/redaxo_url/commit/b7887dbbee9db702970bb9223e45520d001af3ea#diff-3dc848e2fb64c30179a87a28a67ea933

**Error:** Call to a member function isOnline() on null
**File:** redaxo/src/addons/url/lib/Url/Seo.php
**Line:** 129

<details>
<summary>Stacktrace</summary>

| Function                      | File                                            | Line     |
| ----------------------------- | ----------------------------------------------- | -------- |
| Url\Seo::getSitemap           | redaxo/src/addons/url/boot.php                  | 85       |
| rex_package->{closure}        | redaxo/src/core/lib/extension.php               | 45       |
| rex_extension::registerPoint  | redaxo/src/addons/yrewrite/lib/yrewrite/seo.php | 266      |
| rex_yrewrite_seo->sendSitemap | redaxo/src/addons/yrewrite/boot.php             | 121      |
| rex_package->{closure}        | redaxo/src/core/lib/extension.php               | 45       |
| rex_extension::registerPoint  | redaxo/src/core/packages.php                    | 31       |
| include_once                  | redaxo/src/core/frontend.php                    | 16       |
| require                       | redaxo/src/core/boot.php                        | 135      |
| require                       | index.php                                       | 9        |

</details>
<details>
<summary>System report (REDAXO 5.8.1, PHP 7.3.11-nmm1)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.8.1      |

| PHP           |             |
| ------------: | :---------- |
|       Version | 7.3.11-nmm1 |
|       OPcache | no          |
|        Xdebug | no          |

| Database      |                            |
| ------------: | :------------------------- |
|       Version | 5.6.44-nmm1-log            |
| Character set | latin1 (latin1_swedish_ci) |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/70.0 |
|      Protocol | HTTP/1.1     |
|         HTTPS | yes          |

| Packages                                         |             |
| -----------------------------------------------: | :---------- |
|                                     accessdenied |             |
|                                         be_style | 2.8.1       |
|                              be_style/customizer | 2.8.0       |
|                                  be_style/redaxo | 2.8.1       |
|                                          bloecks | 2.1.1       |
|                                   bloecks/status | 2.1.1       |
|                                   cookie_consent | 3.0.0-beta3 |
|                                          cronjob | 2.5.0       |
|                                      d2u_address | 1.1.1       |
|                                       d2u_helper | 1.6.1       |
|                    d2u_helper/translation_helper | 1.6.1       |
|                                      d2u_history | 1.0.0       |
|                                         d2u_jobs | 1.0.9       |
|                           d2u_jobs/hr4you_import | 1.0.9       |
|                                      d2u_linkbox | 1.2.2       |
|                                    d2u_machinery | 1.3.1       |
|                   d2u_machinery/industry_sectors | 1.3.1       |
|         d2u_machinery/machine_features_extension | 1.3.1       |
| d2u_machinery/machine_steel_processing_extension | 1.3.1       |
|                      d2u_machinery/used_machines | 1.3.1       |
|                                         d2u_news | 1.1.2       |
|                                   d2u_news/fairs | 1.1.2       |
|                                      d2u_partner | 1.0         |
|                                   d2u_references | 1.0.6       |
|                                        d2u_staff | 1.0.2       |
|                                       d2u_videos | 1.0.7       |
|                                 email_obfuscator |             |
|                                          install | 2.5.0       |
|                                    media_manager | 2.7.0       |
|                        media_manager_autorewrite | 1.1.0       |
|                                        mediapool | 2.6.1       |
|                                         metainfo | 2.5.1       |
|                                  multinewsletter | 3.2.6       |
|                                        phpmailer | 2.6.0       |
|                                            sprog | 1.2.0       |
|                                        structure | 2.8.1       |
|                                structure/content | 2.8.1       |
|                                         tinymce4 | 1.2.1       |
|                                         uploader |             |
|                                              url | 2.0.0-beta3 |
|                                            users | 2.5.3       |
|                                             ycom | 3.0-beta4   |
|                                        ycom/auth | 3.0-beta4   |
|                                       ycom/group | 3.0-beta4   |
|                                  ycom/media_auth | 3.0-beta4   |
|                                            yform | 3.3.1       |
|                                       yform/docs | 3.3.1       |
|                                      yform/email | 3.3.1       |
|                                    yform/manager | 3.3.1       |
|                                         yrewrite | 2.6         |
|                                  yrewrite_scheme | 3.1.1       |

</details>

**Comment by TobiasKrais** [comment]
Der Grund ist der, dass auf mehrsprachigen Seiten in den Einstellungen "Alle Sprachen" ausgewählt werden kann. Dann ist die SprachID des Profiles null und verursacht den fatal error.

**Comment by tbaddade** [comment]
Danke dir für die ausführliche Beschreibung
