### ISSUE TITLE
Sprache: wenn Artikel offline wird auf andere Sprache ausgewichen

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#17]
Beispiel: Standardsprache ist Deutsch. Wenn ein Artikel, der für eigene URLs verwendet wird in Englisch Offline ist, wird die URL in Deutsch generiert.
Lösungsvorschläge:
a) Es werden gar keine URLs erstellt, da Artikel offline ist (das wäre mein Wunsch)
b) Es werden die URLs mit der korrekten Sprache erstellt.

**Comment by tbaddade** [comment]
> Standardsprache ist Deutsch. Wenn ein Artikel, der für eigene URLs verwendet wird in Englisch Offline ist, wird die URL in Deutsch generiert.

Ob der Artikel online oder offline ist interessiert dem Addon nicht. 

Meine Vermutung
- deine Config ist nicht ganz richtig (poste mal deinen Screenshot)
- eigenes YRewrite Scheme

**Comment by TobiasKrais** [comment]
Hmmm. Ich kann den Fehler jetzt nicht mehr nachvollziehen. Vermutlich muss es tatsächlich an einer Fehlkonfiguration gelegen haben. Sorry für die Störung.
