### ISSUE TITLE
URL 2 / Einschränken: ungleich

### ISSUE THREAD

**Issue by isospin** [tbaddade/redaxo_url#173]
Wenn ich die die Url Erzeugung einschränken möchte und `text_1 != ""` anlege funktioniert die einschränkung nicht. Wenn ich aber `text_1 > ""` anlege wird die Url Erzeugung eingeschränkt. Eigentlich müsste `text_1 != ""` doch auch funktionieren...

![url2_einschränken](https://user-images.githubusercontent.com/1148347/71252891-82e50d00-2326-11ea-95e9-c7ed86646208.png)

**Comment by alexplusde** [comment]
ich fände es sinnvoller, hier direkt die WHERE-Bedingung aus SQL eingeben zu können. Dann wäre es eine Zeile und jeder kann frei seine Bedingungen formulieren.

**Comment by tbaddade** [comment]
Dann müsste man im  das where beim abfragen zerlegen und wieder zusammensetzen. Dann wäre es einfacher, dass der Admin den Query komplett selbst notiert inkl. aller Relationen und Einschränkungen.

**Comment by alexplusde** [comment]
An Relationen habe ich nicht gedacht :/

**Comment by tbaddade** [comment]
@isospin Ich würde gern diese Diskussion abwarten wollen. https://github.com/redaxo/redaxo/issues/3729

**Comment by tbaddade** [comment]
@isospin Es gibt es jetzt einen weiteren Vergleichsoperator `!= ""`. Das Textfeld dabei leer lassen. Wäre schön, wenn du es mit deinem Profil Gegentesten könntest.
