### ISSUE TITLE
rex_url_generator_url in rex_tmp_url_generator_url umbenennen

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#183]
Damit die Tabelle nicht im Backup landet, es handelt sich ja nur um eine im Betrieb notwendige Tabelle mit Daten, die aus den Profilen erzeugt werden.

**Comment by tbaddade** [comment]
Das mag sei, aber die Tabelle würde beim Export weiterhin gelistet werden und somit im Backup dabei sein. Wer das nicht mag kann diese deselektieren.

Ansonsten sehe ich hier zunächst Bedarf beim Core, sodass man bewusst Tabellen vom Backup ausschließen kann ohne das man eigene Tabellen umbenennen muss.

**Comment by alexplusde** [comment]
tmp-Tabellen werden automatisch vom Backup ausgeschlossen.

Dies ist bereits im Core der Fall:
https://github.com/redaxo/redaxo/pull/3004/files

**Comment by tbaddade** [comment]
> tmp-Tabellen werden automatisch vom Backup ausgeschlossen.

Die werden mit angezeigt, wie die `rex_user` Tabelle.

**Comment by alexplusde** [comment]
Sie werden nicht automatisch vorausgewählt

![image](https://user-images.githubusercontent.com/3855487/77785610-ba1d3580-705c-11ea-8797-36861ddbf5be.png)

**Comment by TobiasKrais** [comment]
Das wird neuer Standard. Andere Addons wie search_it haben schon umgestellt. PR ist gemacht.

**Comment by TobiasKrais** [comment]
Eine Entscheidung bezüglich dieses Issues wäre super. Es ist ein sehr großer PR in search_it anhängig, der auf diese Entscheidung wartet.

**Comment by tbaddade** [comment]
Verwende das hier:

https://github.com/tbaddade/redaxo_url/blob/master/lib/Url/UrlManagerSql.php#L16

Damit wärst du auf der sicheren Seite.

**Comment by TobiasKrais** [comment]
Kommt darauf an, ob du den Redaxo temp prefix `rex::getTempPrefix()` hart kodieren willst oder nicht. im search_it addon ist der nicht hart kodiert und daher nicht in der Konstanten enthalten.

**Comment by tbaddade** [comment]
Ich empfinde das tmp Präfix ist falsch. Es ist ja keine temporäre Tabelle die jeder Zeit wieder gelöscht werden kann. Ich fände es besser, wenn man dem Backup AddOn mitteilen kann, welche Tabelle für ein Export sinnvoll ist und welche nicht. Das Präfix ist da nur ein Notbehelf in meinen Augen.

**Comment by alexplusde** [comment]
Aber das kann man doch mit diesem gottverdammten Präfix

**Comment by TobiasKrais** [comment]
Was die Meinung angeht, gehe ich mit euch beiden einig. Fakt ist, dass hier ein Redaxo Standard geschaffen wurde und die Definition für diesen Standard auf die url_generate_url Tabelle zutrifft. Wir müssen uns fragen: Ordnen wir uns diesem Standard unter oder nicht?
