### ISSUE TITLE
Normalisierung von URLs erweitern um bestimmte Zeichen

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#184]
Beispiel rex_media: 

![image](https://user-images.githubusercontent.com/3855487/77768853-5c302400-7043-11ea-82ff-0edcd18b53bb.png)

hier sollte in der URL auch ein `.` erlaubt sein - dieser wird wegnormalisiert.

Kann mir gut vorstellen, dass man auch andere utf-8-Zeichen in anderen Sprachen beibehalten will. Diese sollten url_encoded werden können.

**Comment by tbaddade** [comment]
> hier sollte in der URL auch ein . erlaubt sein - dieser wird wegnormalisiert.

Das müsste am verwendeten Rewriter liegen.

**Comment by alexplusde** [comment]
Danke für die Info, das war mir nicht bewusst.
