### ISSUE TITLE
Extension Points "URL_POST_SAVE" und "URL_DELETED" gesucht.

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#185]
Brauche kurz einen Tipp: ich erweitere gerade das search_it Addon dahingehend, dass es URLs aus dem URL Addon indexieren kann (https://github.com/FriendsOfREDAXO/search_it/tree/url2). Das funktioniert soweit auch sehr gut. Nur kann ich Änderungen noch nicht automatisch überwachen.

Es gibt ja den Extension Point "URL_PRE_SAVE". Aber er setzt einen Tick zu früh an. Ich bräuchte einen "URL_POST_SAVE", "URL_DELETED" oder einfach "URL_UPDATED". Besteht Interesse daran, dass diese EPs programmiert werden oder soll ich die Reindexierung aus meinem Code heraus aufrufen?

**Comment by tbaddade** [comment]
Bin mir nicht sicher ob es der richtige Ansatz ist. Wäre es nicht sinnvoller, sobald sich der eigentliche Datensatz bei YForm geändert hat den Suchindex zu starten? Die Url kann man sich so holen.

Ansonsten würde ich an [dieser Stelle](https://github.com/tbaddade/redaxo_url/blob/master/lib/Url/Profile.php#L405) einen allgemeinen EP wie `URL_SAVED` anlegen, der die Url enthält.

Du müsstest dann am besten die Urls erst einmal einsammeln bevor du den Index startest.

**Comment by TobiasKrais** [comment]
Ich bin mir auch nicht ganz sicher, ob es das überhaupt benötigt. YForm nutze ich nicht, daher entfällt die Möglichkeit. Aber ich könnte in meinem Code die Anpassung des Index manuell anstoßen.

Meinstest du für den EP [hier](https://github.com/tbaddade/redaxo_url/blob/a2db315c537210d39beb4269a5548ccc7679655c/lib/Url/Profile.php#L407)?

**Comment by tbaddade** [comment]
Ja schon wobei das Negieren im if wegfällt. Deshalb hatte ich es vor dem if hier im Issue notiert.

**Comment by tbaddade** [comment]
Ist das noch aktuell @TobiasKrais

**Comment by TobiasKrais** [comment]
Ja. Inzwischen kann ich auch mehr dazu sagen. Es wäre gut, wenn man folgende Extension Points hätte:

- URL_DELETED_ALL: wenn alle URLs gelöscht wurden. Dieser EP müsste [hier](https://github.com/tbaddade/redaxo_url/blob/3b694428e38db6e43159cfc4ea236480d93ec4e2/lib/Url/UrlManagerSql.php#L189) eingehängt werden.
- URL_DELETED_DATASET: wenn nur ein Dataset gelöscht wird. Dieser EP müsste [hier](https://github.com/tbaddade/redaxo_url/blob/3b694428e38db6e43159cfc4ea236480d93ec4e2/lib/Url/UrlManagerSql.php#L202) eingehängt werden.
- URL_SAVED: wenn eine URL angelegt wurde. Dieser EP müsste [hier](https://github.com/tbaddade/redaxo_url/blob/3b694428e38db6e43159cfc4ea236480d93ec4e2/lib/Url/UrlManagerSql.php#L163) eingehängt werden. Vor dem Hintergrund dieses EP wäre es sehr gut, wenn es eine weitere Methode geben würde, die nur eine einzige neue URL speichert. Warum? Im Moment können nur die URLs eines gesamten Profils im URL Addon generiert werden. Siehe hier: [`Profile:createAndSaveUrls()`](https://github.com/tbaddade/redaxo_url/blob/3b694428e38db6e43159cfc4ea236480d93ec4e2/lib/Url/Profile.php#L268). Da der Aufruf dieses EP aus dem search_it Addon jede URL neu indiziert, kann das je nach Anzahl URLs sehr auf die Performance drücken. Dieser Nachteil würde entfallen, wenn man eine einzelne URL hinzufügen kann.

**Comment by tbaddade** [comment]
Vielleicht kannst du kurz erklären, wie das Search AddOn die Urls benötigt und wie es generell damit dann umgeht. Was passiert genau? Mir ist z.Bsp. nicht klar, warum es für das Löschen von Urls ein EP benötigt

Allgemein, es gibt verschiedene Szenarien:

1. Alle Urls werden gelöscht und neu erstellt
1. Alle Urls bestimmter Profile werden gelöscht und neu erstellt
1. Sobald ein Datensatz angelegt oder geändert wird, werden dessen Urls gelöscht und neu erstellt

**Comment by TobiasKrais** [comment]
Das ist eine gute Frage. Vorab schon mal: als Identifikator der URLs wird im search_it Addon der url_hash eingesetzt.

Im Moment gibt es nur 2 Möglichkeiten die URLs zu indexieren: entweder manuell oder per Cronjob. Jedes mal werden alle im search_it Index vorhandenen URL Einträge gelöscht und dann neu aufgebaut.

Das search_it Addon kann die URLs entweder einzeln oder alle zusammen löschen. Eine Löschmöglichkeit für ein Profil gibt es derzeit nicht. Daher wäre es interessant, wenn ein Extension Point die Hashes der gelöschten URLs als Array enthält.

Beim Aufbauen des Suchindex indexiert search_it jede URL einzeln. Die dafür verwendete Methode lautet `indexURL($url_hash, $article_id, $clang_id, $profile_id, $data_id)`.

Beantwortet das deine Frage?

**Comment by alexplusde** [comment]
(man möchte z.B. bei einer neuen URL diese gezielt indexieren, bei einer Veränderung reindexieren und beim Löschen deindexieren, ohne das für die drölfzigtausend ebenfalls machen zu müssen, die eigentlich gleich geblieben sind)

**Comment by tbaddade** [comment]
Wenn search_it die URLs in einer separaten Tabelle speichert, dann könnte man einen EP setzen, dass Änderungen an der url-Tabelle vorgenommen wurden. search_it könnte dann einen Abgleich zw. beiden Tabellen machen. Wäre das nicht performanter?

**Comment by TobiasKrais** [comment]
Damit wäre es möglich gelöschte URLs und neue URLs zu erkennen. Auch wäre es möglich das letzte Änderungsdatum auszulesen und damit einen Reindex zu ermöglichen. Ich denke, das wäre eine super Lösung.
@alexplusde: was denkst du?

**Comment by TobiasKrais** [comment]
Vorbereitungen im search_it Addon wären getroffen: https://github.com/FriendsOfREDAXO/search_it/pull/277

Die Änderungen im search_it Addon haben die Performance des bisherigen Cronjobs extrem verbessert. Danke @tbaddade für die tolle Idee!

**Comment by TobiasKrais** [comment]
@tbaddade: ich würde das gerne weiter voranbringen. Wie sollte der neue EP heißen? URL_TABLE_UPDATED? Welche Daten würde man übergeben? Vermutlich gar keine. Zumindest braucht man durch den Vergleich der Tabellen keine.

**Comment by TobiasKrais** [comment]
Hab mir gerade mal angeschaut, wo der EP geladen werden sollte. Eindeutig sollte der EP in der Methode [`Profiles->createAndSaveUrls()`](https://github.com/tbaddade/redaxo_url/blob/ede7c47bf529f39dd135d2ba801435fbb4f475eb/lib/Url/Profile.php#L406-L408) geladen werden. Damit würden alle **neu angelegten** und **aktualisierten URLs** erfasst.

Problematischer wird es die **gelöschten URLs** zu erfassen. Warum? Zwar gibt es hier die Methoden `UrlManagerSql::deleteAll()`, `UrlManagerSql::deleteByProfileId()` und `UrlManagerSql::deleteByProfileIdAndDatasetId()`. Aber meistens werden nach dem Aufruf dieser Methoden die URLs neu generiert. Würde man aus den Löschfunktionen heraus den neuen EP aufrufen, würde im search_it Addon der Index gelöscht werden um dann kurz darauf den kompletten Index wieder zu erstellen.

Wie könnte man das Problem am einfachsten Lösen? Indem den Löschfunktionen ein Parameter hinzugefügt wird mit dem das Auslösen des EPs gesteuert wird. @tbaddade: Hast du da eine bessere Idee?

**Comment by TobiasKrais** [comment]
Da fällt mir eine weitere Möglichkeit ein: in den Löschfunktionen wird der EP gar nicht aufgerufen, sondern nur beim Löschen eines Profils, also hier: https://github.com/tbaddade/redaxo_url/blob/ede7c47bf529f39dd135d2ba801435fbb4f475eb/pages/generator.profiles.php#L30-L48

**Comment by TobiasKrais** [comment]
Noch zum Aufruf des EP beim Speichern der URLs: wenn alle Profile im Backend neu generiert werden, wird der EP auch mehrfach aufgerufen, für jedes Profil einzeln. :-(

**Comment by tbaddade** [comment]
Ich würde den EP wohl eher hier definieren.
https://github.com/tbaddade/redaxo_url/blob/master/lib/Url/Generator.php#L57

Als Name schwebt mir bis jetzt `URL_GENERATOR_EXECUTED` vor. Was meinst du?

**Comment by TobiasKrais** [comment]
Ich habe mir heute Nacht nochmals viele Gedanken dazu gemacht. Wenn die Generator Klasse die einzige Schnittstelle nach außen ist, wäre das denkbar. Dann fehlt nur noch ein EP aufruf in einer noch nicht existierenden Methode `Profile->delete()` die ein Profil mitsamt URLs löscht.

Dagegen spricht, dass in der README.md unter "Beispiel: URL-Pathlist neu generieren" wird ein Codebeispiel genannt, wie man die URLs eines Profils neu generiert. Ruft jemand diesen Code auf wird der EP nicht aufgerufen.

Eventuell wäre folgendes eine sauberere Lösung. Wir erstellen 3 neue Methoden in der Profile Klasse die den EP aufrufen:

- `Profile->delete()`
- `Profile::rebuildAllUrls()` (statische Methode, generiert die URLs aller Profile neu)
- `Profile->rebuildUrls()` (generiert die URLs dieses Profils neu)

Alle weiteren Methoden die eine Änderung der URLs in der Datenbank zur Folge haben könnten dann auf protected statt public gesetzt werden um zu verhindern, dass sie von außerhalb des Addons aufgerufen werden und uns damit Änderungen entgehen.

Was denkst du?

**Comment by tbaddade** [comment]
Warum es einen EP beim löschen benötigt ist mir nicht ganz klar. Vielleicht auch, weil ich nicht weiß wie search_it tatsächlich arbeitet. Ich verstehe das AddOn immer weniger ;)

Neue Methoden? Ich weiß nicht so recht. Ich sehe keinen wirklichen Mehrwert darin. Ich mache mir nochmal Gedanken dazu.

**Comment by alexplusde** [comment]
Wenn eine URL nicht mehr existiert, dann müssen die entsprechenden Daten auch aus dem search it Index. Sonst verwaisen die Verweise.

**Comment by tbaddade** [comment]
Dann passt m.E. immer noch der EP beim Generator. Urls werden nur gelöscht, wenn sie denn auch wieder aufgebaut werden. Das Löschen ist nur ein bereinigen der Datenbank.

**Comment by tbaddade** [comment]
Arg … ich muss mir das genauer ansehen.

**Comment by alexplusde** [comment]
Ich biete an, eine Einführung in search_it zu geben.

**Comment by TobiasKrais** [comment]
@tbaddade: Schon ein bischen weiter gekommen wo der EP am besten platziert werden sollte?

**Comment by tbaddade** [comment]
> Schon ein bischen weiter gekommen wo der EP am besten platziert werden sollte?

Nein … leider nicht … die Tests hier stellten mich nicht zufrieden.

**Comment by TobiasKrais** [comment]
Ich hab mir auch Gedanken gemacht. Die Idee den EP nur im Generator auszulösen finde ich sehr komfortabel. Was wäre, wenn man dem `Generator::execute()` einen `ExtensionPointManager::MODE_DELETE_PROFILE` oder etwas in der Art hinzufügt?

**Comment by TobiasKrais** [comment]
Die Lösung ist für das search_it URL unglücklich. Warum? Der EP wird zu oft aufgerufen:

- Beim ersten Aufruf des EPs werden alle URLs des Profils gelöscht.
- Danach wird der EP für jede URL einzeln aufgerufen. In Folge wird diese eine URL von search_it indexiert. Bei mehreren 100 URLs kann das sehr lange dauern. Und: wird dabei auf einer Seite die gerade indexiert wird eine URL genutzt, die noch nicht generiert ist, wird der EP bei der URL Generierung iterativ nochmals aufgerufen, ... Es kann im ungünstigsten Fall also passieren, dass der EP mehrfach so oft aufgerufen wird wie er eigentlich sollte. Das drückt nochmals massiv auf die Performance.

Lösungsvorschlag: Ziel wäre es, dass der EP erst aufgerufen wird, wenn alle anstehenden Aktivitäten in der URL Tabelle abgeschlossen ein. Wie könnte das erreicht werden?

- Der Aufruf des EP wird, wie ursprünglich vorgeschlagen, in die `Generator::execute()` Methode verschoben und zusätzlich wird er beim Löschen eines Profils ausgelöst.
- Wenn Änderungen an der URL Tabelle vorgenommen werden wird irgendwo ein Flag gesetzt, mit dem sich die Änderungen triggern lassen. Dann wird am Ende dieser Flag geprüft und wenn er existiert wird der EP aufgerufen.

**Comment by tbaddade** [comment]
>  Ziel wäre es, dass der EP erst aufgerufen wird, wenn alle anstehenden Aktivitäten in der URL Tabelle abgeschlossen ein.

Warum kann `search_it` das nicht einsammeln?
Für mein Empfinden, werden die EPs jetzt korrekt getriggert.

**Comment by TobiasKrais** [comment]
Ja, das können wir so lösen. Ich habe mich mit Norbert kurz geschlossen. Dann sammeln wir das und arbeiten das nach der Sammlung ab. Danke dir!

**Comment by AndiLeni** [comment]
Ich hätte aktuell einen sehr ähnlichen anwendungsfall für einen POST EP.
Artikel sollen per curl analysiert werden wenn sich deren Inhalt ändert.
Die Yform EPs greifen leider zu früh, genauso wie URL_PRE_SAVE.
