### ISSUE TITLE
Sollte das addon den profile cache leeren/löschen, wenn unter system cache-löschen gewählt wird?

### ISSUE THREAD

**Issue by staabm** [tbaddade/redaxo_url#190]
Getriggert aus slack conversation

> Problem: ich schreibe im url 2 Addon etwas in die Datenbank und lasse danach den Cache  neu generieren. Allerdings wird der gerade in der Datenbank geänderte Wert nicht mit generiert, sondern der "alte" Wert. PHPMyAdmin sagt aber, dass die Änderung korrekt durchgeführt wurde.

**Comment by tbaddade** [comment]
Verstehe das Problem nicht.

> ich schreibe im url 2 Addon etwas in die Datenbank und lasse danach den Cache neu generieren. 

Welcher Cache wird gelöscht? System Cache, der Profile Cache im Url AddOn?

> Allerdings wird der gerade in der Datenbank geänderte Wert nicht mit generiert, sondern der "alte" Wert. PHPMyAdmin sagt aber, dass die Änderung korrekt durchgeführt wurde.

Welcher Wert wird geändert? Welche Tabelle ist genau betroffen?

**Comment by staabm** [comment]
Der user updated via sql eine wert in der db und die php api liefert aber den neuen wert nicht.

Es wird rex_delete_cache() cache aufgerufen. 

Alle details siehe slack conversation von heute.

Macht es sinn dass dee url addon cache nicht geleert wird bei rex_delete_cache() oder wäre es einfacher wenn es das tun würde (da man als verwender nicht für jedes addon jeden cache einzeln löschen will/muss)?

**Comment by tbaddade** [comment]
Danke. Werde mir das im Slack bei Gelegenheit durchlesen.

**Comment by staabm** [comment]
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1591874095420300

**Comment by tbaddade** [comment]
Danke dir nochmals für das Übertragen von Slack hierher ins Repo.
