### ISSUE TITLE
Fatal Error beim Anlegen eines Media Manager Profils

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#192]
Wenn ich im Media Manager Addon ein Profil anlege kommt folgender Fehler:

**rex_sql_exception:** Unable to fetch row.
**File:** redaxo/src/core/lib/sql/sql.php
**Line:** 775

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                       | Line     |
| -------------------------------------------- | ---------------------------------------------------------- | -------- |
| rex_sql->getRow                              | redaxo/src/core/lib/sql/sql.php                            | 750      |
| rex_sql->fetchValue                          | redaxo/src/core/lib/sql/sql.php                            | 697      |
| rex_sql->getValue                            | redaxo/src/addons/url/lib/Url/ExtensionPointManager.php    | 143      |
| Url\ExtensionPointManager->normalize         | redaxo/src/addons/url/lib/Url/ExtensionPointManager.php    | 47       |
| Url\ExtensionPointManager->__construct       | redaxo/src/addons/url/boot.php                             | 39       |
| rex_package->{closure}                       | redaxo/src/core/lib/extension.php                          | 49       |
| rex_extension::{closure}                     | redaxo/src/core/lib/util/timer.php                         | 60       |
| rex_timer::measure                           | redaxo/src/core/lib/extension.php                          | 56       |
| rex_extension::registerPoint                 | redaxo/src/addons/debug/lib/extensions/extension_debug.php | 20       |
| rex_extension_debug::registerPoint           | redaxo/src/core/lib/base/factory_trait.php                 | 89       |
| rex_extension::callFactoryClass              | redaxo/src/core/lib/extension.php                          | 35       |
| rex_extension::registerPoint                 | redaxo/src/core/lib/form/form.php                          | 382      |
| rex_form->save                               | redaxo/src/core/lib/form/form_base.php                     | 1164     |
| rex_form_base->get                           | redaxo/src/addons/media_manager/pages/types.php            | 186      |
| include                                      | redaxo/src/core/lib/packages/package.php                   | 250      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                      | 476      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                         | 60       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                      | 477      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                      | 432      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/media_manager/pages/index.php            | 22       |
| include                                      | redaxo/src/core/lib/packages/package.php                   | 250      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                      | 476      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                         | 60       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                      | 477      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                      | 415      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                                | 235      |
| require                                      | redaxo/src/core/boot.php                                   | 137      |
| require                                      | redaxo/index.php                                           | 9        |

</details>
<details>
<summary>System report (REDAXO 5.11.0-beta1, PHP 7.4.5, MySQL 5.7.28)</summary>

| REDAXO        |              |
| ------------: | :----------- |
|       Version | 5.11.0-beta1 |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.5      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.28 |
| Character set | utf8mb4      |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/78.0 |
|      Protocol | HTTP/2.0     |
|         HTTPS | yes          |

| Packages                |              |
| ----------------------: | :----------- |
|                be_style | 2.11.0-beta1 |
|     be_style/customizer | 2.11.0-beta1 |
|         be_style/redaxo | 2.11.0-beta1 |
|              d2u_helper | 1.6.2        |
|                   debug | 1.0.0-beta1  |
|                 install | 2.8.0-beta1  |
|           media_manager | 2.10.0-beta1 |
|               mediapool | 2.9.0-beta1  |
|                metainfo | 2.7.2-beta1  |
|               phpmailer | 2.9.0-beta1  |
|                 project | dev          |
|               search_it | 6.7.0        |
|  search_it/autocomplete | 6.7.0        |
| search_it/documentation | 6.7.0        |
|     search_it/plaintext | 6.7.0        |
|         search_it/stats | 6.7.0        |
|                   sprog | 1.2.0        |
|               structure | 2.11.0-beta1 |
|       structure/content | 2.11.0-beta1 |
|                     url | 2.0.0-beta3  |
|                   users | 2.7.0-beta1  |
|                   yform | 3.4          |
|             yform/email | 3.4          |
|           yform/manager | 3.4          |
|                yrewrite | 2.7b2        |

</details>

**Comment by alexplusde** [comment]
Kann das Problem bestätigen. Meta Infos ist genauso davon betroffen.

**Comment by skerbis** [comment]
https://github.com/tbaddade/redaxo_url/issues/193 
sked und feeds ebenso und anscheinend immer beim Anlegen neuer Datensätze

**Comment by skerbis** [comment]
Es knallt beim  EP 'REX_FORM_SAVED',

**Comment by rolandsee** [comment]
Jetzt ist mir auch klar,woher diese Fehler kommen. Konnte ich bisher nicht zuordnen: 
![image](https://user-images.githubusercontent.com/4113894/89518439-31b55b00-d7db-11ea-8f87-430c3630b409.png)

**Comment by tbaddade** [comment]
Der Fehler ist, dass rex_sql für leere Rows jetzt eine Exception wirft.

Dieser Commit ist die Ursache, dass es jetzt whoopste.
https://github.com/redaxo/redaxo/commit/a4cfc38005da40f6714a8fd52e03af0927d654d3#diff-043c74c6dcb9f93bd03809b49467087cL735
