### ISSUE TITLE
URL erzeugt Fehler bei Speicher-Aktionen in anderen Addons

### ISSUE THREAD

**Issue by iceman-fx** [tbaddade/redaxo_url#193]
Wenn url aktiv ist, wird nach jedem Speichern in anderen Addons (z.B. sked & feeds) ein Fehler geworfen

**rex_sql_exception:** Unable to fetch row.
**File:** redaxo/src/core/lib/sql/sql.php
**Line:** 775

Dieser Fehler komt, wenn nach dem Speichern z.B. zur Übersichtsseite zurückgewechselt wird.
Ist das url-Addon deaktiviert, stellt sich das normale Verhalten wieder ein.

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                    | Line     |
| -------------------------------------------- | ------------------------------------------------------- | -------- |
| rex_sql->getRow                              | redaxo/src/core/lib/sql/sql.php                         | 750      |
| rex_sql->fetchValue                          | redaxo/src/core/lib/sql/sql.php                         | 697      |
| rex_sql->getValue                            | redaxo/src/addons/url/lib/Url/ExtensionPointManager.php | 143      |
| Url\ExtensionPointManager->normalize         | redaxo/src/addons/url/lib/Url/ExtensionPointManager.php | 47       |
| Url\ExtensionPointManager->__construct       | redaxo/src/addons/url/boot.php                          | 39       |
| rex_package->{closure}                       | redaxo/src/core/lib/extension.php                       | 49       |
| rex_extension::{closure}                     | redaxo/src/core/lib/util/timer.php                      | 54       |
| rex_timer::measure                           | redaxo/src/core/lib/extension.php                       | 56       |
| rex_extension::registerPoint                 | redaxo/src/core/lib/form/form.php                       | 382      |
| rex_form->save                               | redaxo/src/core/lib/form/form_base.php                  | 1164     |
| rex_form_base->get                           | redaxo/src/addons/sked/pages/entries.php                | 513      |
| include                                      | redaxo/src/core/lib/packages/package.php                | 250      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                   | 476      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                      | 54       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                   | 477      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                   | 432      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/sked/pages/index.php                  | 10       |
| include                                      | redaxo/src/core/lib/packages/package.php                | 250      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                   | 476      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                      | 54       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                   | 477      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                   | 415      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                             | 235      |
| require                                      | redaxo/src/core/boot.php                                | 137      |
| require                                      | redaxo/index.php                                        | 9        |

</details>
<details>
<summary>System report (REDAXO 5.11.0, PHP 7.3.13, MySQL 5.7.29)</summary>
</details>

Scheint hiermit zusammen zuhängen: https://github.com/tbaddade/redaxo_url/issues/192

**Comment by tbaddade** [comment]
Duplicate #192
