### ISSUE TITLE
Call to undefined method Url\Seo::getTitleTag()

### ISSUE THREAD

**Issue by skerbis** [tbaddade/redaxo_url#195]
Aus der Readme übernommen: 

Aktuelle GitHub-Version

```php
<?php
    $urlSeo = new Url\Seo();
    echo $urlSeo->getTitleTag().PHP_EOL;
    echo $urlSeo->getDescriptionTag().PHP_EOL;
    echo $urlSeo->getRobotsTag().PHP_EOL;
    echo $urlSeo->getHreflangTags().PHP_EOL;
    echo $urlSeo->getCanonicalUrlTag().PHP_EOL;
    ?>
``

was mache ich falsch?

**Comment by skerbis** [comment]
Ach wie einfach ... es reicht: 

   $urlSeo = new Url\Seo();
    echo $urlSeo->getTags();

**Comment by tbaddade** [comment]
Aber nur mit der GH Version und diesen PR beachten
https://github.com/yakamara/redaxo_yrewrite/pull/310

**Comment by fietstouring** [comment]
habe das auch grad bemerkt. Mir fehlt da leider dass man den Titel der Website da nicht einbauen kann...
in Zeile 62 in Seo.php steht

`$tags['og:url'] = '<meta property="og:url" href="'.$fullUrl.'" />';`

statt href müsste da "content" stehen
