### ISSUE TITLE
Problem wenn suffix = .html in yRrewrite / yRewrite_scheme

### ISSUE THREAD

**Issue by skerbis** [tbaddade/redaxo_url#196]
Wenn als Suffix .html für Yrewrite in Yrewrite_scheme gewählt wurde, wird auf die Startseite geleitet anstelle dass der Newsartikel aufgerufen wird. 
Das hat mit 1.x noch funktioniert. 
Im Log kann ich nichts entdecken. 

Ich weiß nicht ob das issue hier hin gehört oder nach yrewrite scheme bzw yrewrite. 

@tbaddade hast du ne Idee?

**Comment by tbaddade** [comment]
- Wurden die Urls bereits generiert und da hast erst später das Suffix umgestellt?
- Sind Urls bereits in der DB-Tabelle vorhanden?
- Haben diese Urls bereits den Suffix `.html`?

**Comment by skerbis** [comment]
Ich habe die Urls extra neu generieren lassen. Und sie stehen auch mit .html in der DB

**Comment by skerbis** [comment]
false auf true ändern. 
https://github.com/tbaddade/redaxo_url/blob/ebcee1b994a33abdff9da65f065ba421a504f4c6/lib/Url/UrlManager.php#L265

**Comment by tbaddade** [comment]
Danke
