### ISSUE TITLE
Fehler beim Anlegen eines SKED Eintrags:  rex_sql_exception Unable to fetch row.

### ISSUE THREAD

**Issue by isospin** [tbaddade/redaxo_url#199]
Sobald in URL 2 ein Profil angelegt ist, bei dem auf die Tabelle rex_sked_entries verwiesen wird und in SKED ein neuer Termin angelegt wird fliegt folgender Fehler:

rex_sql_exception: Unable to fetch row.
File: redaxo/src/core/lib/sql/sql.php
Line: 775

vermutlich verwandt mit #192

SKED 1.10.0 oder 2.0.2
URL 2.0.0-beta3 (aktuelle github version)
REDAXO 5.11.0 oder  5.11.1

ein dd($object->getSql()); https://github.com/tbaddade/redaxo_url/blob/ebcee1b994a33abdff9da65f065ba421a504f4c6/lib/Url/ExtensionPointManager.php#L148

liefert:
```
rex_sql {#359 ▼
    #debug: 0
    #values: []
    #rawValues: []
    #fieldnames: array:30 [▶]
    #rawFieldnames: array:30 [▶]
    #tablenames: array:1 [▶]
    #lastRow: []
    #table: ""
    #wherevar: ""
    #whereParams: []
    #rows: 0
    #counter: 0
    #query: "SELECT * FROM rex_sked_entries WHERE id=0 LIMIT 2"
    #params: []
    #DBID: 1
    -lastInsertId: "0"
    #records: []
    #stmt: PDOStatement {#365 ▶}
}
```

der eintrag landet in der rex_sked_entries tabelle...

**Comment by tbaddade** [comment]
Das Issue müsste zu Sked nicht zum Url Addon … Es müsste geklärt werden, warum beim EP REX_FORM_SAVED keine Daten mehr enthalten sind. Url hat den Fehler nur aufgedeckt, kann ihn selbst aber m.E. nicht beheben.
