### ISSUE TITLE
Benutzerdefinierte URL

### ISSUE THREAD

**Issue by nilsology** [tbaddade/redaxo_url#2]
Erhält der Redaxo Artikel einen benutzerdefinierten URL wird dieser im Rewrite (glaube ich) verändert; folgendermaßen:

__produkt__ wird zu __produk__
__produkte__ wird zu __produkt__

es wird jeweils der letzte Buchstabe weggetrimmt.

**Comment by tbaddade** [comment]
Bin mir nicht sicher, ob es nicht eher ein Fehler von yrewrite ist. Das Suffix steht bei dir sicherlich noch auf **"/"** (Slash) [^Scheme ansehen] aber die Url wird ohne Suffix also dem Slash **(/)** gespeichert?

[^Scheme ansehen]: https://github.com/yakamara/redaxo_yrewrite/blob/master/lib/scheme.php#L13

**Comment by nilsology** [comment]
Genau steht auf '/'. Der Url wird ohne '/' gespeichert, nimmt auch keine '/' an.

**Comment by tbaddade** [comment]
Custom Urls können jetzt bei yrewrite auch mit einem Slash am Ende eingetragen werden.
