### ISSUE TITLE
"Verwaiste" Trennerzeichen bei leeren Feldern

### ISSUE THREAD

**Issue by polarpixel** [tbaddade/redaxo_url#200]
Wenn man die URL aus zwei oder drei Feldern generiert und das zweite und/oder dritte Feld leer ist, erscheint am Ende der URL trotzdem das Trennerzeichen.
In meinem Fall kommt es auch vor, dass das erste Feld leer ist und nur das zweite ein Pflichtfeld ist.

Meiner Einschätzung nach wäre ew sinnvoll zu prüfen, ob am Anfang oder Ende wegen eines leeren Feldes ein Trennerzeichen "übrig" ist und dieses dann zu entfernen.

**Comment by tbaddade** [comment]
Ist anscheinend in der aktuellen Version bereits behoben.
