### ISSUE TITLE
Tabellennamen mit Präfix `rex__` machen Probleme

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_url#201]
Tabellen, die einen doppelten Unterstrich nutzen, z.B. `rex__product`, führen zu einem Whoops. 

![image](https://user-images.githubusercontent.com/3855487/100229985-5b7ac500-2f25-11eb-94ed-3a739e682cdf.png)

Es wird bereits das Profil nicht korrekt abgespeichert, daraus entsteht dann ein Folgefehler

![image](https://user-images.githubusercontent.com/3855487/100229969-5289f380-2f25-11eb-8f26-1b52655411a2.png)

**Comment by alxndr-w** [comment]
War halt keine gute Idee, kommt halt auch nicht wirklich häufig vor.

**Comment by tbaddade** [comment]
It aber ein legitimer Tabellennamen.

**Comment by tbaddade** [comment]
Das liegt an `rex_form` und diesem Aufruf im Profilformular:
`$f = $fieldContainer->addGroupedField($group, $type, $name);`

durch den Aufruf in der Methode `addGroupedField` von 
`$field->setAttribute('name', $this->getAttribute('name').'['.$group.']['.$field->getFieldName().']');` 
wird die übergebene $group (hier im Profilformular der Tabellenname) normalisiert, sodass der `__` zu einem `_` wird.

@gharlan Sollte `rex_form` an der Stelle das mehrfache Löschen einen Zeichens besser zulassen.

**Comment by gharlan** [comment]
kann ich spontan nicht einschätzen.
ich würde das problem wahrscheinlich eher ignorieren, solange es keinen neuen Melder gibt.
