### ISSUE TITLE
"Unable to fetch row." beim Anlegen neuer Inhalte

### ISSUE THREAD

**Issue by rkemmere** [tbaddade/redaxo_url#203]
Sobald das URL Addon aktiv ist kommt es zum Fehler "Unable to fetch row." beim Anlegen von Kategorien in der Struktur und auch im Addon Global Konfig. 

REDAXO 5.11 / 5.11.1

in REDAXO 5.9 war es noch ok.

**Comment by alxndr-w** [comment]
Dies kann in Verbindung stehen zu fehlerhaften YForm-Tabellendefinitionen - muss aber nicht.

Am besten ein Backup machen, dann Felddefinitionen in jeder Tabelle aktualisieren und schauen, ob nicht Relationsfelder o.ä. ungültig sind.

**Comment by rkemmere** [comment]
Danke Alex. Ich versuch das mal ...

**Comment by tbaddade** [comment]
Kannst du mehr Infos wie z.Bsp. den Stack liefern? Konntest du selbst das Problem weiter einschränken?

**Comment by rkemmere** [comment]
`rex_sql_exception thrown with message "Unable to fetch row."

Stacktrace:
#21 rex_sql_exception in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/lib/sql/sql.php:775
#20 rex_sql:getRow in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/lib/sql/sql.php:750
#19 rex_sql:fetchValue in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/lib/sql/sql.php:697
#18 rex_sql:getValue in /var/www/vhosts/isyfair/htdocs/redaxo/src/addons/url/lib/Url/ExtensionPointManager.php:139
#17 Url\ExtensionPointManager:normalize in /var/www/vhosts/isyfair/htdocs/redaxo/src/addons/url/lib/Url/ExtensionPointManager.php:47
#16 Url\ExtensionPointManager:__construct in /var/www/vhosts/isyfair/htdocs/redaxo/src/addons/url/boot.php:39
#15 rex_package:{closure} in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/lib/extension.php:49
#14 rex_extension:{closure} in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/lib/util/timer.php:54
#13 rex_timer:measure in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/lib/extension.php:56
#12 rex_extension:registerPoint in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/lib/form/form.php:382
#11 rex_form:save in /var/www/vhosts/isyfair/htdocs/redaxo/src/addons/global_settings/lib/table_expander.php:216
#10 rex_global_settings_table_expander:save in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/lib/form/form_base.php:1164
#9 rex_form_base:get in /var/www/vhosts/isyfair/htdocs/redaxo/src/addons/global_settings/pages/field.php:111
#8 require in /var/www/vhosts/isyfair/htdocs/redaxo/src/addons/global_settings/pages/index.php:23
#7 include in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/lib/packages/package.php:250
#6 rex_package:includeFile in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/lib/be/controller.php:476
#5 rex_be_controller:{closure} in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/lib/util/timer.php:54
#4 rex_timer:measure in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/lib/be/controller.php:477
#3 rex_be_controller:includePath in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/lib/be/controller.php:415
#2 rex_be_controller:includeCurrentPage in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/backend.php:235
#1 require in /var/www/vhosts/isyfair/htdocs/redaxo/src/core/boot.php:137
#0 require in /var/www/vhosts/isyfair/htdocs/redaxo/index.php:10
`

**Comment by rkemmere** [comment]
Ich habe es mal in einer fast leeren REDAXO Instanz probiert. Sobald das URL Addon aktiv ist, wird der Fehler beim Anlegen im Global Konfig Addon geworfen. Selbst ohne das beim URL Addon etwas konfiguriert wurde.

**Comment by tbaddade** [comment]
> Passiert das auch ohne das Addon Global Konfig?

Kannst du das noch beantworten?

**Comment by rkemmere** [comment]
Ich reproduziere aktuell mit dem Addon Global Konfig das Verhalten. In der Stuktur tritt es leider nur sporadisch auf.

**Comment by tbaddade** [comment]
Kannst du mal nachsehen ob diese Zeilen bei dir im AddOn enthalten sind

https://github.com/tbaddade/redaxo_url/commit/aa0019bde1a5ccc78a4cc46fb484fdc177f7ae00

**Comment by rkemmere** [comment]
In der Version auf dem Server haben diese Zeilen gefehlt. Habe mir gerade noch mal die aktuelle Github Version gezogen. Mit der scheint das nicht mehr zu passieren. Ich teste das nochmal auf einer anderen Installation

**Comment by tbaddade** [comment]
> Ich teste das nochmal auf einer anderen Installation

Danke

**Comment by rkemmere** [comment]
Ja geht jetzt wieder überall wo die 2er Version installiert war und ich die aktuelle github Version genommen habe.

**Comment by tbaddade** [comment]
Danke für dein Feedback
