### ISSUE TITLE
only variables should be passed by reference - Bei Aufruf der sitemap.xml

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_url#205]
**ErrorException:** Only variables should be passed by reference
**File:** redaxo/src/addons/url/lib/Url/Seo.php
**Line:** 170

<details>
<summary>Stacktrace</summary>

| Function                       | File                                            | Line     |
| ------------------------------ | ----------------------------------------------- | -------- |
| rex_error_handler::handleError | redaxo/src/addons/url/lib/Url/Seo.php           | 170      |
| Url\Seo::getSitemap            | redaxo/src/addons/url/boot.php                  | 84       |
| rex_package->{closure}         | redaxo/src/core/lib/extension.php               | 49       |
| rex_extension::{closure}       | redaxo/src/core/lib/util/timer.php              | 60       |
| rex_timer::measure             | redaxo/src/core/lib/extension.php               | 56       |
| rex_extension::registerPoint   | redaxo/src/addons/yrewrite/lib/yrewrite/seo.php | 268      |
| rex_yrewrite_seo->sendSitemap  | redaxo/src/addons/yrewrite/boot.php             | 120      |
| rex_package->{closure}         | redaxo/src/core/lib/extension.php               | 49       |
| rex_extension::{closure}       | redaxo/src/core/lib/util/timer.php              | 60       |
| rex_timer::measure             | redaxo/src/core/lib/extension.php               | 56       |
| rex_extension::registerPoint   | redaxo/src/core/packages.php                    | 31       |
| include_once                   | redaxo/src/core/frontend.php                    | 16       |
| require                        | redaxo/src/core/boot.php                        | 137      |
| require                        | index.php                                       | 9        |

</details>
<details>
<summary>System report (REDAXO 5.11.1, PHP 7.4.15, MySQL 5.7.32)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.11.1     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 7.4.15                         |
|       OPcache | no                             |
|        Xdebug | no                             |
|       Warning | Das Setup wird ohne HTTPS/Verschlüsselung durchgeführt. Es wird empfohlen jegliche Frontend und Backend aufrufe nur mittels HTTPS durchzuführen, um die Privatsphäre und den Datenschutz zu gewährleisten. |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.32 |
| Character set | utf8mb4      |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/88.0.4324.150 |
|      Protocol | HTTP/1.1             |
|         HTTPS | no                   |

| Packages                |             |
| ----------------------: | :---------- |
|            accessdenied | 1.0.6       |
|                  across | 3.0.0-dev23 |
|          across/backend | 3.0.0       |
|                 adminer | 1.8.2       |
|                  backup | 2.6.2       |
|                be_style | 2.11.1      |
|         be_style/redaxo | 2.11.1      |
|                 bloecks | 3.0.0       |
|        bloecks/cutncopy | 3.0.0       |
|          bloecks/status | 3.0.0       |
|            cache_warmup | 3.6.1       |
|                    cke5 | 4.2.1       |
|      cke5/documentation | 1.0.0       |
|         consent_manager | 2.0.1       |
|                 cronjob | 2.7.1       |
|  cronjob/article_status | 2.7.1       |
| cronjob/optimize_tables | 2.7.1       |
|               developer | 3.9.0       |
|                  events | 2.0.0-dev   |
|                   feeds | 3.1         |
|                 install | 2.8.0       |
|             maintenance | 2.5.0       |
|                markitup | 3.6.0       |
|                  mblock | 3.1.0       |
|           media_manager | 2.10.1      |
|               mediapool | 2.9.0       |
|                metainfo | 2.7.2       |
|                   mform | 5.3.1       |
|              mform/docs | 1.0         |
|                  minify | 2.2         |
|                   neues | 2.0.0-dev   |
|               phpmailer | 2.9.1       |
|                 product | 2.0.0-dev   |
|                 project | dev         |
|        quick_navigation | 3.9.5       |
|               redactor2 | 4.1.0       |
|                   sprog | 1.2.0       |
|               structure | 2.11.1      |
|       structure/content | 2.11.1      |
|       structure/version | 2.11.0      |
|                   theme | 1.2.0       |
|                uploader | 2.2.0       |
|                     url | 2.0.0-beta3 |
|                   users | 2.7.1       |
|                  watson | 2.2.0       |
|                    ycom | 4.0.3       |
|               ycom/auth | 4.0.3       |
|               ycom/docs | 4.0.3       |
|              ycom/group | 4.0.3       |
|                   yform | 3.4.1       |
|             yform/email | 3.4.1       |
|           yform/manager | 3.4.1       |
|           yform_geo_osm | 1.2.3       |
|   yform_spam_protection | 1.0.5       |
|         yform_usability | 1.4         |
|                yrewrite | 2.7         |
|             zip_install | 1.1         |

</details>

**Comment by isospin** [comment]
+1
bin da auch gerade drüber gestolpert...

in meinem projekt werden urls aus drei tabellen erzeugt. es scheint aber, das lediglich eine tabelle diese notice bewirkt: 
es werden 34 notices ausgespuckt und es gibt in einer tabelle 34 datensätze (die anderen haben mehr)




<details>
<summary>System report (REDAXO 5.11.2, PHP 7.2.24-0ubuntu0.18.04.7, MySQL 5.7.26)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.11.2     |


| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 7.2.24-0ubuntu0.18.04.7        |
|       OPcache | yes                            |
|        Xdebug | no                             |
|       Warning | Die verwendete PHP Version 7.2.24-0ubuntu0.18.04.7 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden. |


| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.26 |
| Character set | utf8mb4      |


| Server        |                |
| ------------: | :------------- |
|            OS | Linux          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.29  |


| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/86.0 |
|      Protocol | HTTP/1.1     |
|         HTTPS | yes          |


| Packages                    |             |
| --------------------------: | :---------- |
|                     adminer | 1.8.3       |
|                      backup | 2.6.3       |
|                 be_password | 2.0.0       |
|                    be_style | 2.11.1      |
|         be_style/customizer | 2.11.0      |
|             be_style/redaxo | 2.11.1      |
|                     bloecks | 3.0.2       |
|            bloecks/cutncopy | 3.0.2       |
|           bloecks/dragndrop | 3.0.2       |
|                cache_warmup | 3.6.1       |
|                     cronjob | 2.7.1       |
|                     cropper | 1.1.0       |
|                   developer | 3.9.0       |
|                  focuspoint | 3.0.1       |
|             global_settings | 2.5.1       |
|                     install | 2.8.1       |
|                    markitup | 3.6.0       |
|      markitup/documentation | 1.1.0       |
|                      mblock | 3.1.0       |
|               media_manager | 2.10.1      |
|                   mediapool | 2.9.1       |
|                    metainfo | 2.7.3       |
|                       mform | 5.3.1       |
|                  mform/docs | 1.0         |
|                      minify | 2.2         |
|            navigation_array | 1.1.1       |
|                   phpmailer | 2.9.1       |
|                     project | dev         |
|             project_manager | 1.3.0       |
|      project_manager/client | 1.1.0       |
|            quick_navigation | 3.9.5       |
|                   search_it | 6.7.3       |
|     search_it/documentation | 6.7.3       |
|         search_it/plaintext | 6.7.3       |
|             search_it/stats | 6.7.3       |
|                       sprog | 1.2.0       |
|                   structure | 2.11.2      |
|           structure/content | 2.11.2      |
|                       theme | 1.2.0       |
|            uikit_collection | 2.4.1       |
|                    uploader | 2.2.0       |
|                         url | 2.0.0-beta3 |
|                       users | 2.7.1       |
|                      watson | 2.2.0       |
|               xoutputfilter | 3.0.0-beta1 |
| xoutputfilter/documentation | 1.0.0       |
|      xoutputfilter/frontend | 3.0.0       |
|                       yform | 3.4.1       |
|                 yform/email | 3.4.1       |
|               yform/manager | 3.4.1       |
|                 yform/tools | 3.4.1       |
|             yform_usability | 1.4         |
|                    yrewrite | 2.7         |
|             yrewrite_scheme | 3.3.0       |

</details>

**Comment by tbaddade** [comment]
Zeile 170 wie hier anpassen
https://github.com/tbaddade/redaxo_url/commit/1e1ea993ab11144458e8d9ca68d9a0b9f6361af4

**Comment by isospin** [comment]
hat geholfen!
 danke @tbaddade

**Comment by alxndr-w** [comment]
Danke für die schnelle Hilfe @tbaddade

**Comment by alxndr-w** [comment]
Wenn der fix schon im Code drin ist, kann das Issue doch zu?

**Comment by tbaddade** [comment]
> Wenn der fix schon im Code drin ist, kann das Issue doch zu?

Der Fix ist in einer anderen Zeile. Zeile 170 müsste wie die Zeilen 79+80 aussehen.
