### ISSUE TITLE
sitemap.xml - Erweiterung der Sitemap nur auf angeforderte Domain beschränken 

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_url#206]
Ich habe hier ein Multidomain-Setup mit Produkten für 2 Websites - in der sitemap.xml der Sitemap unter Domain 1 tauchen URLs der Sitemap von Domain 2 auf.

**Comment by skerbis** [comment]
Kann ich bestätigen

**Comment by tbaddade** [comment]
close via d272a15fb956293ef247b7b640fb7c9ebc0a3975
