### ISSUE TITLE
Installation via GitHub / zip_installer erzeugt Probleme - beta in den Installer?

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_url#207]
Ich wäre wirklich dankbar, wenn die aktuelle Version wieder im Installer landet - sie ist an vielen Stellen praxiserporbt, wenn auch vlt. nicht perfekt.

Gerade habe ich mir ins Knie geschossen, weil ich die aktuelle Version per zipinstaller aus GitHub laden wollte, die intl-Erweiterung jedoch auf dem Server nicht existierte und das Addon in Version 1 schon ersetzt wurde, Version 2 sich jedoch nicht installieren ließ.

Die Rolle rückwärts wäre nicht nötig gewesen, wenn der reguläre Installer-Ablauf eingehalten hätte werden können.

**Comment by tbaddade** [comment]
> Gerade habe ich mir ins Knie geschossen, weil ich die aktuelle Version per zipinstaller aus GitHub laden wollte, die intl-Erweiterung jedoch auf dem Server nicht existierte.

Was ist der zipinstaller? Ist das eine Alternative zum Installer des Core? Prüft der zipinstaller auf Abhängigkeiten?

**Comment by alxndr-w** [comment]
> Ist das eine Alternative zum Installer des Core?
> Prüft der zipinstaller auf Abhängigkeiten?

Ja, nein. 

Hier geht es weiter. #209
