### ISSUE TITLE
v2 in den Installer?

### ISSUE THREAD

**Issue by IngoWinter** [tbaddade/redaxo_url#209]
Jede Woche schlägt mindestens eine im Slack auf, die irgendein Problem mit v1 hat. Sie kriegt dann stets die Empfehlung, sich v2 auf Github runterzuladen. Aber auch nicht das letzte Release, sondern besser den aktuellen Stand. Das ist keine transparente oder effiziente Art Software zu verteilen.

**Comment by skerbis** [comment]
https://github.com/tbaddade/redaxo_url/issues/207

**Comment by tbaddade** [comment]
> Sie kriegt dann stets die Empfehlung, sich v2 auf Github runterzuladen. 

Die Empfehlung gibt die Community.

> Aber auch nicht das letzte Release, sondern besser den aktuellen Stand. Das ist keine transparente oder effiziente Art Software zu verteilen.

Die Transparenz ist für mich soweit vorhanden, dass die GH Version eben nicht im Installer ist und damit auch nicht produktiv eingesetzt werden sollte. Denn es hat Gründe weshalb die GH Version nicht im Installer ist. Mir gefällt es ebenso wenig, dass die Leute ständig Probleme haben. Aber effektiv funktioniert die Version 1 immer noch. Und wenn ich Zeit habe die Probleme in der 2er Version anzugehen, dann wird auch diese irgendwann im Installer sein.

**Comment by alxndr-w** [comment]
> Denn es hat Gründe weshalb die GH Version nicht im Installer ist. 

Ein perfekter Zeitpunkt, die für einige ominösen Gründe nochmal transparent zu machen.

**Comment by tbaddade** [comment]
> ominösen Gründe

= zweifelhaft

Ich weiß du machst das gern, aber ich habe auf solche Sticheleien keine Lust.

**Comment by IngoWinter** [comment]
Version 1 funktioniert ganz hervorragend 👍 
Im Slack wird immer v2 als problemlos produktiv einsetzbar empfohlen. Dann weiss ich nun, dass dem nicht so ist und die Verwirrung von der featuregeilen Community kommt :)

**Comment by alxndr-w** [comment]
@tbaddade danke, dass du das ansprichst.

"ominös" bedeutet für mich, dass sie im Unklaren gehalten werden und nicht vorgebracht werden, sie sind unsichtbar.  

Hier zur Klärung, wie ich ominös meine:

![image](https://user-images.githubusercontent.com/3855487/109499995-f1c70580-7a95-11eb-91a5-c30ae195b147.png)

Weißt du, du könntest auch einfach sagen, was Sache ist. Warum so kompliziert?

**Comment by skerbis** [comment]
Och Leute. 
Es wird immer mal wieder V2 empfohlen, auch von @tbaddade. 
Wenn's noch nicht fit ist für die Welt, dann soll es so sein.

**Comment by IngoWinter** [comment]
Wieso "Och Leute"? Eine klare Ansage dazu vom Maintainer ist schon sinnvoll. Wenn jemand nicht zwingend irgendein Feature von der v2 braucht, sollte er v1 nehmen. Aktuell wird im Slack grundsätzlich v2 empfohlen, die anscheinend noch irgendwelche kritischen Bugs hat. Wenn ich im Slack Support für ein Addon mache, möchte ich zumindest die passende Version empfehlen können :)
