### ISSUE TITLE
title-tag Schema (Diskussion)

### ISSUE THREAD

**Issue by polarpixel** [tbaddade/redaxo_url#211]
Das URL-AddOn bietet ja die Möglichkeit, auch den Title-tag zu generieren mit
`$urlSeo->getTags()`
Das ist natürlich eine sehr komfortable Option.

Allerdings wird so nur der in URL hinterlegte Titel als title-tag ausgegeben, z.B.
`<title>Mein tolles Projekt</title>`

Um dem yrewrite-Schema zu folgen, wäre aber eher sowas hier sinnvoll:
`<title>Mein tolles Projekt / Projekte / Website</title>`

So etwas wäre aber nur mit einiger Mühe zu realisieren, z.B.
```
$urlSeo = new Url\Seo();
    \rex_extension::register('URL_SEO_TAGS', function(\rex_extension_point $ep) {
        $manager = Url\Url::resolveCurrent();
        if (!$manager) {
            return;
        }
        $tags = $ep->getSubject();
        $seo = new \rex_yrewrite_seo();
        $title = str_replace(["\n", "\r"], [' ', ''], rex_escape(strip_tags($manager->getSeoTitle().' / '.$seo->getTitle())));
        $tags['title'] = '<title>'.$title.'</title>';
        $ep->setSubject($tags);
    });
    echo $urlSeo->getTags().PHP_EOL;
```

Daher ist vielleicht eine Diskussion sinnvoll, wie man den title-tag am liebsten haben möchte?
@tbaddade @gharlan @dergel

**Comment by tbaddade** [comment]
Meine Antwort an Peter war zunächst:

> Ich sehe den `title` Tag eher als Titel der aktuellen Seite an und nicht als verkürzte Breadcrumb.

Und bat ihn dann das Issue zu öffnen, um andere Meinungen einzuholen.

**Comment by ynamite** [comment]
Bin da völlig bei Peter. Bisher (in URL1) hat das auch so funktioniert.
Wenn der Titel separat (ohne Tag drumrum) ausgegeben werden kann, dann ist das nicht so tragisch. Aber so wie's jetzt ist, macht das zu viele Probleme.

**Comment by skerbis** [comment]
Mir reicht die aktuelle Schreibweise: Titel aus URL-AddOn + Sitename ... Es sind z.T. schon sehr lange Titel (gerade bei News) Ich brauche da nicht noch extra Infos

**Comment by ynamite** [comment]
Hab Peter so verstanden, dass der Sitename fehlt. Ist dem nicht so?

**Comment by skerbis** [comment]
ups! Hab ne Seite mit url2 geschaut ... aber auch da reicht mir der Titel des Datensatzes.

**Comment by polarpixel** [comment]
Mir fehlt nicht nur der Titel, sondern auch die Kategorie und gegebenenfalls Unterkategorie. Oder zumindest die Option, sowas leicht und schnell tun zu können. ￼Denn es soll ja die URL wie bei einem Artikel abgebildet werden.￼

**Comment by ynamite** [comment]
@polarpixel da muss ich dir allerdings wiedersprechen, bei einem Artikel wird nicht der ganze Pfad/Brotkrümmel abgebildet, nur der aktuelle Artikel und Seitenname.

**Beispiel:**
Artikel-Pfad: Projekte -> Wohnbauten -> Wohnhaus Dübendorf
Seitenname: Yakamara

Ergibt den Titel: `Wohnhaus Dübendorf / Yakamara`

Das war imo schon immer so bei yrewrite. Falls bei dir der Titel so aussehen soll:
`Wohnhaus Dübendorf / Wohnbauten / Projekte / Yakamara`

Dann hast du zuvor etwas spezielles gemacht, damit das so ausgegeben wurde. Oder irre ich mich?

**Comment by polarpixel** [comment]
@ynamite Du hast recht.
Ich dachte, das war früher mal anders ... kann mich aber auch irren.

**Comment by skerbis** [comment]
Die Variante `Wohnhaus Dübendorf / Yakamara` würde mir als Option auch reichen. 
Die Variante nur mit dem Titel sollte aber bitte beibehalten werden. Google weiß schon um welche Seite es sich handelt.

**Comment by ynamite** [comment]
@skerbis ich finde es müsste umgekehrt sein, da yrewrite das auch so macht (und beie, auch URL, das bisher immer so gemacht hat; ausser ich irre mich, was durchaus sein kann). Sonst ist's irgendwie inkonsistent/unschön.

**Comment by alxndr-w** [comment]
Ein Textfeld zur Definition des Titelschemas, analog zu YRewrite, pro URL-Schema, könnte das nachhaltig lösen.

**Comment by ynamite** [comment]
Finde Alex' Vorschlag gut, damit wären wohl alle zufrieden.

**Comment by polarpixel** [comment]
Ich weiß jetzt wieder, warum ich das issue eröffnet hatte. Bei einem Projekt habe ich Interviews und CD Rezensionen, darunter dann die ganzen Bands und Musiker. Da erschien mir ein Titel sinnvoll wie Website/Interview/Apocalyptica. Und eben der andere dann Website/Rezension/Apocalyptica. Sollte ein Title Tag nicht unique sein￼￼? ￼

**Comment by tbaddade** [comment]
Aktuell kann man bei YRewrite das angeben

`%T=SEO-Title oder Artikelname, %SN=Servename`

Eine Variante wie die von Peter `Website/Interview/Apocalyptica` ist m.E. ohne eigenes Eingreifen nicht möglich.

Was man jetzt machen kann, dass Url ebenfalls das Seitentitel-Schema von yrewrite auswertet. Dabei wäre `%T` der Titel des Datensatzes und `%SN` weiterhin der Servename.

**Comment by alxndr-w** [comment]
Ein eigenes Eingabefeld wäre deswegen zielführender, weil man dann bspw. auch den YRewrite-Titel des Artikels beibehalten kann, also 
`URL-Datensatz-Titel / Artikel-Titel / Website-Titel` z.B. `Don't Look Up / Filme / Kino 3000`

**Comment by tbaddade** [comment]
> Ein eigenes Eingabefeld wäre deswegen zielführender, weil man dann bspw. auch den YRewrite-Titel des Artikels beibehalten kann, also

Dann müsste man sich wieder irgendwelche Kürzel ausdenken, um eben den Artikelnamen oder auch die Namen des kompletten Artikelpfades zu berücksichtigen. Und selbst dann vermute ich, dass irgendwelche Sonderwünsche später noch auftauchen.

Ich favorisiere eher eine Lösung dieser Art:

```php
$seo = new Seo();
$manager = Url::resolveCurrent();
if ($manager) {
    \rex_extension::register('URL_SEO_TAGS', function(\rex_extension_point $ep) use ($manager) {
        $tags = $ep->getSubject();
        $title = [];
        $article = rex_article::get($manager->getArticleId());
        if ($article) {
            $title[] = $article->getName();
        }
        if ('' !== rex::getServerName()) {
            $title[] = rex::getServerName();
        }
        if ($manager->getSeoTitle()) {
            $title[] = $manager->getSeoTitle();
        }
        if (count($title)) {
            $tags['title'] = sprintf('<title>%s</title>', rex_escape(implode(' / ', $title)));            
        }
        $ep->setSubject($tags);
    });
}
$tags = $seo->getTags();
```

Hier kann der Dev selbst bestimmen, was genau als Titel ausgegeben werden soll.

Wäre das für euch eine annehmbare Lösung?

**Comment by skerbis** [comment]
Finde ich gut. Sehr schön und variabel einsetzbar.

**Comment by alxndr-w** [comment]
Puh, mächtig viel Code. Ich verstehe den Ansatz. 

- Wenn hier aber mehrere Profile im Einsatz sind, wird das noch aufgeblähter, als über die GUI am Profil ein Eingabefeld auszufüllen und fertig.
- Wenn Mutlidomain, dann funktioniert der Ansatz mit `rex::getServerName()` nicht. Es wird die Angabe aus dem Profil benötigt, z.B. `%T | Meine 2. Domain`
- btw. die Reihenfolge stimmt nicht. Vom konkreten zum allgemeinen müsste es `Datensatz / Artikel / Domain-Titel` heißen. Bzw. `Datensatz %Trennzeichen% %Artikeltitel nach YRewrite-Definition%`

Wäre es nicht am sinnvollsten, beides zu haben? Wäre letzteres nicht auch das Standard-Vorgehen?

Und sorry, falls ich da zu hartnäckig bin. Ich wünsche mir einfach eine Konfiguration in den Profilen, bei denen ich als Entwickler das Profil einstelle und fertig bin.

**Comment by tbaddade** [comment]
> Wenn Mutlidomain, dann funktioniert der Ansatz mit rex::getServerName() nicht. 
> btw. die Reihenfolge stimmt nicht.

Das Beispiel zeigt, dass du es komplett selbst beeinflussen kannst. Egal welche Reihenfolge am Ende heraus kommen soll oder wo bzw. wie auch immer du den Titel haben magst.

Für mich ist das die flexibelste Variante, denn auch mit "ausfüllen und fertig" ist es eben nicht getan.

**Comment by polarpixel** [comment]
Ich finde den Vorschlag von Thomas gut. Letztlich ist es recht flexibel, flexibler jedenfalls eine GUI-Lösung.
Also für mich würde das passen so. :-)

**Comment by ynamite** [comment]
Ich finde Thomas' Vorschlag auch gut. Vielleicht wäre es sinnvoll, das obige Beispiel in der Anleitung zu erwähnen, falls nicht bereits geschehen (ergänzt mit Multidomain-Beispiel wäre natürlich perfekt)

**Comment by tbaddade** [comment]
> Vielleicht wäre es sinnvoll, das obige Beispiel in der Anleitung zu erwähnen ... (ergänzt mit Multidomain-Beispiel wäre natürlich perfekt)

https://github.com/tbaddade/redaxo_url/commit/419fe08daf875d130018148183598db29372d155
