### ISSUE TITLE
Whoops nachdem ein neuen Sprog Datensatz eingefügt wird

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#213]
**rex_sql_exception:** Unable to fetch row.
**File:** redaxo/src/core/lib/sql/sql.php
**Line:** 812

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                    | Line     |
| -------------------------------------------- | ------------------------------------------------------- | -------- |
| rex_sql->getRow                              | redaxo/src/core/lib/sql/sql.php                         | 787      |
| rex_sql->fetchValue                          | redaxo/src/core/lib/sql/sql.php                         | 734      |
| rex_sql->getValue                            | redaxo/src/addons/url/lib/Url/ExtensionPointManager.php | 139      |
| Url\ExtensionPointManager->normalize         | redaxo/src/addons/url/lib/Url/ExtensionPointManager.php | 47       |
| Url\ExtensionPointManager->__construct       | redaxo/src/addons/url/boot.php                          | 39       |
| rex_package->{closure}                       | redaxo/src/core/lib/extension.php                       | 51       |
| rex_extension::{closure}                     | redaxo/src/core/lib/util/timer.php                      | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/extension.php                       | 62       |
| rex_extension::registerPoint                 | redaxo/src/core/lib/form/form.php                       | 389      |
| rex_form->save                               | redaxo/src/core/lib/form/form_base.php                  | 1157     |
| rex_form_base->get                           | redaxo/src/addons/sprog/pages/wildcard.clang_switch.php | 169      |
| include                                      | redaxo/src/core/lib/packages/package.php                | 280      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                   | 482      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                      | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                   | 483      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                   | 432      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/sprog/pages/index.php                 | 17       |
| include                                      | redaxo/src/core/lib/packages/package.php                | 280      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                   | 482      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                      | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                   | 483      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                   | 415      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                             | 233      |
| require                                      | redaxo/src/core/boot.php                                | 141      |
| require                                      | redaxo/index.php                                        | 9        |

</details>
<details>
<summary>System report (REDAXO 5.12.0, PHP 7.4.14, MySQL 5.7.28)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.12.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.14     |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.28 |
| Character set | utf8         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/86.0 |
|      Protocol | HTTP/2.0     |
|         HTTPS | yes          |

| Packages                                         |             |
| -----------------------------------------------: | :---------- |
|                                     accessdenied | 1.0.6       |
|                                         be_style | 2.12.0      |
|                              be_style/customizer | 2.12.0      |
|                                  be_style/redaxo | 2.12.0      |
|                                  consent_manager | 2.0.1       |
|                                          cronjob | 2.8.0       |
|                                      d2u_address | 1.1.2       |
|                                       d2u_helper | 1.8.2       |
|                    d2u_helper/translation_helper | 1.8.2       |
|                                      d2u_history | 1.0.1       |
|                                         d2u_jobs | 1.2.0       |
|                           d2u_jobs/hr4you_import | 1.2.0       |
|                                      d2u_linkbox | 1.2.4       |
|                                    d2u_machinery | 1.3.4       |
|                   d2u_machinery/industry_sectors | 1.3.4       |
|         d2u_machinery/machine_features_extension | 1.3.4       |
| d2u_machinery/machine_steel_processing_extension | 1.3.4       |
|                      d2u_machinery/used_machines | 1.3.4       |
|                                         d2u_news | 1.1.3       |
|                                   d2u_news/fairs | 1.1.3       |
|                                      d2u_partner | 1.0         |
|                                   d2u_references | 1.0.8       |
|                                        d2u_staff | 1.0.3       |
|                                       d2u_videos | 1.0.9       |
|                                  emailobfuscator | 3.0.0       |
|                                          install | 2.9.0       |
|                                    media_manager | 2.11.0      |
|                        media_manager_autorewrite | 2.0.0       |
|                                        mediapool | 2.10.0      |
|                                         metainfo | 2.8.0       |
|                                  multinewsletter | 3.2.7       |
|                                        phpmailer | 2.10.0      |
|                                        search_it | 6.7.3       |
|                           search_it/autocomplete | 6.7.3       |
|                          search_it/documentation | 6.7.3       |
|                              search_it/plaintext | 6.7.3       |
|                                  search_it/stats | 6.7.3       |
|                                            sprog | 1.2.0       |
|                                        structure | 2.12.0      |
|                                structure/content | 2.12.0      |
|                                         tinymce4 | 1.2.1       |
|                                         uploader | 2.2.2       |
|                                              url | 2.0.0-beta3 |
|                                            users | 2.8.0       |
|                                             ycom | 4.0.3       |
|                                        ycom/auth | 4.0.3       |
|                                        ycom/docs | 4.0.3       |
|                                       ycom/group | 4.0.3       |
|                                  ycom/media_auth | 4.0.3       |
|                                            yform | 3.4.1       |
|                                       yform/docs | 3.3.1       |
|                                      yform/email | 3.4.1       |
|                                    yform/manager | 3.4.1       |
|                            yform_spam_protection | 1.0.6       |
|                                         yrewrite | 2.7         |
|                                  yrewrite_scheme | 3.3.0       |

</details>

**Comment by tbaddade** [comment]
@TobiasKrais Könntest du den Platzhalter und dessen Ersetzung hier, oder wenn zu privat im Slack, notieren?

**Comment by TobiasKrais** [comment]
Welchen Platzhalter meinst du? Den, den ich hinzufüge? Das spielt keine Rolle wie ich ihn nenne oder welche Ersetzung ich einfüge. Nimm einfach "test" und "test". Hier die Liste der sonstigen Platzhalter, die in meiner Ersetzungstabelle sind:
```
INSERT INTO `rex_sprog_wildcard` (`pid`, `id`, `clang_id`, `wildcard`, `replace`, `createuser`, `updateuser`, `createdate`, `updatedate`, `revision`) VALUES
(1, 1, 1, 'd2u_jobs_announcement', 'Zur Ausschreibung', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(2, 2, 1, 'd2u_jobs_footer', 'Bitte senden Sie uns Ihre kompletten Bewerbungsunterlagen mit dem frühestmöglichen Eintrittstermin und Ihrer Gehaltvorstellung per E-Mail mit dem Stichwort „Karriere“ im Betreff an:', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(3, 3, 1, 'd2u_jobs_phone', 'Tel.', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(4, 4, 1, 'd2u_jobs_questions', 'Wenn Sie Fragen zur ausgeschriebenen Stelle haben, wenden Sie sich bitte an:', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(5, 5, 1, 'd2u_jobs_reference_number', 'Referenznummer', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(6, 6, 1, 'd2u_jobs_region', 'Region', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(7, 7, 1, 'd2u_jobs_vacancies', 'Stellenangebote', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(16, 1, 2, 'd2u_jobs_announcement', 'Complete announcement', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(17, 2, 2, 'd2u_jobs_footer', 'Please send us your complete application documents with the possible starting date and your salary expectations via email to:', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(18, 3, 2, 'd2u_jobs_phone', 'Phone', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(19, 4, 2, 'd2u_jobs_questions', 'If you have questions regarding this position, please contact:', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(20, 5, 2, 'd2u_jobs_reference_number', 'Reference number', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(21, 6, 2, 'd2u_jobs_region', 'Region', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(22, 7, 2, 'd2u_jobs_vacancies', 'Vacancies', 'username', 'username', '2020-06-19 15:23:54', '2020-10-15 11:56:32', 0),
(73, 8, 1, 'd2u_helper_module_11_city', 'Ort', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(74, 8, 2, 'd2u_helper_module_11_city', 'City', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(75, 9, 1, 'd2u_helper_module_11_contact_request', 'Kontaktanfrage', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(76, 9, 2, 'd2u_helper_module_11_contact_request', 'Contact request', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(77, 10, 1, 'd2u_helper_module_11_contact_request_intro', 'In das Anfrage-Formular wurden folgende Werte eingetragen', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(78, 10, 2, 'd2u_helper_module_11_contact_request_intro', 'The following values were entered in the request form:', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(79, 11, 1, 'd2u_helper_module_11_email', 'E-Mail Adresse', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(80, 11, 2, 'd2u_helper_module_11_email', 'E-mail address', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(81, 12, 1, 'd2u_helper_module_11_message', 'Nachricht', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(82, 12, 2, 'd2u_helper_module_11_message', 'Message', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(83, 13, 1, 'd2u_helper_module_11_name', 'Name', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(84, 13, 2, 'd2u_helper_module_11_name', 'Name', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(85, 14, 1, 'd2u_helper_module_11_phone', 'Telefon', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(86, 14, 2, 'd2u_helper_module_11_phone', 'Phone', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(87, 15, 1, 'd2u_helper_module_11_privacy_policy', 'Ich akzeptiere die <a href=\"+++LINK_PRIVACY_POLICY+++\" target=\"_blank\">Datenschutzerklärung</a>. Meine Daten werden nicht an Dritte weitergegeben. Ich habe das Recht auf Löschung meiner Daten. Diese kann ich jederzeit unter den im <a href=\"+++LINK_IMPRESS+++\" target=\"_blank\">Impressum</a> angegebenen Kontaktdaten verlangen.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(88, 15, 2, 'd2u_helper_module_11_privacy_policy', 'I accept the <a href=\"+++LINK_PRIVACY_POLICY+++\" target=\"_blank\">Privacy Policy</a>. My data will not be disclosed to third parties. I know about the right of deletion of my data. I can request deletion at any time from the contact details provided in the <a href=\"+++LINK_IMPRESS+++\" target=\"_blank\">impress</a>.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(89, 16, 1, 'd2u_helper_module_11_required', 'Pflichtfelder', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(90, 16, 2, 'd2u_helper_module_11_required', 'Required', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(91, 17, 1, 'd2u_helper_module_11_send', 'Abschicken', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(92, 17, 2, 'd2u_helper_module_11_send', 'Send', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(93, 18, 1, 'd2u_helper_module_11_street', 'Straße', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(94, 18, 2, 'd2u_helper_module_11_street', 'Street', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(95, 19, 1, 'd2u_helper_module_11_thanks', 'Danke für Ihr Nachricht. Wir werden uns schnellst möglich um Ihr Anliegen kümmern.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(96, 19, 2, 'd2u_helper_module_11_thanks', 'Thank you for request. we will answer as soon as possible.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(97, 20, 1, 'd2u_helper_module_11_validate_email', 'Bitte geben Sie eine gültige E-Mailadresse ein.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(98, 20, 2, 'd2u_helper_module_11_validate_email', 'Please enter a valid email address.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(99, 21, 1, 'd2u_helper_module_11_validate_message', 'Bitte geben Sie eine Nachricht ein.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(100, 21, 2, 'd2u_helper_module_11_validate_message', 'Please enter a message.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(101, 22, 1, 'd2u_helper_module_11_validate_name', 'Um Sie korrekt ansprechen zu können, geben Sie bitte Ihren vollständigen Namen an.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(102, 22, 2, 'd2u_helper_module_11_validate_name', 'Please enter your full name.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(103, 23, 1, 'd2u_helper_module_11_validate_phone', 'Bitte geben Sie Ihre Telefonnummer an.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(104, 23, 2, 'd2u_helper_module_11_validate_phone', 'Please enter your phone number.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(105, 24, 1, 'd2u_helper_module_11_validate_privacy_policy', 'Der Datenschutzerklärung muss zugestimmt werden.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(106, 24, 2, 'd2u_helper_module_11_validate_privacy_policy', 'It\'s necessary to accept the privacy policy.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(107, 25, 1, 'd2u_helper_module_11_validate_spambots', 'Spamverdacht: Sie haben das Formular so schnell ausgefüllt, wie es nur ein Spambot tun kann. Bitte lassen Sie sich beim ausfüllen der Felder etwas mehr Zeit.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(108, 25, 2, 'd2u_helper_module_11_validate_spambots', 'Too fast - it seems you are a spambot. Please take your time to fill out all all fields or call us.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(109, 26, 1, 'd2u_helper_module_11_validate_spam_detected', 'Ihre Anfrage wurde als Spam eingestuft und verworfen. Sie waren entweder zu schnell oder es wurden zu viele Anfragen von Ihrer IP-Adresse registriert. Bitte versuchen Sie es später oder wenden Sie sich persönlich an uns.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(110, 26, 2, 'd2u_helper_module_11_validate_spam_detected', 'Your request was recognized as spam and deleted. Please try again in a few minutes or contact us personally.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(111, 27, 1, 'd2u_helper_module_11_validate_title', 'Fehler beim Senden:', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(112, 27, 2, 'd2u_helper_module_11_validate_title', 'Failure sending message:', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(113, 28, 1, 'd2u_helper_module_11_zip', 'Postleitzahl', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(114, 28, 2, 'd2u_helper_module_11_zip', 'ZIP Code', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(115, 29, 1, 'd2u_helper_module_14_enter_search_term', 'Suchbegriff eingeben', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(116, 29, 2, 'd2u_helper_module_14_enter_search_term', 'Enter a search term', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(117, 30, 1, 'd2u_helper_module_14_search_results', 'Suchergebnisse', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(118, 30, 2, 'd2u_helper_module_14_search_results', 'Search results', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(119, 31, 1, 'd2u_helper_module_14_search_results_none', 'Es wurden keine Suchergebnisse gefunden.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(120, 31, 2, 'd2u_helper_module_14_search_results_none', 'No search results found.', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(121, 32, 1, 'd2u_helper_module_14_search_similarity', 'Ähnliche Suche mit Treffern', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(122, 32, 2, 'd2u_helper_module_14_search_similarity', 'Similar search with hits', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(123, 33, 1, 'd2u_helper_module_14_search_template_address', 'Adresse', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(124, 33, 2, 'd2u_helper_module_14_search_template_address', 'Address', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(125, 34, 1, 'd2u_helper_module_14_search_template_ceo', 'Geschäftsführung', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(126, 34, 2, 'd2u_helper_module_14_search_template_ceo', 'Managing director', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(127, 35, 1, 'd2u_helper_module_14_search_template_contact', 'Kontakt', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(128, 35, 2, 'd2u_helper_module_14_search_template_contact', 'Contact', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(129, 36, 1, 'd2u_helper_module_14_search_template_links', 'Links', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(130, 36, 2, 'd2u_helper_module_14_search_template_links', 'Links', 'username', 'username', '2020-09-21 16:12:02', '2021-01-16 20:53:52', 0),
(131, 37, 1, 'd2u_helper_module_14_validate_spam_detected', 'Ihre Anfrage wurde als Spam eingestuft und verworfen. Sie waren entweder zu schnell oder es wurden zu viele Anfragen von Ihrer IP-Adresse registriert. Bitte lassen Sie sich beim Ausfüllen des Formulars ein paar Sekunden Zeit oder versuchen Sie es später erneut.', 'username', 'username', '2020-10-25 20:54:24', '2021-01-16 20:53:52', 0),
(132, 37, 2, 'd2u_helper_module_14_validate_spam_detected', 'Your request was recognized as spam and rejected. You were either too fast or there were too many requests from your IP address. Please take a few seconds to fill out the form or try again later.', 'username', 'username', '2020-10-25 20:54:24', '2021-01-16 20:53:52', 0),
(133, 38, 1, 'd2u_helper_module_06_gdpr_hint', 'Datenschutz Hinweis: wenn Sie dieses Video abspielen lassen, wird es von Youtube abgerufen. Sie anerkennen damit die <a href=\"https://policies.google.com/privacy\" target=\"_blank\">Google Nutzungsbedingungen und Datenschutzerklärung</a>.', 'username', 'username', '2020-12-01 14:41:05', '2021-01-16 20:53:52', 0),
(134, 38, 2, 'd2u_helper_module_06_gdpr_hint', 'Data protection notice: if you let this video play, it will be retrieved from Youtube. By doing so, you acknowledge the <a href=\"https://policies.google.com/privacy\" target=\"_blank\"> Google terms of use and data protection declaration</a>.', 'username', 'username', '2020-12-01 14:41:05', '2021-01-16 20:53:52', 0);```

**Comment by tbaddade** [comment]
@TobiasKrais Kannst du erklären was gegebenen sein muss, damit der Fehler passiert. Ich kann Platzhalter erstellen ohne das irgendein Fehler kommt.

**Comment by alxndr-w** [comment]
@TobiasKrais ich empfehle, in YForm die Feldaktualisierung an jeder Datenbank-Tabelle auszuführen und dann zu schauen, ob das Problem noch besteht.

Vorher natürlich ein Backup machen.

**Comment by TobiasKrais** [comment]
@tbaddade Gute Frage: der Fehler kommt bei mir nur bei mehrsprachigen Seiten. Kannst du es dann verifizieren?

@alxndr-w Ich habe keine YForm Tabellen. Das sollte nichts damit zu tun haben.

**Comment by tbaddade** [comment]
> der Fehler kommt bei mir nur bei mehrsprachigen Seiten. Kannst du es dann verifizieren?

Nein. Hier ist auch alles mehrsprachig. Es scheint ja dasselbe Problem wie beim anlegen von Metainfofelder zu sein. Aber auch da bekomme ich es nicht nachgestellt.

**Comment by TobiasKrais** [comment]
Seltsam. Ich hab das auf allen meinen Seiten. Soll ich dir einen Zugang zu meiner Spielwiese geben?

**Comment by tbaddade** [comment]
> Soll ich dir einen Zugang zu meiner Spielwiese geben?

Gern via Slack.

**Comment by tbaddade** [comment]
Duplicate https://github.com/tbaddade/redaxo_url/issues/192 - Fixed in https://github.com/tbaddade/redaxo_url/commit/aa0019bde1a5ccc78a4cc46fb484fdc177f7ae00

**Comment by TobiasKrais** [comment]
Ja, Bugfix wirkt. Danke!
