### ISSUE TITLE
Whoops wenn zweite DB in core/config.yml existiert, aber nicht verunden werden kann

### ISSUE THREAD

**Issue by ynamite** [tbaddade/redaxo_url#214]
Bin unsicher ob das ein Bug ist. Wir haben zwei DBs in core/config.yml erfasst, eine für Dev und eine für Live. 
Wenn man in URL-Addon einen Eintrag bearbeiten möchte, gibt's eine Exception wenn der zweite DB Eintrag existiert, aber keine Verbindung darüber aufgebaut werden kann (ist in unserem Fall so gewollt).
Entfernt man den zweiten Eintrag, klappt's wieder.

**Request-Uri:** /redaxo/index.php?page=url/generate&func=edit&id=5
**Request-Method:** GET

**rex_sql_could_not_connect_exception:** Could not connect to database
**File:** redaxo/src/core/lib/sql/sql.php
**Line:** 151

<details>
<summary>Stacktrace</summary>

| Function | File | Line |
| -------------------------------------------- | ---------------------------------------- | -------- |
| rex_sql->selectDB | redaxo/src/core/lib/sql/sql.php | 106 |
| rex_sql->__construct | redaxo/src/core/lib/sql/sql.php | 1842 |
| rex_sql::factory | redaxo/src/core/lib/sql/sql.php | 1647 |
| rex_sql::showTables | redaxo/src/addons/url/pages/generate.php | 278 |
| include | redaxo/src/core/lib/packages/package.php | 280 |
| rex_package->includeFile | redaxo/src/core/lib/be/controller.php | 482 |
| rex_be_controller::{closure} | redaxo/src/core/lib/util/timer.php | 63 |
| rex_timer::measure | redaxo/src/core/lib/be/controller.php | 483 |
| rex_be_controller::includePath | redaxo/src/core/lib/be/controller.php | 432 |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/url/pages/index.php | 17 |
| include | redaxo/src/core/lib/packages/package.php | 280 |
| rex_package->includeFile | redaxo/src/core/lib/be/controller.php | 482 |
| rex_be_controller::{closure} | redaxo/src/core/lib/util/timer.php | 63 |
| rex_timer::measure | redaxo/src/core/lib/be/controller.php | 483 |
| rex_be_controller::includePath | redaxo/src/core/lib/be/controller.php | 415 |
| rex_be_controller::includeCurrentPage | redaxo/src/core/backend.php | 233 |
| require | redaxo/src/core/boot.php | 141 |
| require | redaxo/index.php | 10 |

</details>
<details>
<summary>System report (REDAXO 5.12.0, PHP 7.4.16, MariaDB 10.3.28)</summary>

| REDAXO | |
| ------------: | :--------- |
| Version | 5.12.0 |

| PHP | |
| ------------: | :--------- |
| Version | 7.4.16 |
| OPcache | yes |
| Xdebug | no |

| Database | |
| ------------: | :-------------- |
| Version | MariaDB 10.3.28 |
| Character set | utf8 |

| Database 2 | |
| ------------: | :---------------------------- |
| Warning | Could not connect to database |

| Server | |
| ------------: | :--------- |
| OS | Linux |
| SAPI | fpm-fcgi |
| Webserver | Apache |

| Request | |
| ------------: | :----------- |
| Browser | Firefox/87.0 |
| Protocol | HTTP/1.0 |
| HTTPS | yes |

| Packages | |
| --------------------------------: | :--------- |
| adminer | 1.9.0 |
| article_presets | 1.1.0 |
| backup | 2.7.0 |
| be_password | 2.0.0 |
| be_style | 2.12.0 |
| be_style/customizer | 2.12.0 |
| be_style/redaxo | 2.12.0 |
| be_tools | 1.5.4 |
| bloecks | 3.0.2 |
| bloecks/cutncopy | 3.0.2 |
| bloecks/dragndrop | 3.0.2 |
| bloecks/status | 3.0.2 |
| clear_content | 1.1.1 |
| cropper | 1.2.0 |
| developer | 3.9.0 |
| emailobfuscator | 3.0.0 |
| focuspoint | 3.0.2 |
| hyphenator | 1.1.7 |
| install | 2.9.0 |
| massif | 1.0.0 |
| massif_minify | 1.3.0 |
| massif_settings | 1.0.0 |
| mblock | 3.1.0 |
| media_manager | 2.11.0 |
| mediapool | 2.10.0 |
| metainfo | 2.8.0 |
| mform | 6.0.5 |
| mform/docs | 1.1 |
| phpmailer | 2.10.0 |
| project | dev |
| quick_navigation | 5.0.0 |
| sprog | 1.2.0 |
| structure | 2.12.0 |
| structure/content | 2.12.0 |
| structure/history | 2.12.0 |
| structure_tweaks | 1.3.2 |
| tinymce4 | 1.2.1 |
| ui_tools | 1.0.0 |
| ui_tools/bootstrap-datetimepicker | 4.17.47 |
| ui_tools/jquery-minicolors | 2.2.7 |
| ui_tools/selectize | 0.2.0 |
| uploader | 2.2.2 |
| url | 1.0.1 |
| useragent | 2.3.0 |
| users | 2.8.0 |
| ycom | 4.0.3 |
| ycom/auth | 4.0.3 |
| ycom/docs | 4.0.3 |
| ycom/group | 4.0.3 |
| yform | 3.4.1 |
| yform/email | 3.4.1 |
| yform/manager | 3.4.1 |
| yform/tools | 3.4.1 |
| yform_usability | 1.4 |
| yrewrite | 2.7 |

</details>

**Comment by tbaddade** [comment]
Das AddOn geht derzeit davon aus, dass die Verbindung klappt.
https://github.com/tbaddade/redaxo_url/blob/master/lib/Url/Database.php#L22-L32

Irgendetwas klappte nicht mit dem Check der Verbindung. Das muss ich mir noch mal ansehen.

Andererseits ist es aktuell so, dass keine zwei Datenbanken genutzt werden können. Man kann zwar ein Profil anlegen, es werden jedoch keine Urls generiert. Hier ist das Problem, dass das Url-Addon Yorm für den SQL-Query-Aufbau nutzt. Yorm kann aber keine zweite DB-Verbindung aufbauen. Das wird scheinbar auch noch so bleiben, sodass ich hier nochmals umbauen muss.

**Comment by ynamite** [comment]
Für uns ist das Issue nicht mega relevant. Wir hatten mehr aus Bequemlichkeit beide Verbindungen hinterlegt, damit wir schnell von Dev auf Live switchen können (einfach IDs der Verbindungen austauschen). Nun haben wir die zweite Verbindung aber einfach auskommentiert, so geht's wieder :) 

Wollte es einfach kurz melden, weil ich dazu noch kein Issue gefunden hatte.

**Comment by ynamite** [comment]
P.S. für's erste würde es ev. schon reichen, wenn die Felder host, password usw. einzeln geprüft werden würden.
Solange da irgendetwas steht, gibt's nen Whoops
