### ISSUE TITLE
Unterscheidliche Ausgabe in Cronjob

### ISSUE THREAD

**Issue by Sysix** [tbaddade/redaxo_url#215]
Hallo,

wenn ich `rex_getUrl` verwende bekomme ich zwei unterschiedliche Ergebnisse via den Cronjob-Manager:

Mein Code:

```php
        var_dump(rex_getUrl($this->addon->getConfig('job_article'), null, [
            'id' => $job->id
        ]));
```

**Ausgabe über `bin/redaxo cronjob:run`**:
`string(50) "://localhost/job/xxxxxxxxxxxxx/"`

**Ausgabe über "Cronjob manuell ausführen"**:
`string(38) "/job/xxxxxxxxxxxxx/"`

Versionen:
Redaxo: 5.12.0
PHP: 7.4.16
YRewrite: 2.7
URL Addon: 1.0.1
Cronjob Addon: 2.8.0

**Comment by tbaddade** [comment]
Probiere mal bitte ohne die Artikelnummer und nur über den Namespace

```
 var_dump(rex_getUrl('', '', ['job-id' => $job->id]));
```

**Comment by Sysix** [comment]
Gleicher Fehler.

Bekomme im Backend:
`/job/xxxxx/`

in der Console:
`http://localhost/?job-id=xxxxx`

**Comment by Sysix** [comment]
Mit der Version 2.0.0-dev siehst das Ergebnis so aus:

Backend:
`/job/xxxx/`

In der Console:
`https://localhost/job/xxxx/`

Das passt schon fast :)

**Comment by tbaddade** [comment]
Danke für dein Testen

An der 1er Version werde ich nichts mehr machen. 
Bei der 2er vermute ich eher yrewrite. Das Url Addon erhält die Urls zu den Artikeln (hier Jobs) komplett von yrewrite. Falls ich hier falsch liege, gern das Issue wieder eröffnen.

**Comment by alxndr-w** [comment]
Es kommt darauf an, unter welcher Domain (YRewrite) der Cronjob läuft.

Bei manuell ausführen bist du vermutlich über eine bestimmte Domain angemeldet, daher dort die relative URL. 

Meldest du dich über eine andere Domain an, ändert sich das Verhalten
