### ISSUE TITLE
getSeoImage() … Bitte bitte mediamanager-Typ angeben können. 

### ISSUE THREAD

**Issue by skerbis** [tbaddade/redaxo_url#221]

**Comment by tbaddade** [comment]
Hast du mal probiert ,ob es via EP `MEDIA_URL_REWRITE ` klappt?

Intern wird die Methode `getUrl()` von `rex_media` aufgerufen.

**Comment by skerbis** [comment]
Wüsste jetzt leider nicht in welchem Context ich den EP dann aufrufen müsste ohne alle Urls umzuschreiben.

**Comment by tbaddade** [comment]
Reicht wirklich die Auswahl eines MediaManagerTypen? Wie sollte die Url zum Schluss aussehen? Was würdest du hier erwarten?

```
/images/media-type/filename.jpg
/images/media-type/400/filename.jpg
/media/media-type/filename.jpg
```

Wie verwendest du es in der allgemeinen Sitemap von YRewrite?

**Comment by skerbis** [comment]
In der Sitemap lasse ich es weg. Sehe da keinen Nutzen. Denke aber auch da würde ein gemeinsamer Mediamangertyp reichen. Beim Seo-Image also für og::image etc. reicht eigentlich 1 Mediamanagertyp aus meiner Sicht aus, das den kleinsten gemeinsamen Nenner für Facebook, Twitter und die anderen bilden kann. 
Das Hauptproblem sind dabei einfach nur viel zu große Original-Bilder.

**Comment by tbaddade** [comment]
Ja, aber wie sollen die Urls zum Schluss aussehen? Wir haben zum Teil solche Urls für Bilder:

```
/images/16by9/400/filename.jpg
/images/16by9/800/filename.jpg
/images/16by9/1600/filename.jpg
```

Man könnte wie beim `<title>` so lösen:

```
$seo = new Seo();
$manager = Url::resolveCurrent();
if ($manager) {
    \rex_extension::register('URL_SEO_TAGS', function(\rex_extension_point $ep) use ($manager) {
        $tags = $ep->getSubject();

        $tags['image'] = str_replace('/media/', '/images/social/', $tags['image']);
        $tags['og:image'] = str_replace('/media/', '/images/social/', $tags['og:image']);
        $tags['twitter:image'] = str_replace('/media/', '/images/social/', $tags['twitter:image']);
        unset($tags['og:image:width'], $tags['og:image:height']);

        $ep->setSubject($tags);
    });
}
$tags = $seo->getTags();
```

Oder man gibt ggf. ein Callback an, der dann für das Generieren der Urls zuständig ist. Wobei man dann auch wieder gleich einen ExtensionPoint registrieren könnte.

**Comment by skerbis** [comment]
ah ok auf die Art und Weise könnte man ja doch je Image eine eigenen Typ definieren. 
Finde ich gut. Settings dafür kann man sich dann auch selbst basteln. 
Dann denke ich macht es Sinn es so zu handhaben wie du es hier beschrieben hast. Danke.
