### ISSUE TITLE
Wunsch: Date-Abfragen bei Einschränkungen ermöglichen

### ISSUE THREAD

**Issue by skerbis** [tbaddade/redaxo_url#222]
Das würde einiges gerade bei News erleichtern. 

<img width="1342" alt="Bildschirmfoto 2021-07-28 um 09 20 01" src="https://user-images.githubusercontent.com/791247/127280959-7c6ba279-61de-4c23-a715-4fbbc2cecb81.png">

**Comment by alxndr-w** [comment]
@skerbis eine View wäre dafür ein geeigneter Workaround

**Comment by skerbis** [comment]
ja tut es

**Comment by tbaddade** [comment]
@skerbis Für News und auch für deinen Abfrage wäre das hier interessant:

https://github.com/tbaddade/redaxo_url#url_profile_restriction
