### ISSUE TITLE
JSON-LD / Google-Search-Box: Problem mit URL-Parser

### ISSUE THREAD

**Issue by skerbis** [tbaddade/redaxo_url#226]
Folgender durch Google vorgeschlagener Code sorgt für ein Whooops durch den URL-Parser.
Kann man man das irgendwie umgehen?

```
<script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "WebSite",
      "url": "https://www.example.com/",
      "potentialAction": {
        "@type": "SearchAction",
        "target": {
          "@type": "EntryPoint",
          "urlTemplate": "https://query.example.com/search?q={search_term_string}"
        },
        "query-input": "required name=search_term_string"
      }
    }
    </script>
```

**Comment by tbaddade** [comment]
Wo fügst du den Code ein bzw. wie kann man das testen? Wie sieht der Stacktrace aus?

**Comment by skerbis** [comment]
Es wird im Head der Website eingesetzt. Ich habe es wieder rausgenommen.
Ich kann nur im Log sehen dass es gewhoopst hatte.   

Ich setze es wieder ein und prüfe ob ich im Serverlog dann was finde.
