### ISSUE TITLE
generierte URLs ohne domain

### ISSUE THREAD

**Issue by chrisrex** [tbaddade/redaxo_url#232]
bei mir werden die URLs immer mit domain generiert. Zu Beginn stehen zusätzlich zwei Slashs.
Also: **//www.meinedomain.de**/schoene_url/
Wie kann ich das ohne diesen Vorspann generieren lassen?

**Comment by alxndr-w** [comment]
Gibt es Besonderheiten in dieser Installation? Wurde REDAXO in einem Unterverzeichnis installiert, was wurde als Domain in YRewrite eingetragen?

**Comment by chrisrex** [comment]
Redaxo befindet sich in einem Unterverzeichnis. Es existiert eine Subdomain.
In YRewrite steht im Feld Domain: sub.meinedomain.de
Im addon url sehen alle url dann so aus: //sub.meinedomain.de/schoene_url

**Comment by alxndr-w** [comment]
Aus den Domain-Einstellungen bei YRewrite:

> Läuft REDAXO in einem Unterordner, muss dieser mit notiert werden. Beispiel: <code>http://domain.de/unterordner/</code>

**Comment by chrisrex** [comment]
Danke dir.
Jetzt sehen alle urls im url addon so aus
//www.meinedomain.de/sub/schoener_url/
Cache habe ich gelöscht
httaccess neu erzeugt
Im Grunde soll ja nur schoener_url drinstehen

**Comment by alxndr-w** [comment]
- Ist es eine Multidomain-Installation?
- benutzt du versehentlich den Base-Tag im Template?
- Kannst du die Domain auch mit Protokoll anlegen? Und schauen, ob der Fehler weiter existiert?
- Ist der Mountpoint korrekt?
- Liegt der URL-Artikel innerhalb oder unterhalb der Mountpoint-Ebene?

**Comment by chrisrex** [comment]
es ist keine Multidomain-Installation 
es ist kein Base-Tag vorhanden 
Mountpoint ist nicht eingetragen 
Die Seiten werden zwar alle gefunden. Aber vielleicht ist es auch nur ein Schönheitsfehler, wenn die url mit domain in der url addon drinsteht? Oder gehört das so?

**Comment by alxndr-w** [comment]
Trag' mal bitte einen Mountpoint ein. Ich versuche einfach rauszufinden, was unterschiedlich ist zu meinem Setup, den das Problem hatte ich noch nie.

**Comment by alxndr-w** [comment]
Also fürs Protokoll: die Doppelslashs sind da, weil das so gehört, du hast ja bei der Domain in YRewrite kein Protokoll angegeben.

Warum su die Domain mit www. bekommst obwohl es eine Subdomain und ein anderes Verzeichnis hast, ist mir schleierhaft.

**Comment by chrisrex** [comment]
ich habe in den Mountpoint etwas eingetragen. Keine Änderungen,
Ich könnte aber auch mit string replace den vorderen Teil abzwacken

**Comment by tbaddade** [comment]
@chrisrex 

1. Welche Version des AddOns verwendest du?

 > Warum die Domain mit www. bekommst obwohl es eine Subdomain und ein anderes Verzeichnis ist, ist mir schleierhaft.

2. Ist das tatsächlich so oder beschreibst du hier etwas anderes als in deiner Instanz vorhanden ist?

---

@alxndr-w Danke für die Moderation

**Comment by chrisrex** [comment]
Ich nutze das url addon 2.0.0-beta3
Ich habe in YRewrite nun wieder die Subdomain ohne Unterordner eingetragen.
Jetzt tut es merkwürdigerweise, wie es soll.
Ich fasse jetzt am besten nichts an.
Danke für die Geduld.

**Comment by alxndr-w** [comment]
Hey @chrisrex,

merkwürdig. Aber gut, wenn es jetzt so ist wie es soll.

@tbaddade gerne.
