### ISSUE TITLE
Bei Benutzung von yrewrite_scheme funktioniert Url::resolveCurrent() nicht

### ISSUE THREAD

**Issue by danspringer** [tbaddade/redaxo_url#235]
Wenn man YRewrite Scheme nutzt und als Endung **.html** wählt, klappt `Url::resolveCurrent()` nicht mehr und liefert für 
`dump( Url::resolveCurrent() )` dann `null`
Wenn man die Endung in YRewrite-Scheme deaktiviert, greift es wieder.

Rex 5.13
URL 2.0.0-dev
PHP 8

**Comment by skerbis** [comment]
Same as: https://github.com/tbaddade/redaxo_url/issues/196

**Comment by tbaddade** [comment]
Kann ich nicht nachvollziehen. Wobei ich nicht `yrewrite_scheme` verwendet habe sondern ein eigenes Scheme welches das Suffix setzt.


**Scheme**
```
<?php
namespace Project;

class Scheme extends \rex_yrewrite_scheme
{
    protected $suffix = '.html';
}
```


**boot.php des Project AddOns**
```
use Project\Scheme;

// register a custom yrewrite scheme
rex_yrewrite::setScheme(new Scheme());
```

Danach wurden alle Urls neu generiert und die Url konnte in der Modulausgabe aufgelöst werden

```
$manager = Url::resolveCurrent();
dump($manager);
```

**Comment by tyrant88** [comment]
Ich habe mal yrewrite_scheme deaktiviert und ein eigenes scheme angelegt im Project AddOn (so wie du es hier beschreibst) und auch dann wird bei mir die URL nicht aufgelöst.

Dumpe doch mal vor der IF Abfrage in der Zeile https://github.com/tbaddade/redaxo_url/pull/236/files#diff-a8dd6dee93c23ca05f793115aaffd86223936460bdabb7d0682994fe54c76d85L278
die beiden Variablen, die da verglichen werden: 
```
dump($articlePath);
dump(substr($url->getPath(), 0, strlen($articlePath)));
```
Bei mir sieht das dann so aus:
(Ich habe auch noch mal ".xml" genommen, damit klar ist, das eigene scheme wird verwendet...)
![Zwischenablage-1](https://user-images.githubusercontent.com/1277494/148068443-f4b736db-2192-49b6-b210-c2746cbda25b.jpg)

**Comment by tbaddade** [comment]
Hier die Variante mit .xml

<img width="1307" alt="Bildschirmfoto 2022-01-04 um 16 08 47" src="https://user-images.githubusercontent.com/338267/148079752-8829c53e-7004-4ff5-af1b-f0bba154647b.png">

Die Url wird aufgelöst. Eventuell müsste man einmal die Profile abgleichen.

**Comment by tbaddade** [comment]
Ich habe hier zu viele Profile, sodass ein Profile bereits das $resolve true lieferte und erst gar nicht bis zum Check mit dem $articlePath kam.
