### ISSUE TITLE
Sonderzeichen in Datensatz -> keine Url

### ISSUE THREAD

**Issue by fietstouring** [tbaddade/redaxo_url#241]
Habe ein Problem mit einer Datenbank aus Kunstwerken.
### Ein Titel lautet:  »!«

Der Titel soll Teil der URL sein, wird aber (klarerweise) nicht generiert, da ja normalisiert wird und die Zeichen entfernt werden.

Irgendjemand eine Idee obs da einen Workaround für dieses Problem gibt??

**Comment by alxndr-w** [comment]
Workaround A: die ID oder ein weiteres Feld zur Generierung der URLs hinzuziehen, also `!` wird zu `49` oder `Der Schrei` wird zu `401-der-schrei`
Workaround B: Ein separates Titelfeld anbieten, das verwendet wird und ggf. vorbelegt wird. 
Workaround C: Mit YForm ein Index-Feld verwenden und dieses aus mehreren Feldern befüllen lassen / über einen EP darauf Einfluss nehmen

**Comment by tbaddade** [comment]
Ich würde vermutlich eine View Table anlegen. und von dieser die Urls erzeugen lassen. Beim erzeugen dieser View würde ich den Titel normalisieren und wenn dieser danach "leer" ist, entweder die Id eintragen oder ein Fallback verwenden.

**Comment by fietstouring** [comment]
Danke für die Ideen, die einfachste Variante ist sicher, die ID mit in das Feld zu nehmen.
