### ISSUE TITLE
Installer Update-Hinweise

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_url#242]
Hey @tbaddade,

glückwunsch nochmal zum Release. Gerade habe ich ein altes 1.0 Projekt auf 2.0 geupdatet. Im Prinzip lief alles wie erwartet, außer, dass man vielleicht noch im Installer erwähnen sollte, dass man den Code von `1.0` zum Holen einer ID updaten muss.

```
// versuche die Url aufzulösen
$manager = Url\Url::resolveCurrent();
$movieId = $manager->getDatasetId();
```

Und, dass Profile von 1.0 auf 2.0 automatisch geupdatet werden.

Dann sind auch weniger versierte Personen im Bilde, was passiert, wenn man den Update-Link klickt und was einen erwartet.

**Comment by TobiasKrais** [comment]
Könnte noch hinzufügen, dass nach dem Update die URLs manuell neu generiert werden sollten.

**Comment by alxndr-w** [comment]
@TobiasKrais ist das so? Ist das nicht schon in der update.php enthalten?

**Comment by TobiasKrais** [comment]
Eigentlich müsste das auch funktionieren: https://github.com/tbaddade/redaxo_url/blob/968764877c4415453e1f4bd6aa2a01178b9f0c2b/update.php#L44. Ich konnte das nur bei einem Update testen. Dort musste ich die URLs nochmals neu generieren lassen. Kann es sein, dass das Generieren des Caches die URL Tabelle nicht füllt?

**Comment by tbaddade** [comment]
In der update.php wird `rex_delete_cache();` aufgerufen. 

Das wiederum löst den EP `CACHE_DELETED` aus, der dann [hier](https://github.com/tbaddade/redaxo_url/blob/968764877c4415453e1f4bd6aa2a01178b9f0c2b/lib/Url/ExtensionPointManager.php#L112-L114) die Urls erstellen sollte.

**Comment by tbaddade** [comment]
close via #243 … Danke @alxndr-w
