### ISSUE TITLE
Hinweis zu yform_usability

### ISSUE THREAD

**Issue by fietstouring** [tbaddade/redaxo_url#244]
Hab das dort auch schon gepostet: URLs werden bei Verwendung des Usability Status-Toggle nicht neu generiert.

**Comment by tbaddade** [comment]
Das AddOn müsste einen EP von YFom triggern.

**Comment by fietstouring** [comment]
https://github.com/FriendsOfREDAXO/yform_usability/issues/88

**Comment by alxndr-w** [comment]
https://github.com/alexplusde/yform_field bietet einen Status-Schalter `choice_status`, der über YOrm läuft und damit den EP triggert.
