### ISSUE TITLE
docs: Performance - getUrl() - SQL-Abfragen reduzieren

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_url#245]
In einer Übersicht werden 500-1000 Datensätze mit ihren jeweiligen Links ausgegeben, dies generiert einzelne SQL-Abfragen:

<html>
<body>

 
--
SELECT * FROM rex_url_generator_url WHERE `profile_id` = ? AND `data_id` = ? AND `clang_id` = ? AND is_user_path = ? AND is_structure = ? (< 1 ms)
SELECT * FROM rex_url_generator_url WHERE `profile_id` = ? AND `data_id` = ? AND `clang_id` = ? AND is_user_path = ? AND is_structure = ? (< 1 ms)
SELECT * FROM rex_url_generator_url WHERE `profile_id` = ? AND `data_id` = ? AND `clang_id` = ? AND is_user_path = ? AND is_structure = ? (< 1 ms)
SELECT * FROM rex_url_generator_url WHERE `profile_id` = ? AND `data_id` = ? AND `clang_id` = ? AND is_user_path = ? AND is_structure = ? (< 1 ms)
SELECT * FROM rex_url_generator_url WHERE `profile_id` = ? AND `data_id` = ? AND `clang_id` = ? AND is_user_path = ? AND is_structure = ? (< 1 ms)
SELECT * FROM rex_url_generator_url WHERE `profile_id` = ? AND `data_id` = ? AND `clang_id` = ? AND is_user_path = ? AND is_structure = ? (< 1 ms)

<br class="Apple-interchange-newline">
</body>
</html>

In der Summe sind das ca. 500ms gewesen

Ließe sich das optimieren / reduzieren?

**Comment by tbaddade** [comment]
Könnte dieser [Trick](https://friendsofredaxo.github.io/tricks/addons/url/lange_listen_schnell_ausgeben) dir hier helfen?

**Comment by alxndr-w** [comment]
Klasse! Das wird helfen.

**Comment by tbaddade** [comment]
Das Tricks-Beispiel und eine YOrm-Variante in Docs aufnehmen

**Comment by tbaddade** [comment]
@dtpop Könntest du einmal den [Commit](https://github.com/tbaddade/redaxo_url/commit/64735841288ea0ffd0e53da88ad5de6cbd1caab2) testen? Der sollte dir ebenso ein Array liefern, wie in deinem [Tricks-Beispiel](https://friendsofredaxo.github.io/tricks/addons/url/lange_listen_schnell_ausgeben).

```
<?php
$profiles = \Url\Profile::getByNamespace('prod_id');
foreach ($profiles as $profile) {
    dump($profile->getUrlsAsKeyValuePair('data_id', 'url'));
}
?>
```
