### ISSUE TITLE
Profil-Schlüssel (ehemals "urlParamKey" in URL1) wieder hinzufügen

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_url#248]
Vormals konnte man mit der Property `urlParamKey` ermitteln, um welches Profil es sich handelt, das unter der URL angesprochen wurde. Das ist nun nicht mehr möglich.

![image](https://user-images.githubusercontent.com/3855487/154551822-a1e52a06-507c-481c-b38a-b8a9025b5a35.png)

**Comment by tbaddade** [comment]
Ist über das Profil zu erreichen
```php
$manager = Url::resolveCurrent();
if ($manager && $profile = $manager->getProfile()) {
    dump($profile->getNamespace());
}
```

**Comment by alxndr-w** [comment]
Docs, gerne offen lassen.

**Comment by tbaddade** [comment]
@alxndr-w Magst du die Docs anpassen?

**Comment by alxndr-w** [comment]
@tbaddade ist mir 'ne Ehre, hoffe es passt so.
