### ISSUE TITLE
Notice in den Logs

### ISSUE THREAD

**Issue by olien** [tbaddade/redaxo_url#25]
```
25.10.2016 10:18:55 Notice  Undefined index: 1_xxx_rex_team_clang_id    
redaxo/src/addons/url/lib/Url/Generator.php
Zeile 69
```

**Comment by alexplusde** [comment]
@olien besteht das Problem noch? Kannst du das URL-Profil im Addon löschen und neu einrichten?

**Comment by olien** [comment]
Ja. Das Problem besteht noch. Profil gelöscht und neu geschrieben. Die Notice wird beim speichern des Profils ausgegeben.

**Comment by tbaddade** [comment]
@olien Ich kann das nicht nachstellen. Könntest du mal mit der GH-Version testen?

**Comment by tbaddade** [comment]
Notice kommt, wenn nur eine Sprache vorhanden ist.

**Comment by TobiasKrais** [comment]
Ist in Version 2 behoben. Der Issue könnte m. E. gelöscht werden, oder?

**Comment by tbaddade** [comment]
> Ist in Version 2 behoben.
