### ISSUE TITLE
Neue getTags() Methode aus YRewrite nutzen

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#254]
Nachdem https://github.com/yakamara/redaxo_yrewrite/pull/310 gemerged wurde sind Anpassungen nötig, damit die Methode `Seo:getTags()` auch die neuen OG Tags von Artikeln ausgibt.

**Comment by tbaddade** [comment]
Welche neuen OG Tags sind das? In dem verlinkten PR sind m.E. keine neuen zu sehen.

**Comment by TobiasKrais** [comment]
Ja, das stimmt. Ich habe meinen Code auch angepasst (https://github.com/TobiasKrais/d2u_helper/blob/8a4d4c56725ce6e22b4097eb41d10e23a50b76e8/lib/d2u_addon_frontend_helper.php#L199-L214). Es könnte aber das eine oder andere Projekt geben, das die Änderung nicht bemerkt und somit nicht profitiert.

Lösung wäre eine einfache Änderung im Code: man prüft, ob das url Addon verantwortlich ist und wenn nicht wird einfach die Methode vom Rewriter aufgerufen und ausgegeben.

**Comment by tbaddade** [comment]
> Lösung wäre eine einfache Änderung im Code: man prüft, ob das url Addon verantwortlich ist und wenn nicht wird einfach die Methode vom Rewriter aufgerufen und ausgegeben.

Das macht man zumeist schon über das Auflösen der Url.

Ich kann mir vorstellen, dass das Url-AddOn sich direkt an den [EP](https://github.com/yakamara/redaxo_yrewrite/blob/50ee71fb1bc242cb81393ccbd29ec5621e6b3ea4/lib/yrewrite/seo.php#L106) hängt und dann selbst die Ausgabe beeinflusst.

**Comment by alxndr-w** [comment]
Da man in URL-Profilen ja bspw ein Meta--SEO-Bild-Feld festlegen kann, wäre es sinnvoll, wenn dieses auch automatisch verwendet wird. So war's glaube ich gemeint von @TobiasKrais

**Comment by tbaddade** [comment]
> Da man in URL-Profilen ja bspw ein Meta--SEO-Bild-Feld festlegen kann, wäre es sinnvoll, wenn dieses auch automatisch verwendet wird.

Das wird bereits [hier](https://github.com/tbaddade/redaxo_url/blob/9bf98b17abe509390c01081fdcde07c5c2d1d559/lib/Url/Seo.php#L80) berücksichtigt

**Comment by TobiasKrais** [comment]
Ja, bei URLs die vom url Addon erzeugt werden, wird es berücksichtigt, aber nicht bei URLs die von YRewrite erzeugt werden. Ich bin mir nicht sicher, ob ihr verstanden habt, was ich meine. Lasst es mich nochmals aus historischer Sicht erklären:

Bisher war der Output der Meta Tags auf gewöhnlichen Redaxo Artikelseiten beim url Addon und von YRewrite ziemlich gleich. Handelte es sich um eine URL die durch das url Addon erzeugt wurde, war der Output sogar viel besser, da hier Open Graph schon lang berücksichtigt wird. Deshalb habe ich YRewrite gar nicht mehr abgefragt sondern für alle Seiten die das url Addon verwenden, folgenden Code auf allen Seiten verwendet:
```php
$urlSeo = new Url\Seo();
$meta_tags = $urlSeo->getTags();
```
Das ist mir jetzt zum Nachteil, denn für gewöhnliche Artikel erhalte ich keine Open Graph Tags wie YRewrite das jetzt kann. Es wäre doch super, wenn hier auf die neue `getTags()` Funktion des YRewrite Addon zurückgegriffen wird, so dass immer OG Tags ausgegeben werden, also nicht nur auf URLs die vom url Addon generiert werden, sondern auch auf "herkömmlichen" Artikel URLs. Ist euch jetzt klarer, was ich meine?

**Comment by tbaddade** [comment]
Nur so als Idee:

```php
<?php
\rex_extension::register('YREWRITE_SEO_TAGS', function($ep) {
    $yrewriteTags = $ep->getSubject();

    \rex_extension::register('URL_SEO_TAGS', function($ep) use ($yrewriteTags) {
        $urlTags = $ep->getSubject();

        return array_merge($yrewriteTags, $urlTags);
    });

    $seo = new Url\Seo();
    $urlTags = $seo->getTags();
});
?><!DOCTYPE html>
<html>
<head>
    <?php
    $seo = new rex_yrewrite_seo();
    echo $seo->getTags();
    ?>
</head>
</html>
```

Ich denke aber ich verstehe jetzt was du meinst. Sobald es keine Url-AddOn Seite ist, wird [hier](https://github.com/tbaddade/redaxo_url/blob/master/lib/Url/Seo.php#L44-L46) abgebrochen.

**Comment by alxndr-w** [comment]
Für mich zum Nachvollziehen, welches Verhalten wurde jetzt erwirkt?

**Comment by tbaddade** [comment]
Url überschreibt jetzt die Tags von yrewrite. Im Template am besten jetzt das verwenden:

```php
$seo = new rex_yrewrite_seo();
echo $seo->getTags();
```

Url hakt sich dann bei yrewrite ein. Wenn ihr hier Probleme seht, dann gern melden.

**Comment by alxndr-w** [comment]
Toll, das habe ich mir schon lange gewünscht. Ich gebe zeitnah Feedback.
