### ISSUE TITLE
Kompatibilität zu cache_warmup oder eigenen Warmup-Mechanismus

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_url#259]
Siehe https://github.com/FriendsOfREDAXO/cache_warmup/issues/114 - allerdings kann sich URL2 nicht dort einklinken, da es keinen passenden EP gibt.

Evtl. könnte man einen eigenen Warmup-Mechanismus implementieren.

**Comment by tbaddade** [comment]
> Evtl. könnte man einen eigenen Warmup-Mechanismus implementieren.

Sehe ich nicht in diesem AddOn. Da du es für dich bereits gelöst hast, würde ich daher hier gern schließen.

**Comment by alxndr-w** [comment]
Passt! Danke.
