### ISSUE TITLE
Leere Einträge

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#26]
Szenario:
- Artikel `domain.de/produkte/` ist ein Ziel-Artikel des URL-Plugins, die Artikel werden über `domain.de/produkte/slug/` aufgerufen.
- Datenbank-Eintrag `Gummipunkt` in `rex_products` wird mit leerem URL-Feld (hier: `slug`) befüllt
- Daraufhin liefert  `domain.de/produkte/` (ohne `slug`-Wert, die Übersichtsseite) die `id` zum Datenbankeintrag `Gummipunkt` zurück.

Zu erwarten wäre, dass leere Eingaben grundsätzlich keinen Datenbanktreffer auslösen können.

(In der Hilfe könnte man desweiteren erwähnen, dass YForm für das URL-Feld (hier: `slug`) 2 Validierungen anwendet: `unique` und `empty`. Bei uns war `empty` nicht aktiviert.)

**Comment by alexplusde** [comment]
Sollte in der Doku empfohlen werden. Man muss sich eben bewusst machen, was man tut.

Das Issue ist 3 Jahre alt. Heute würde ich nicht nur auf empty prüfen, sondern direkt an der Datenbank NULL nicht erlauben.

**Comment by tbaddade** [comment]
Ich öffne noch einmal, wegen den Hinweis in der Doku.
