### ISSUE TITLE
`is_user_path` müsste INT sein

### ISSUE THREAD

**Issue by ynamite** [tbaddade/redaxo_url#266]
In einem aktuellen Projekt wird bei isUserPath immer `false` zurückgegeben, da `$this->values['is_user_path']` vom Typ INT ist, aber mit einem String verglichen wird. 

https://github.com/tbaddade/redaxo_url/blob/664a895ae07d5f19091418ac063916d4b7c39700/lib/Url/UrlManager.php#L229

Aktuellste Version von URL.

Wenn ich die '1' zu `1` ändere, klappt's. Soll ich einen PR machen?

**Comment by tbaddade** [comment]
Kannst du mal prüfen, ob das bei dir bereits `bool` ist?

**Comment by ynamite** [comment]
Ne, `$this->values['is_user_path']` ist eine INT, wenn du das meinst.

**Comment by tbaddade** [comment]
Gern PR … schau mal paar Zeilen darüber `isStructure` … Müsste dann dort ebenfalls INT sein oder?

**Comment by ynamite** [comment]
Ich meine ja, bin aber nicht ganz sicher. Kann es kurz testen. Wozu ist `isStructure` denn gedacht bzw. wann ist es 1  (oder 0)?

**Comment by tbaddade** [comment]
> Wozu ist isStructure denn gedacht  

Das wäre die Auswahl im Profil "Unterkategorien anhängen?"

Du hast einen Artikel, der noch Unterkategorien hat. Beispiel Filme

- Filme <- url Artikel
- Filme : Schauspieler <- Unterkategorie in der Strukturverwaltung

Es werden dann pro Datensatz 2 Urls erstellt

- /filme/the-big-lebowski/
- /filme/the-big-lebowski/schauspieler/

**Comment by ynamite** [comment]
PR ist erstellt und ja, auch bei is_structure ist es eine INT :) 
https://github.com/tbaddade/redaxo_url/pull/267

**Comment by tbaddade** [comment]
close via #https://github.com/tbaddade/redaxo_url/pull/267
