### ISSUE TITLE
Whooops beim speichern // Konflikt mit yform_usability

### ISSUE THREAD

**Issue by olien** [tbaddade/redaxo_url#269]
https://github.com/FriendsOfREDAXO/yform_usability

![image](https://user-images.githubusercontent.com/330516/214775434-c317af04-cc96-41f7-95d9-50c7e5667861.png)
![image](https://user-images.githubusercontent.com/330516/214775657-bd76d52d-0f2c-4e43-8b95-3b137b3022dd.png)

**Comment by eaCe** [comment]
@olien https://github.com/FriendsOfREDAXO/yform_usability/issues/130

**Comment by olien** [comment]
Ups. Danke

**Comment by alxndr-w** [comment]
close
