### ISSUE TITLE
YForm EP "delete" u.a.: Pathlist aktualisieren

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#27]
In unserem Fall wurde die Pathlist nicht aktualisiert, wenn wir einen Datenbank-Eintrag gelöscht haben. Das wäre jedoch notwendig, da sonst alte URLs in der Pathlist bleiben. (ich weiß nicht, ob das grundsätzlich so ist, ist aber im Rahmen von https://github.com/tbaddade/redaxo_url/issues/26 aufgefallen)

**Comment by alexplusde** [comment]
Workaround: einen Struktur-Artikel aktualisieren oder Systemseiten neu setzen (bspw. Fehler 404-Seite)

**Comment by tbaddade** [comment]
> YForm EP "delete"

Gibt es da einen?

**Comment by tbaddade** [comment]
Danke

**Comment by alexplusde** [comment]
<3
