### ISSUE TITLE
Warning bei der Ausgabe der SEO Tags

### ISSUE THREAD

**Issue by olien** [tbaddade/redaxo_url#270]
![image](https://user-images.githubusercontent.com/330516/214776263-56af1d0b-5130-4900-afa8-0e47ac36967c.png)
![image](https://user-images.githubusercontent.com/330516/214776295-7e358204-1932-42f5-874d-4ff61a028171.png)

**Comment by olien** [comment]
Ah. das kommt anscheinend nur auf Seiten die nicht in URL als Ausgabeseite eingetragen sind.

**Comment by tbaddade** [comment]
Probier es mal so:

```
$seo = new \rex_yrewrite_seo();
<head>
    ...
    <?= $seo->getTags() ?>
    ...
</head>
```

Url hakt sich direkt via EP bei yrewrite ein.

**Comment by olien** [comment]
jepp. so geht es
