### ISSUE TITLE
SEO/Sitemap Ausgabe gemäss Status - neues Feld

### ISSUE THREAD

**Issue by paddle07** [tbaddade/redaxo_url#273]
Kleine Anregung, wäre toll, wenn unter SEO neben headline, description und image zusätzlich ein Feld für Status gespeichert werden könnte (0/1). Offline Einträge würden dann automatisch mit noindex, nofollow ausgegeben und auch nicht in der Sitemap aufgeführt. Löse das aktuell mit Extension Points.
Ansonsten tolles Addon, danke!!

**Comment by alxndr-w** [comment]
Dafür kannst du eigentlich im Query angeben, ob URLs generiert werden sollen (und ein 2. Profil anlegen, wenn du sie trotzdem erreichbar haben willst)

**Comment by paddle07** [comment]
So natürlich auch möglich ... somit müsste ich die Profil-Abfrage beim Vorschau-Link des Addons machen. Dachte nur es wäre evtl. einfacher dies direkt bei den SEO-Feldern zu intergerieren, da wahrscheinlich bei den meisten Addons ein online/offline Status der Einträge benötigt wird.

**Comment by tbaddade** [comment]
Die Abfrage nach einem Status kann über einen EP beeinflusst werden. Das fix einzubauen ist nicht möglich. Denn wie schon @alxndr-w anmerkte, spielen dann auch u.a. Relationen eine Rolle. Auch ist der Wert status nicht nur auf `0` und `1` beschränkt.

> somit müsste ich die Profil-Abfrage beim Vorschau-Link des Addons machen

Die Abfrage solltest du schon beim Absetzen des Queries aller Vorschauen machen, damit du so wenig Datensätze wie nur möglich erholst (Performance).

```php
<?php
$items = rex_sql::factory()->getArray('SELECT `id`, `title` FROM `rex_item` WHERE `status` = "1"');
foreach ($items as $item) {
    echo sprint('<a href="%s">%s</a>', rex_getUrl('', '', ['namespace_id' => $item['id']]), $item['title']);
}
```

oder
```php
<?php
$categories = rex_sql::factory()->getArray('
    SELECT
        c.id AS cid, 
        c.title AS cname, 
        i.id AS iid,
        i.title AS iname 
    FROM rex_category AS c 
    LEFT JOIN rex_item AS i
        ON c.id = i.category_id 
    WHERE c.status = "1"
        AND i.status = "1"
    ');
```

**Comment by paddle07** [comment]
Ok, alles klar, danke euch

**Comment by alxndr-w** [comment]
@paddle07 wenn das für dich passt, dann kannst du das Issue gerne schließen.
