### ISSUE TITLE
SEO-Metatags auf Nicht-URL-generierten Seiten gibt nur "Array" aus

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_url#275]
```
Array
```

als Ausgabe von 

```
use Url\Seo;

$seo = new Seo();
echo $seo->getTags();
```  

Ist das so gewollt? Oder muss ich unterscheiden, ob ich mich in einer URL oder einem klassischen Artikel befinde oder nicht?

**Comment by tbaddade** [comment]
> Ist das so gewollt? Oder muss ich unterscheiden, ob ich mich in einer URL oder einem klassischen Artikel befinde oder nicht?

Wenn du die aktuellste Version nutzt, dann sollte folgendes reichen:

```
$seo = new rex_yrewrite_seo();
echo $seo->getTags();
```

Url hängt sich an einem EP von yrewrite dran.

**Comment by alxndr-w** [comment]
Sind dann die Docs verkehrt?

**Comment by alxndr-w** [comment]
Siehe auch #271
