### ISSUE TITLE
Datensatz in allen Sprachen auch ohne Angabe einer clang_id erlauben

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_url#281]
Ich habe ein Szenario, da habe ich 3 Systemsprachen und ein URL-Profil, dessen Unterseiten ausschließlich über einen Hash-Wert 
oder eine UUID generiert werden.

Der Artikel dazu wird in allen 3 angelegten Sprachen gleichermaßen verfügbar sein. Demzufolge möchte ich "Alle Sprachen" auswählen können, ohne am Datensatz eine Sprache hinterlegen zu müssen.

![image](https://github.com/tbaddade/redaxo_url/assets/3855487/806b69b9-fd3e-4e78-9216-a5e248636d6e)

URL sollte dann für alle 3 Sprachen gleichermaßen die URLs generieren können.

**Comment by tbaddade** [comment]
Dann musst du 3 Profile anlegen. Sonst klappt das nicht. Dein gewünschtes Szenario wird leider nur zu Problemen führen.

**Comment by alxndr-w** [comment]
Oder eine View mit demselben Datensatz je clang.

Schade, was ist denn der Grund für die Restriktion oder ist das konzeptionell so notwendig? Falls man das einfach zusammen fassen kann.

**Comment by tbaddade** [comment]
Ich meine es ginge nicht um das Anlegen sondern um das Auflösen der Url und den Aufruf des richtigen Artikels. URL war ja einmal komplett egal, welcher Rewriter genutzt wurde.

Du kannst dich aber gern daran probieren und das umzustellen. Ich selbst benötige das nicht und werde da keine Zeit investieren.
