### ISSUE TITLE
Zweite Datenbank - SQL Abfrage geht Auf Datenbank 1

### ISSUE THREAD

**Issue by lokbase** [tbaddade/redaxo_url#283]
Wir bekommen einen Fehler SQL-Fehler beim Setup:
Beim editieren bekommen wir die zweite Datenbank angezeigt mit korrekter Auswahl der Tabelle (projekte). »Datensatz identifizieren« bietet ebenfalls die korrekte Auswahl der Tabelle aus der Datenbank.  Beim sicher erhalten wir einen SQL-Fehler

Table **d0340bfe.projekte** doesn't exist
Korrekt, es müsste lauten: **d03454c6.projekte**

In der Tabelle rex_url_generator_profile findet sich der Eintrag
2_xxx_projekte
Sieht eigentlich gut aus. 

PHP 8.1 | URL 2.10 | redaxo 5.15.1

**Comment by alxndr-w** [comment]
"Beim sicher erhalten wir einen SQL-Fehler" - was heißt das?

Geht es um das REDAXO-Setup zur Installation bzw über System > Setup?

**Comment by lokbase** [comment]
Entschuldigung richtig: Es passiert nach dem einstellen eines neuen Profils.

**Comment by tbaddade** [comment]
Siehe Kommentar
https://github.com/tbaddade/redaxo_url/issues/214#issuecomment-822533484
