### ISSUE TITLE
Keine generierung von Links aufgrund von clang_id null

### ISSUE THREAD

**Issue by mschnieder** [tbaddade/redaxo_url#286]
Beim erzeugen von URLs erhalte ich keine Fehlermeldung und es wird nichts generiert.
Konnte den Fehler daraufhin eingrenzen, das beim insert in der Datenbank das Feld clang_id auf NULL gesetzt ist.

Fehler in der Datei:
[https://github.com/tbaddade/redaxo_url/blob/master/lib/Url/Profile.php](url)

Zeile 394, $clangId ist dort Null, die Datenbank lässt null aber nicht zu.

**Comment by alxndr-w** [comment]
#281 hast du mehrere Sprachen im Einsatz?

**Comment by mschnieder** [comment]
Nein, habe nur eine Sprache.
Was aber vielleicht eine Besonderheit ist, ich habe in dem System wo ich den Fehler hatte, ursprünglich 2 Sprachen drin und eine gelöscht.

**Comment by alxndr-w** [comment]
Und das URL-Profil steht nicht auf "alle Sprachen", sondern nur auf der einen und wurde frisch abgespeichert?

**Comment by tbaddade** [comment]
> Was aber vielleicht eine Besonderheit ist, ich habe in dem System wo ich den Fehler hatte, ursprünglich 2 Sprachen drin und eine gelöscht.

@mschnieder Lösche mal das Profil und lege es neu an.

**Comment by mschnieder** [comment]
@tbaddade Das Problem ist durch das löschen behoben.

Für mich erledigt, aber sollte ggf. nen Fix das ganze beheben, wenn die clangId an der stelle leer ist, das es eine Fehlermeldung gibt oder vielleicht dann nur die Standard Sprach ID sich aus dem Redaxo holt?

**Comment by tbaddade** [comment]
> Für mich erledigt, aber sollte ggf. nen Fix das ganze beheben, wenn die clangId an der stelle leer ist, das es eine Fehlermeldung gibt oder vielleicht dann nur die Standard Sprach ID sich aus dem Redaxo holt?

Schlussendlich wird die Default Sprach-ID verwendet. Ich habe vermutet, dass in deinem Profil eine Sprach-ID gespeichert wurde (wegen deinen 2 Sprachen zuvor) und diese durch das erneute Speichern aber nicht mehr in der DB angepasst wurde. Denn die Auswahl der Sprachen erscheint auch nur, wenn du mehr als eine Sprache dabei hast.
