### ISSUE TITLE
Beispiel für "normale" Frontend Sitemap

### ISSUE THREAD

**Issue by olien** [tbaddade/redaxo_url#29]
Hey Thomas,

ist es möglich die generierten URLs irgendwo in eine "normale" Sitemap einzuhängen?

LG
Oliver

**Comment by alexplusde** [comment]
Lösungsansatz wäre doch, sich in den entsprechenden Navigationspunkt über einen Filter einzuhängen und dann ganz normal eine Datenbank-Abfrage zu machen.

Da das in meinen Augen ja simulierte "Artikel" sind und keine "Kategorien", wäre es auch nicht notwendig, dass die Redaxo Navigation-Factory sie sehen kann,

**Comment by tbaddade** [comment]
Ich denke das wird hier zu spezifisch. Es gibt verschiedene Varianten um die eigene Frontend Sitemap zu bestücken und auszugeben.

Will man für einen Artikel die Urls erhalten, gibt es bereits im Url AddOn verschiedene Möglichkeiten, sodass man hier denke ich bereits flexibler unterwegs ist, als wenn das AddOn selbst etwas vorgibt.
