### ISSUE TITLE
Call to a member function normalize() on null

### ISSUE THREAD

**Issue by muenzberg-me** [tbaddade/redaxo_url#30]
Ich habe mir gerade ein neues Addon für die Ausgabe meiner Events geschrieben und wollte gern suchmaschinenoptimierte URLs haben. Dies lief bis vor kurzem super doch jedesmal wenn ich, nach der Re-Installation das redaxo_url Addons, den System-Cache lösche bekomme ich folgenden Fehler angezeigt.

> "Error" thrown in /www/htdocs/w010b316/muenzberg.me/redaxo/src/addons/url/lib/Url/Rewriter/Yrewrite.php on line 127
Call to a member function normalize() on null

**Comment by tbaddade** [comment]
Welche Versionen von yrewrite und url verwendest du?

**Comment by muenzberg-me** [comment]
url	1.0.0-beta4
yrewrite	2.2.1

ich habe auch schon direkt die Sachen aus dem GitHub geladen

**Comment by tbaddade** [comment]
Ich kann den Fehler nicht nachvollziehen. Falls der Fehler mit der aktuellen wieder auftreten sollte, gerne das Issue wieder öffnen.
