### ISSUE TITLE
Undefined Index for clang

### ISSUE THREAD

**Issue by psgehe** [tbaddade/redaxo_url#31]
Hi,

wenn ich mir eine URL ausgeben lassen will kommt bei mir folgender Fehler:
**Undefined index: 1_xxx_rex_news_clang_id    
redaxo/src/addons/url/lib/Url/Generator.php** (aktuelles generator.php aus dem Git ist eingebunden)

Somit kann ich natürlich auch meine URL nicht aufrufen.
Dieses Problem tritt sowohl lokal als auch live auf.

Ich habe meine Konfiguration via YRewrite vorgenommen (Domain für deutsche Sprache ist eingerichtet - htaccess gesetzt).

Versionen:
- yRewrite 2.2.1
- URL 1.0.0-Beta4

**Comment by tbaddade** [comment]
Duplicate #25
