### ISSUE TITLE
rex_getUrl() ohne Parameter liefert URL des Artikels, nicht der aktuellen URL

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#32]
Szenario: Ein YForm-Formular, das das Formular an die aktuelle Seite absenden soll, die mit dem URL-Addon generiert wurde.

```
$yform->setObjectparams('form_action',rex_getUrl());
```

erwartetes Verhalten: Die URL der aktuellen Seite wird ausgegeben
tatsächliches Verhalten: Die URL des Artikels wird ausgegeben.

Noch schöner wäre es btw., wenn YForm direkt die korrekte URL bei aktiviertem Addon übernimmt, stattdessen wird man auf die 404er-Seite weitergeleitet.

**Comment by tbaddade** [comment]
Abhilfe sollte der UrlParamKey schaffen.

```php
$id = UrlGenerator::getId();
$data = UrlGenerator::getData();

$yform->setObjectparams('form_action',rex_getUrl('', '', [$data->urlParamKey => $id]));
```

Damit bleibst du auf der eigentlichen Url.

**Comment by alexplusde** [comment]
Das würde ich mir in der Readme zum Addon wünschen.

**Comment by alexplusde** [comment]
Könnte man ja gleich Url::current() nehmen (Gerade in Slack gesehen)
