### ISSUE TITLE
sitemap.xml fehlerhaft

### ISSUE THREAD

**Issue by olien** [tbaddade/redaxo_url#33]
Hi,

sofern ich die erzeugten URLs mit in der sitemap.xml anzeigen lassen möchte wird die sitemap.xml nicht richtig ausgegeben.

Es werden zwei Leerzeichen am Anfang gerendert.

LG
Oliver

`XML-Verarbeitungsfehler: XML- oder Text-Deklaration nicht am Beginn der Entität
Adresse: http://abc.de/sitemap.xml
Zeile Nr. 1, Spalte 3:  <?xml version="1.0" encoding="UTF-8"?>
--^`

**Comment by skerbis** [comment]
Kann es sein, dass die Leerzeichen wo anders her kommen? Ich kann das bei mir nicht feststellen. (Irgendein Outputfilter vielleicht)

**Comment by olien** [comment]
Das Plugin "structure_separators" von "out5" ist schuld. @olien
Danke für den Tipp Thomas!
