### ISSUE TITLE
meta title und description funktioniert nicht - yrewrite

### ISSUE THREAD

**Issue by steri-rex** [tbaddade/redaxo_url#34]
Ich verwende yrewrite 2.2.1 und url 1.0.0-beta4 - die URL Generierung auf Basis einer erstellten Veranstaltungs DB funktioniert super - auch die Ergänzung der URLs in die Sitemap. Nur die SEO Generierung des meta titles und meta description will irgendwie nicht. Trotz Einstellung im Addon kommt nicht title und description aus den gewählten Spalte sondern immer noch vom Artikel. Hab ich etwas vergessen?
Als Ausgabe im header verwende ich 
`<?php
      $seo = new rex_yrewrite_seo();
      echo $seo->getTitleTag().PHP_EOL;
      echo $seo->getDescriptionTag().PHP_EOL;
      echo $seo->getRobotsTag().PHP_EOL;
      echo $seo->getHreflangTags().PHP_EOL;
      echo $seo->getCanonicalUrlTag().PHP_EOL;
?> 	`

**Comment by tbaddade** [comment]
Du musst `new UrlSeo()` schreiben.

**Comment by steri-rex** [comment]
danke! funktioniert

**Comment by Hirbod** [comment]
Bitte mal einen Hinweis hierzu in die README. Generell fehlt hier noch bisschen mehr Doku. Ggf @alexplusde mal :)
