### ISSUE TITLE
UrlGenerator::getId() um "Parameter für rex_getUrl" erweitern

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#35]
Ich habe gerade den Fall, dass auf einer Seite ein Template an mehreren Artikeln eingebunden werden, die `UrlGenerator::getId()` verwenden. So kann es sein, dass `UrlGenerator::getId()` darin einmal die ID des Datensatzes aus `tabelle_a` bekommt, bspw. `5`und einmal die des Datensatzes aus `tabelle_b`, bspw. auch `5`

Ich möchte allerdings nur dann eine ID, wenn ich mich auch im korrespondierenden Artikel befinde, bspw. 
`UrlGenerator::getId('tabelle_a')`. Das muss ich derzeit von Hand abfragen, bspw.:

```
$event_id = UrlGenerator::getId();
if($event_id && rex_article::getCurrentId() == 6) {
```

**Comment by tbaddade** [comment]
Verstehe nicht ganz das Problem. Die getId() Methode holt anhand der aktuellen Url die Id zum Datensatz. Wie kannst du mehrere Ids gleichzeitig bekommen?

**Comment by alexplusde** [comment]
Beispiel: Ein Template mit einem Hero-Slider, der bei Künstlern eine Galerie des Künstlers zeigt, bei Events eine Galerie der Veranstaltung. Mit `if(UrlGenerator::getId())` hole ich mir ggf. eine ID an der Stelle, an der ich gar keine will. Soll ich dir den Template-Code mal in Slack zuschicken? Dann wird's evtl klarer.

**Comment by tbaddade** [comment]
Code würde helfen :)
Du kannst auch mal getData anstatt getId  probieren. Eventuell hilft dir das schon weiter.

**Comment by alexplusde** [comment]
getData() löst mein Problem. Issue kann geschlossen werden, falls du es nicht als Reminder benötigst.
