### ISSUE TITLE
URL-Vorschau: Immer Domain dazu schreiben

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#39]
Wenn man mehr als eine Domain in YRewrite hat, dann wird bei unterschiedlichen URL-Profilen mal die URL zum Artikel 
* mal als `/folder/scheme`, und `http://domain2.de/folder/scheme/`, oder 
* mal als `http://domain1.de/folder/scheme`, und `/folder/scheme/` angezeigt 

Je nachdem, mit welcher Domain man im Redaxo-Backend eingeloggt ist. Ist das so gewollt?

**Comment by tbaddade** [comment]
> Ist das so gewollt?

Das ist das Standardverhalten von yrewrite bzw. vom eingesetzten Rewriter. Wenn du in den Slices ebenfalls `rex_getUrl` verwendest, wirst du bei yrewrite dasselbe Verhalten sehen.

Die Urls die du ansprichst, werden hier erzeugt.
https://github.com/tbaddade/redaxo_url/blob/master/pages/generate.php#L68

**Comment by alexplusde** [comment]
In meinen Augen müsste aber, auch um Verwirrung zu vermeiden, bei URL in der Übersicht an URL-Schemen immer die korrekte Domain mit angezeigt werden.
