### ISSUE TITLE
mehrere Einschränkungen

### ISSUE THREAD

**Issue by mbodon** [tbaddade/redaxo_url#41]
Hallo Thomas, es wäre schon wenn man mehrere "Einschränkungen" haben könnte und diese noch mit AND und OR kombinieren könnte (z.B. "status=1 AND jahr >2016" oder "category=1 OR category=2")

**Comment by alexplusde** [comment]
+1

**Comment by nilsology** [comment]
+1

**Comment by tbaddade** [comment]
Es wären ab Version 2 drei Einschränkungen möglich, die später auch leicht angepasst werden können.
