### ISSUE TITLE
Fehler durch falschen Variablentypen / Kompatibilität mit structure_tweaks

### ISSUE THREAD

**Issue by DanielWeitenauer** [tbaddade/redaxo_url#43]
Wenn die Pathlist im Backend neu generiert wird und man sich auf einer Seite befindet, die ein Modul enthält, dass das Addon aufruft, wird die `Methode Generator::getUrlById` aufgerufen. Zu diesem Zeitpunkt enthält die Variable `Generator::$paths` die gerade generierten Daten. Dadurch ist `$articleIds[$articleId][$primaryId][$clangId]` in dieser Schleife https://github.com/tbaddade/redaxo_url/blob/master/lib/Url/Generator.php#L534-L569 ein `stdObject` und kein Array, wodurch der Fehler `Cannot use object of type stdClass as array` geworfen wird.
Wenn ich vor der Schleife die Daten statt mit `self::ensurePaths()` mit `self::$paths = \rex_file::getCache(self::$pathfile);` zwingend neu lade, funktioniert es. 
Der Fehler fiel mir im Zusammenhang mit dem online/offline Schalten eines Startartikels in den durch structure_tweaks verschobenen Metadaten auf.

**Comment by tbaddade** [comment]
@DanielWeitenauer in er GH Version ist bereits ein fix.
https://github.com/tbaddade/redaxo_url/commit/6de80a185b9cb1c7da32fb9f12b2e5994c4a551d

Ich lasse das Issue aber offen, da mir die Lösung nicht gefällt.

**Comment by tbaddade** [comment]
Ist in Version 2 anders gelöst worden.
