### ISSUE TITLE
rex_getUrl() gibt falsche URL zurück, wenn ParamKey bei mehreren Artikeln gleich ist

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#47]
Ich verwende bei mehreren Artikeln den ParamKey "category_id". Die folge ist, dass beim rex_getUrl() Aufruf nur der erste Treffer in der Pathlist korrekt übersetzt wird, sonst wird die URL nur mit ?category_id ausgegeben.

**Comment by tbaddade** [comment]
Richtig. Der Paramkey ist eine Art Namespace und sollte nur einmal vorkommen. Da der Key auch nirgends sichtbar ist, kann man diesen auch "news-category-id" nennen.

Ich werde dazu das AddOn umbauen und vermutlich komplett auf den ParamKey umstellen.

**Comment by TobiasKrais** [comment]
Danke! Bis dahin ist mein fix eine ziemlich praktische Lösung.

**Comment by tbaddade** [comment]
Ich meine, damit gehen Urls die nur über die Id angesprochen, also ohne Paramkey in der Config, verloren. Deshalb will ich das einheitlich machen.

**Comment by TobiasKrais** [comment]
Nein. Dem ist nur so, wenn die falsche Artikel ID übergeben wird. Im Moment kann man an rex_getUrl irgend eine Artikel ID übergeben und es wird die URL übergeben die zum zusätzlichen Parameter passt zurückgegeben, auch wenn der nur zu einem ganz anderen Artikel passt.

**Comment by tbaddade** [comment]
Ich meine etwas anderes. Es gibt auch diese Möglichkeit

`rex_getUrl(4, '', [id=>3])` Die **4** ist dabei die hinterlegte Artikel Id in der Config. Der Paramkey wurde dabei in der Config **nicht** gesetzt.

**Comment by TobiasKrais** [comment]
In dem Fall wird der Code, den ich gefixt habe gar nicht berührt. Da gibt es vorher ein `if`:
https://github.com/tbaddade/redaxo_url/blob/master/lib/Url/Generator.php#L613

Nur wenn ein Paramkey gesetzt wird springt er weiter:
https://github.com/tbaddade/redaxo_url/blob/master/lib/Url/Generator.php#L616
Und dann wird die in rex_getUrl() übergebene Artikel ID überschreiben.

**Comment by tbaddade** [comment]
Habe mir das nochmal angesehen. Dein Fix wandelt sich hier in einen Bug.

Der Aufruf `rex_getUr('', '', ['category-id' => $id])` wird nur dann deinen Artikel erreichen, wenn man bereits auf demselben Artikel ist, der auch in der Config hinterlegt wurde. Du müsstest ansonsten immer die Artikel-Id bei `rex_getUrl` mit geben. Sinn und Zweck der ParamKeys ist es aber, grad auf diese Artikel-Id zu verzichten und egal wo man sich grad innerhalb der Struktur befindet, ein Aufruf von`rex_getUr('', '', ['category-id' => $id])` immer den korrekten REDAXO-Artikel findet.

**Comment by TobiasKrais** [comment]
Ich kann dein Ziel verstehen, aber hast du eine Lösung für das eigentliche Problem, also dass die URL nicht immer korrekt umgeschrieben wird? Es mag zwar sein, dass die mein fix nicht gefällt, aber das Problem besteht immer noch.

**Comment by tbaddade** [comment]
Das Problem ist doch, dass du den ParamKey mehrfach verwendest. Dieser sollte aber nur einmal verwendet werden. Eventuell kannst du einen Dump bereitstellen, damit ich deine Variante mal testen kann.

**Comment by alexplusde** [comment]
@tbaddade kannst du beim Abspeichern evtl. prüfen, ob der key schon vorhanden ist / mit einer unique-Validierung?

@TobiasKrais in deinem Fall kannst du doch auch weiterhin ohne key die URL generieren?

**Comment by TobiasKrais** [comment]
Um das Szenario zu testen, könnt ihr euch das d2u_machinery Addon installieren. Beim installieren werden die Konfigurationen fürs url Addon automatisch installiert. Im d2u_machinery Addon einfach eine Testmaschine, und eine Testkategorie anlegen. Module werden auch angeboten und wenn ihr ein passendes Template zum Testen braucht, könnt ihr im d2u_helper Addon (wird fürs d2u_machinery Addon benötigt) das Template "00-1 Big Header Template" installieren. Hilft euch das schon, oder soll ich eine Testseite aufsetzen?

Den Paramkey verwende ich nicht (!) mehrfach. Einmal lautet er category_id, einmal machine_id und beim industry_sectors Plugin lautet er industry_sector_id, beim used_machines Plugin lautet er used_machine_id. Noch ein Hinweis: ich arbeite auch noch mehrsprachig.

@alexplusde: dein Vorschlag ist nicht möglich, da ich in einem Artikel sowohl mit Kategorien als auch den Maschinen in den Kategorien arbeite. Deshalb kann ich nicht ohne key arbeiten, da es sonst zu Verwechslungen kommt. Ein Live Beispiel findest du hier: http://www.meier-krantechnik.de/.

Danke für eure Geduld!

**Comment by tbaddade** [comment]
> Ich verwende bei mehreren Artikeln den ParamKey "category_id"
> Den Paramkey verwende ich nicht (!) mehrfach.

Das widerspricht sich aber jetzt, oder?

Ich ging davon aus, dass du eben diesen ParamKey `category_id` mehrfach verwendest.

**Comment by alexplusde** [comment]
@TobiasKrais hab dir in Slack geschrieben

**Comment by TobiasKrais** [comment]
@tbaddade: stimmt. Sorry, ich war im falschen Issue: Ich verwende sowohl für die Gebrauchtmaschinen (Paramkey used_machine_id) als auch für die normalen Maschinen (Paramkey machine_id) eine Kategorie mit dem Paramkey category_id, da beides mal auf die selben Kategorien zugeriffen wird.  Die Unterscheidung um welchen Inhalt es sich handelt findet bei mir also im Modul des Artikels statt.

**Comment by TobiasKrais** [comment]
@tbaddade: Frage für die Zukunft dieses Issues: wird es in Zukunft nicht möglich sein, zwei gleiche Paramkeys zu verwenden? Es gibt Paramkeys, wie z.B. category_id, die potentiell mehrere Entwickler in ihren Addons verwenden könnten. Wenn der Paramkey Unique ist, würde das bedeuten, dass das Addon, das als erstes installiert ist den Vorzug bekommt. Nutzt ein weiteres Addon den selben Paramkey kann es nicht verwendet werden. Ist das so geplant?
Bitte schreib kurz zurück, damit ich meine Addons anpassen kann.
