### ISSUE TITLE
URL bei einer Sprache nicht erkannt

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#51]
Wenn nur eine Sprache in Redaxo vorhanden ist, werden die generierten URLs in der pathlist.php mit der clang_id 0 abgespeichert. Es gibt aber keine rex_clang mit dieser ID.

**Comment by tbaddade** [comment]
Diskussion dazu findet hier statt https://github.com/tbaddade/redaxo_url/pull/52
