### ISSUE TITLE
Zweites Feld für SEO-Titel auswählen

### ISSUE THREAD

**Issue by skerbis** [tbaddade/redaxo_url#55]
Beispiel: Ich möchte gerne den SEO-Titel aus Produktname und Kategorie kombinieren.

**Comment by alexplusde** [comment]
@skerbis du könntest übergangsweise ein Index-Feld dafür verwenden, sofern YForm im Einsatz ist.

**Comment by tbaddade** [comment]
>  Ich möchte gerne den SEO-Titel aus Produktname und Kategorie kombinieren.

@skerbis Du willst aus einer Relation ein Feld auswählen oder aus der gewählten Tabelle?

**Comment by skerbis** [comment]
Aus Relation, wenn möglich.  @alexplusde kannst du das genauer erklären?

**Comment by alexplusde** [comment]
@skerbis mit einem Index-Value kannst du aus bestehenden Feldern einen zusammengesetzten Wert bauen. Quasi wie `CONCAT()`

**Comment by skerbis** [comment]
Danke @alexplusde, das löst mein Problem.

**Comment by alexplusde** [comment]
Was auch immer geht, ist, an der Stelle mit einer VIEW zu arbeiten, um ein Feld aus verschiedenen Feldern in Echtzeit zu generieren.
