### ISSUE TITLE
Fehler beim Installieren von 1.0.0-beta5

### ISSUE THREAD

**Issue by tyrant88** [tbaddade/redaxo_url#56]
Hi, ich bekomme folgende Fehlermeldung (Erst-Installation, an zwei Projekten getestet):

AddOn url konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "SHOW COLUMNS FROM `rex_url_generate_url`"! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db130654_7.rex_url_generate_url' doesn't exist

**Comment by tbaddade** [comment]
Die Tabnel sollte noch gar nicht dabei sein. Ist vermutlich durch das Hochladen via Backend passiert. Probier mal bitte die GH Version.

**Comment by tyrant88** [comment]
Yo, klappt. danke.
