### ISSUE TITLE
Pathlist : Umstellung auf Datenbank

### ISSUE THREAD

**Issue by tbaddade** [tbaddade/redaxo_url#58]
Wird bei wachsender Anzahl von Urls sehr träge.

**Comment by nilsology** [comment]
Ist diese Feature bereits in Entwicklung?

**Comment by tbaddade** [comment]
Nein, wird aber demnächst geschehen. Brauche es selber.

**Comment by nilsology** [comment]
Okay super! :)

**Comment by paddle07** [comment]
Hi, weisst ungefähr wann es soweit ist, betreue eine Webseite, wo das Feature langsam aber sicher nötig wäre ;)

**Comment by tbaddade** [comment]
> weisst ungefähr wann es soweit ist

Nein, da kann ich gar keine Auskunft zu geben.

**Comment by alexplusde** [comment]
Kann man hier die Github-Version testen?

**Comment by tbaddade** [comment]
> Kann man hier die Github-Version testen?

Testen gern. Es kann aber sein, dass noch Änderungen passieren. Erste Erfahrungen hat @dtpop gesammelt. Eventuell kann er dazu etwas mehr schreiben.

**Comment by alexplusde** [comment]
Produktiv einsetzbar wäre es allerdings?

**Comment by tbaddade** [comment]
Produktiv würde ich es noch nicht einsetzen.
