### ISSUE TITLE
trailing Slash

### ISSUE THREAD

**Issue by nilsology** [tbaddade/redaxo_url#61]
@tbaddade Gibt es eine Möglichkeit Trailing Slash zu entfernen? Brauche das dringend für ein Projekt, da sonst alte URLs kaputt gehen.

**Comment by tbaddade** [comment]
Probier mal ein eigenes YRewrite Scheme zu registrieren und das $suffix leer zu lassen

Siehe
https://github.com/yakamara/redaxo_yrewrite/blob/master/lib/scheme.php#L13

**Comment by nilsology** [comment]
Hat funktioniert Danke! :) Ggf. sollte man das nochmal wo mit Hinweis dokumentieren.
https://github.com/FriendsOfREDAXO/tricks/blob/master/addons_yrewrite_url_schemes.md
