### ISSUE TITLE
Probleme bei URLs mit Relationen

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#64]
Wir hatten heute bei einer Website den Fall, dass die generierten URLs des Schemas `/artikel/relation/datensatz/` nicht funktioniert haben:

* Im Frontend wurde `/artikel/relation/datensatz/` ausgegeben
* Diese URLs können korrekt aufgerufen werden (`/artikel/)`, jedoch ohne Treffer in `URLGenerator::getId();`
* Dadurch ist auch die ID des Datensatzes nicht bekannt und man kann nichts ausgeben.
* In der sitemap.xml wurden viel zu viele URLs generiert, sowohl `/artikel/relation/datensatz/` als auch `/artikel/datensatz/relation/`

Bei Bedarf können ich / @pixelpaul dir Zugang zur betroffenen Installation geben.

**Comment by tbaddade** [comment]
Welche Version vom Addon ist im Einsatz?
Kannst du mir die pathlist und alle angelegten Profile als Export geben? Ggf. auch die Tabellen mit den verwendeten Felder im Profil. Ansonsten lege ich mir die Tabellen Lokal an. So zumindest könnte ich mit den Daten/ Profile besser experimentieren.

**Comment by alexplusde** [comment]
Aktuelle Installer-Version. Rest bereite ich dir die Woche auf...

**Comment by alexplusde** [comment]
Ich kann dieses Verhalten nicht mehr in der betroffenen Installation nachstellen.
