### ISSUE TITLE
Custom Rewriter wird ohne clang Parameter aufgerufen

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#67]
Ich muss bei mir leider einen eigenen Rewriter einsetzen, da YRewrite keine Chinesischen oder Russischen URLs produzieren kann (https://github.com/yakamara/redaxo_yrewrite/issues/170).

Das habe ich jetzt programmiert: https://github.com/TobiasKrais/d2u_helper/blob/master/lib/d2u_yrewrite_scheme.php#L12. Er funktioniert auch wunderbar mit YRewrite und den Redaxo Artikeln. So kann ich "normale" und Chinesische / Russische URLs generieren.

Das Problem: das URL Addon spielt nicht mit. Alle URLs, die mit dem URL Addon generiert werden, funktionieren nicht.

Interessant ist, dass in der Zeile (https://github.com/TobiasKrais/d2u_helper/blob/master/lib/d2u_yrewrite_scheme.php#L12) `$clang` den Wert 0 hat, egal welche Sprache ausgegeben wird. Wenn YRewrite einen String mit dieser Methode für einen Artikel normalisieren lässt, stimmt der Wert in `$clang` mit der Sprache überein. Wenn aber das URL Addon dies tut ist `$clang = 0` und mein Rewriter Schema kann nicht ausgeführt werden.

Wie kann ich nun chinesische URLs generieren?

**Comment by tbaddade** [comment]
Clang = 0 existiert nicht mehr in REDAXO 5. In deiner Methode steht der Wert von $clang auf 0, in der Elternklasse steht dieser auf 1.

Das hat aber nichts mit dem generieren der Urls an sich zu tun, da das AddOn die Sprach Id nicht an die normalize Klasse übergibt. Es nutzt die Methode nur, um die Pfade zu normalisieren. D.h. innerhalb der Methode kannst du nicht auf $clang gehen. Deshalb ist bei dir der Wert immer 0.

**Comment by TobiasKrais** [comment]
OK, das mit der clang ist nur eine Spur. Die eigentliche Frage ist: Warum kann das URL Addon keine Chinesischen und Russischen, ... URLs generieren, bzw. damit umgehen?

**Comment by tbaddade** [comment]
Die Urls werden nicht einmal generiert? Wenn doch, aber der Datensatz erscheint nicht dann schau mal was dir das hier liefert

```
dump(Url::current());
```

Sollte das nichts liefern dann debug mal diese Methode
https://github.com/tbaddade/redaxo_url/blob/1.0/lib/Url/Url.php#L653

**Comment by TobiasKrais** [comment]
Wenn ich mein Rewriter Scheme aktiviert habe kommt bei `dump(Url::current());` folgendes heraus:
`Url {#103 ▼
    #original_url: "http://localhost:80/~tobias/www.kaltenbach.com/zh/%E4%BA%A7%E5%93%81/%E8%AE%BE%E5%A4%87/kps-a-167/"
    #scheme: "http"
    #user: null
    #pass: null
    #host: "localhost"
    #port: 80
    #path: "/~tobias/www.kaltenbach.com/zh/%E4%BA%A7%E5%93%81/%E8%AE%BE%E5%A4%87/kps-a-167/"
    #query: null
    #fragment: null
    #query_array: []
}`
Ausgegeben wird aber ein 404 Fehler.

Ohne meinen Rewriter werden die URLs nicht mal gefunden, da sieht die URL so aus: http://localhost:80/~tobias/www.kaltenbach.com/zh///kps-a-167/

**Comment by tbaddade** [comment]
Ich gehe mal davon aus, dass die Url bereits so vom Url-Addon geliefert wird, also im Frontend ausgegeben wird. Soll heißen, dass die Url nur falsch erstellt wird.

Ist das hier deine gewünschte Url oder sollten da eher normale Zeichen kommen?
`/%E4%BA%A7%E5%93%81/%E8%AE%BE%E5%A4%87/kps-a-167/`

Schau mal warum iconv bei dir nur leere Zeichen zurückgibt.

PS: Kannst du mir mal paar russische und chinesische Wörter hier geben. Dann kann ich selbst ein wenig testen.

**Comment by TobiasKrais** [comment]
Hier ein paar Chinesische Schriftzeichen: 高效冲压剪切设备用于角钢至大小  高效冲压剪切设备用于角钢至大小 . Auf dieser URL gibt es mehr davon https://www.kaltenbach.com/zh/. Diese Seite stelle ich gerade auf Redaxo 5 um.

**Comment by tbaddade** [comment]
Und was erwartest du jetzt für eine Url?

Auf der Website sind die Urls mit Chinesisch und Englisch gemischt.

1. Was liegt in der Datenbank für ein Name
1. Wie soll die Url mit diesem Namen aussehen
1. Wird die generierte Url im Frontend bereits gefunden und richtig verlinkt 
`rex_getUrl('', '', ['namespace' => $id]))`
1. wenn du auf den Link klickst, welche Url erscheint im Browser und was kommt bei  `dump(Url::current())`
1. liefert die Methode `getId()` die korrekte Id zum Datensatz

**Comment by TobiasKrais** [comment]
Zu 1.: Folgender Name einer Maschinenkategorie liegt in der DB: 带锯切割机床
Zu 2.: Die URL sollte so aussehen /zh/%E4%BA%A7%E5%93%81/%E8%AE%BE%E5%A4%87/%E5%B8%A6%E9%94%AF%E5%88%87%E5%89%B2%E6%9C%BA%E5%BA%8A/ (= /zh/产品/设备/带锯切割机床/)
Zu 3.: Nein. Die URL, die im Frontend ausgegeben wird ist diese: /zh/%E4%BA%A7%E5%93%81/%E8%AE%BE%E5%A4%87/ (= /zh/产品/设备/)
Zu 4.:  Auch die falsche URL /zh/%E4%BA%A7%E5%93%81/%E8%AE%BE%E5%A4%87/
Zu 5.: Nein. Die ID ist leer.

**Comment by TobiasKrais** [comment]
Noch als Info. Hier der betreffende Eintrag in der pathlist:  [url] => `/zh/产品/设备/`

**Comment by TobiasKrais** [comment]
Hab eine Lösung gefunden.

- Schritt 1: der obige commit decodiert urlencodierte URLs mit Sonderzeichen in URLs

- Schritt 2: In meinem Rewriter Schema (https://github.com/TobiasKrais/d2u_helper/blob/47ba446ee039ed003553994d385faa06fd3cae34/lib/d2u_yrewrite_scheme.php#L22) habe ich statt der einfachen Sprachprüfung eine weitere Prüfung hinzugefügt. Wenn das Standard Schema keine vernünftige URL ausgibt springt mein Schema ein.

Daraus ergibt sich für mich nur eine Konsequenz - eben doch die `$clang_id` zu übergeben. Als Begründung hier die offizielle Empfehlung für mein Rewriter Schema: https://github.com/yakamara/redaxo_yrewrite/issues/170. Diese offizielle Empfehlung kann ich im Umgang mit dem URL Addon nicht umsetzen, da die `$clang_id` für die `normalize()` Funktion nicht übergeben wird.

**Comment by tbaddade** [comment]
Die Url wird ja scheinbar korrekt normalisiert. Es fehlt aber die Kategorie die nicht am Ende angehangen wird.

**Comment by TobiasKrais** [comment]
Das ist auch logisch. Für die URL steht mir eine korrekt übergebene `$clang_id` zur Verfügung. Nur der Teil, der aus dem URL Addon generiert wird übergibt die `$clang_id` nicht und normalisiert alle chinesischen Zeichen weg. Und wenn der normalisiert String leer ist wird auch nichts angehängt.

Das sieht man ganz deutlich wenn auf die Kategorie eine Maschine mit Zahlen im Namen folgt. Dann sieht das Ergebnis so aus:

- Englisch: /en/products/machines/punching-shearing-systems/myname-167/

- Chinesisch: /zh/产品/设备/167/

**Comment by TobiasKrais** [comment]
Hier der PR für Version 2 https://github.com/tbaddade/redaxo_url/pull/153

**Comment by TobiasKrais** [comment]
Danke fürs mergen. Issue ist damit gelöst. Danke!
