### ISSUE TITLE
Gibt es $urlSeo->getCanonicalTag() nicht mehr?

### ISSUE THREAD

**Issue by olien** [tbaddade/redaxo_url#69]
```
   $urlSeo = new UrlSeo();
   echo $urlSeo->getCanonicalTag();
```

Es wird nach dem Update auf die aktuelle Version folgende Fehler ausgegeben:
**“Call to undefined method Url\Seo::getCanonicalTag()”**

`getCanonicalUrlTag` funktioniert.

LG
Oliver

**Comment by tbaddade** [comment]
Kam mit diesem PR rein https://github.com/tbaddade/redaxo_url/pull/28

**Comment by TobiasKrais** [comment]
Methode nennt sich jetzt `Url\Seo::getCanonicalUrlTag()`. Der Issue könnte doch geschlossen werden, oder?
