### ISSUE TITLE
Fehler bei URL-Generierung

### ISSUE THREAD

**Issue by NGWNGW** [tbaddade/redaxo_url#7]
Hallo, 

ich versuche gerade das Addon in Verbindung mit YRewrite/YForm zum laufen zu bekommen. Folgendes Problem habe ich:

Ich erzeuge die Links folgendermaßen:

`rex_getUrl(5, 1, ['id' => $this->attributes['id']]);`

5 ist die Artikel ID die ich im URL Addon entsprechend zugewiesen habe, $this->attributes['id'] der gewünschte Datensatz.

Die generierten Links beginnen nun jedoch alle mit "://:80".

Die Redaxo-Installation läuft auf einer Subdomain. Muss ich hier noch etwas beachten?

**Comment by NGWNGW** [comment]
Ich habe nun eine separate 404 Seite angelegt und diese bei yRewrite entsprechend angegeben. Zusätzlich ist der Startartikel nun vom Status "offline" auf "online" gestellt worden.

Seitdem habe ich das Problem nicht mehr. Ich kann aber nicht wirklich einen Zusammenhang feststellen und kann den Fehler auch nicht reproduzieren. Seltsam.

**Comment by tbaddade** [comment]
Sollte mit https://github.com/tbaddade/redaxo_url/commit/3dfcb6b9b792ab26c4caee2370435babd9e1f558 behoben sein. Ansonsten gern wieder das Issue öffnen
