### ISSUE TITLE
Trailing Slash Umleitung

### ISSUE THREAD

**Issue by marcohanke** [tbaddade/redaxo_url#70]
Bin gerade eine halbe Stunde verzweifelt weil ich immer einen 404 bekommen habe beim Aufruf der URL, bis ich gemerkt habe dass der Trailing Slash fehlt. Der Rest der Seite leitet ohne Trailingslash schön um auf die URL mit dem TrailingSlash. Kann das dass URL Addon auch abdecken? Oder muss ich da yrewrite verbiegen bzw. wenn wäre es ja schön, wenn die genrierten Urls genauso behandelt werden würden wie die restlichen.

**Comment by tbaddade** [comment]
Das Addon bekommt die URL und das Suffix von yrewrite. Das bei dir der Slash fehlt, könnte somit an einer eingetragenen CustomUrl beim Artikel oder am eigenen yrewrite Scheme, welches kein Suffix hat, liegen.

**Comment by marcohanke** [comment]
Komisch, ich hab’ keine Benutzerdefinierte Url hinterlegt und auch kein eigenes Schema …

**Comment by marcohanke** [comment]
Über Sinn und unsinn von falschen Urlausgaben lässt sich streiten. Trotzdem wäre es schön wenn es auf der gesamten Website einheitlich wäre ...

**Comment by tbaddade** [comment]
Hinweis: Die Url wurde nicht falsch ausgegeben sondern falsch im Browser eingegeben (ohne / am Ende). YRewrite versucht auch falsch eingegebene Urls aufzulösen und leitet ggf. via 301 auf die korrekte Url weiter.
Das Url-AddOn schaut nur nach der tatsächlich eingegebenen Url und liefert bei Erfolg die Infos an YRewrite. Bei falschen Urls wird dann nicht ermittelt und es müsste der 404 Artikel erscheinen.

**Comment by fietstouring** [comment]
YRewrite leitet eine URL ohne trailing Slash auf die mit weiter, könnte URL das nicht auch tun?

**Comment by TobiasKrais** [comment]
Problem: eine URL mit Parametern macht Probleme:
https://www.kaltenbach.com/de/unternehmen/karriere/stellenangebote/berufserfahrene/softwareentwickler-8211-schwerpunkt-pc-m-w-d-11463 sollte auf https://www.kaltenbach.com/de/unternehmen/karriere/stellenangebote/berufserfahrene/softwareentwickler-8211-schwerpunkt-pc-m-w-d-11463/ weiterleiten. Das funktioniert korrekt. Aber was passiert, wenn die URL einen Parameter hat, wie hier im Beispiel: https://www.kaltenbach.com/de/unternehmen/karriere/stellenangebote/berufserfahrene/softwareentwickler-8211-schwerpunkt-pc-m-w-d-11463?x=y. Dann wird auf die URL https://www.kaltenbach.com/de/unternehmen/karriere/stellenangebote/berufserfahrene/softwareentwickler-8211-schwerpunkt-pc-m-w-d-11463/x=y/ weitergeleitet.

**Comment by TobiasKrais** [comment]
Hmm. Im bestehenden Code wird außerdem die sitemap.xml auf sitemap.xml/ umgeleitet :-(
