### ISSUE TITLE
Mehr Einfluss auf den Titel

### ISSUE THREAD

**Issue by marcohanke** [tbaddade/redaxo_url#71]
Der Titel besteht im Moment aus Titel - Name des Artikels / Servername. Der Servername wird über yrewrite kontrolliert, auf "Name des Artikels" hätte ich auch gerne Einfluss um wirklich schöne SEO-Titel zu erstellen

**Comment by tbaddade** [comment]
> "Name des Artikels" hätte ich auch gerne Einfluss

wenn du diesen ändern willst, ändere den Artikelnamen. Ich dachte diesen wolltest du gar nicht erst ausgeben lassen.

**Comment by marcohanke** [comment]
Vielleicht falsch beschrieben, ich hätte gerne Einfluss darauf um ihn zu löschen ;-) Ich würde den gesamten Titel gerne selber steuern.

**Comment by alexplusde** [comment]
Du könntest im Template darauf reagieren und ein eigenes Schema für diese Fälle definieren.

**Comment by tbaddade** [comment]
Der Titel Tag kann jetzt über den EP `URL_SEO_TAGS` angepasst werden.
