### ISSUE TITLE
Produkturl ohne Artikel

### ISSUE THREAD

**Issue by marcohanke** [tbaddade/redaxo_url#72]
Ich würde gerne die URLs als doamin.de/seo-url ausgeben, also ohne den Artikel dazwischen.

**Comment by TobiasKrais** [comment]
Gib einfach den Startartikel an. So mach ich das.

**Comment by tbaddade** [comment]
Abfrage ob der Artikel im Pfad aufgenommen wird. 

- Sollte das nur für den Artikel gelten?
- Was sollte mit den Kategorien im Pfad passieren?
- Wer prüft auf doppelte Urls, kann durch andere Kategorien/Artikel innerhalb der Struktur passieren?

**Comment by TobiasKrais** [comment]
Marco möchte wahrscheinlich nicht nur den Artikel, sondern auch die Kategorien aus dem Pfad weg haben. Unser SEO Berater hat uns das auch vor kurzem so empfohlen, da Google gerade auf kurze, ausdrucksstarke URLs steht. Die Idee der Abfrage ist ein praktischer Vorschlag.

Die Prüfung auf doppelte URLs würde ich dem Kunden überlassen. Ich geht hier auf Nummer sicher, indem ich eine ID in die URL mit aufnehme, wenn ich ein Risiko von doppelten Datensätzen sehe. Das URL Addon liefert einfach den ersten Treffer aus.

**Comment by marcohanke** [comment]
Puh, lange her hier. Aber es ist wie Tobias sagt. domain.de/hauptkategorie/unterkategorie/variante/Produkt ist doof. domain.de/produkt ist cool.

**Comment by alexplusde** [comment]
Ihr könnt eine View erstellen aus allen Datensätzen, die ihr als URL haben wollt, und diese dann als ein einziges Profil über das URL-Addon laufen lassen. Das sehe ich persönlich als flexibler an und nimmt Komplexität aus dem URL-Addon heraus.

**Comment by alexplusde** [comment]
das Ganze dann in der README/Doku veröffentlichen. Falls jemand nicht weiter kommt, Bitte Bescheid sagen.

**Comment by TobiasKrais** [comment]
Von einem Kunden habe ich den Auftrag erhalten, bei einem Projekt alle Artikel und Kategorien aus der URL zu entfernen und nur die SEO-URL auszugeben. Außerdem sollen die alten URLs mit Artikeln und Kategorien auf die neuen weitergeleitet werden. Es gibt mehrere Wege das zu lösen:
a) Ich programmiere eine Option wie in diesem Issue gewünscht und mit dazu eine automatische 301 Weiterleitung der URLs mit Artikel und Kategorienamen.
b) Ich programmiere eine Lösung für mein Addon.

Ich bevorzuge Lösung a). Dann profitieren alle. @tbaddade: besteht daran grundsätzlich Interesse?

**Comment by alexplusde** [comment]
c) ein YRewrite-Schema nutzen

**Comment by TobiasKrais** [comment]
@alexplusde: Hilf mit auf die Sprünge: wie soll das funktionieren?

**Comment by tbaddade** [comment]
@TobiasKrais 

Was hindert dich daran eine View für diese Urls zu nutzen?

Weiterleitungen gehören für mich zu YRewrite. Dort müsste es eine API geben um automatisch Weiterleitungen zu registrieren.

**Comment by alexplusde** [comment]
@TobiasKrais vielleicht schreiben wir auch aneinander vorbei. Aber URLs des Schemas `domain.de/mein-datensatz/` gehen doch entweder auch ohne URL über ein eigenes Schema, oder wie @tbaddade gerade vorbringt über eine VIEW.

**Comment by TobiasKrais** [comment]
@tbaddade Was meinst du mit VIEWs für die URL zu nutzen?
@tbaddade Das habe ich auch schon gedacht, dass die Weiterleitung zu YRewrite gehört. Dort könnte ich die URLs in die Weiterleitungstabelle eintragen. Die Frage ist, von wo aus die Tabelle befüllt wird. Von jedem meiner Addons aus? Das bedeutet mehrfache Arbeit. Zentral wäre es, wenn ich an der Quelle ansetze, im URL Addon.
@alexplusde Ich verstehe noch nicht ganz wie das funktioniert. Vielleicht fehlt mir das Wissen. Mir ist nicht klar, wie ich deinen Vorschlag mit einem Schema zu arbeiten umsetze:
- Das URL Profil des Addon a) soll die kurzen URLs bekommen
- Das URL Profil des Addon b) soll die ungekürzten URLs bekommen
- Die Artikel sollen ebenfalls die ungekürzten URLs bekommen

Meine Beweggründe das im URL Addon anzusiedeln sind:
- Zentrale, Addon übergreifende Verwaltung an einer Stelle
- Benutzerfreundlichkeit
- Logischer Zusammenhang, da hier die URLs entstehen

**Comment by alexplusde** [comment]
@TobiasKrais melde dich Mal im Slack-Channel und schildere noch Mal ganz genau, was du eigentlich machen willst, mit konkreten URLs

**Comment by IngoWinter** [comment]
@TobiasKrais kannst du nicht im Url Addon einen neuen Eintrag erstellen, der als Artikel die Startseite hat und als Url Produktnamen + Id? Den bisherigen Eintrag mit der langen URL lässt du einfach drin und machst den Redirect über das Template/Modul, was bisher das Produkt ausgibt.

**Comment by TobiasKrais** [comment]
Wäre denkbar, aber nicht komfortabel. Schau dir mal die Startseite an: https://www.kaltenbach.com/de/. Da gibt es schon anderen Inhalt, der ausgeblendet werden müsste. Ich finde die Idee von @marcohanke  für den Benutzer die komfortabelste Lösung.

**Comment by tbaddade** [comment]
Das Einfachste was ich hier sehe, dass man sich an diesen EP[1] hängt und dort die Url selber beeinflusst. Der Artikel wäre dann immer noch ein Detailartikel und müsste nicht der Startartikel sein.

[1] https://github.com/tbaddade/redaxo_url/blob/master/lib/Url/Profile.php#L368

**Comment by IngoWinter** [comment]
Und die Redirects kloppst du einfach in die .htaccess. Boom, Problem gelöst :collision:

**Comment by TobiasKrais** [comment]
Das wäre eine praktikable Lösung. In den Einstellungen meines Addons könnte ich eine Option "URLs verkürzen" anbieten. Dann beim generieren der URL im EP einklinken und mit der dort ankommenden URL eine Weiterleitung in YRewrite einrichten. Ich schlaf mal drüber. Fürs erste überzeugt mich das.

**Comment by tbaddade** [comment]
> Und die Redirects kloppst du einfach in die .htaccess. Boom, Problem gelöst

Um Redirects kümmert sich das AddOn nicht … Das wäre Aufgabe von YRewrite. Über den EP kann man den Redirect dann direkt an YRewrite übergeben. Die alte Url ist ja im EP bekannt und wird zur neuen angepasst.

**Comment by tbaddade** [comment]
> In den Einstellungen meines Addons könnte ich eine Option "URLs verkürzen" anbieten.

Da musst du aufpassen, wenn du mehrere Configs hast. es könnten dann mehrfach dieselben Urls entstehen. Spätestens beim speichern wird dann ein Whoopi auftauchen.

**Comment by TobiasKrais** [comment]
@marcohanke Eigentlich könnten wir den Issue doch schließen, oder?

**Comment by marcohanke** [comment]
Von mir aus gerne. Wenn ich's wieder brauche, lass' ich mir von @alexplusde erklären wie das mit den Views geht ;-)

**Comment by TobiasKrais** [comment]
Ich werden Beispielcode für den EP programmieren und hier verlinken. Machst du den Issue zu?

**Comment by TobiasKrais** [comment]
Hier das versprochene Codebeispiel als PR für die Doku: https://github.com/tbaddade/redaxo_url/pull/139

**Comment by TobiasKrais** [comment]
Ich sehe gerade, dass mein Codebeispiel ein Problem hat: wenn der Artikelname aus der URL herausgekürzt wird, wird die Bedingung aus dieser Zeile https://github.com/tbaddade/redaxo_url/blob/91edd6756644fd02859177f93969b98e286b0cdd/lib/Url/UrlManager.php#L270 nie erfüllt und die verkürzte URL kann nicht mehr aufgelöst werden. Siehe dazu die Lösung hier: https://github.com/tbaddade/redaxo_url/issues/124#issuecomment-505372831

**Comment by TobiasKrais** [comment]
@marcohanke: Ich glaube der Issue sollte wieder geöffnet werden.

**Comment by TobiasKrais** [comment]
Danke @tbaddade! Wie könnte hier eine Lösung aussehen? Man könnte folgende Zeilen schlicht entfernen:
https://github.com/tbaddade/redaxo_url/blob/91edd6756644fd02859177f93969b98e286b0cdd/lib/Url/UrlManager.php#L265-L278

Soll ich einen PR erstellen?

**Comment by tbaddade** [comment]
> Soll ich einen PR erstellen?

Diese Zeilen sind wichtig und [sollten nicht gelöscht werden](https://github.com/tbaddade/redaxo_url/pull/147#discussion_r296660839). Ich muss nur eine Lösung für obiges Problem finden.

**Comment by TobiasKrais** [comment]
Dieser Issue ist in der aktuellen Git Version behoben, da dieser Fehler (https://github.com/tbaddade/redaxo_url/issues/124) behoben wurde. Der Issue kann geschlossen werden.
