### ISSUE TITLE
Infos zum Debuggen (später für Doku)

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_url#75]
Wie kann man 404-Fehler debuggen?

Szenario:
Ich habe eine Redaxo-Website mit einem URL-Schema, basierend auf `rex_media_category`. Der Ziel-Artikel des URL-Schemas ist vorhanden und online. URLs werden im Frontend korrekt ausgegeben, also `/urlschema-artikel/urlschema-datensatz-name/`. Beim Klick darauf erfolgt jedoch ein 404-Fehler. 

* Cache löschen
* URL-Schema erneut speichern
* Pathlist anschauen und ggf. löschen:  `/redaxo/cache/addons/yrewrite/pathlist.json` `/redaxo/cache/addons/url/pathlist.php` - was müssen die beiden Dateien jeweils beinhalten?
* Weitere Schritte?

Da es um eine Website von `@xbluex` in Slack geht, könntest du @tbaddade vlt. weiterhelfen?

**Comment by tbaddade** [comment]
> Wie kann man 404-Fehler debuggen?

wenn der 404 Artikel auftaucht, dann wird kein Struktur Artikel für die angegebene Url gefunden.

`/redaxo/cache/addons/url/pathlist.php`

Ich nutze dafür die App **VisualJson**. Mit der APP kann man die Pathlist sehr gut durchgehen. Ähnlich wie `dump()` bei REDAXO.

**Comment by alexplusde** [comment]
Weiter zum Debuggen:
* Prüfen der Konfiguration von YRewrite: Ist die Domain korrekt und wurden separate Artikel für die Startseite und den 404 angelegt und verknüpft.
