### ISSUE TITLE
URLs in Redaxo Linkliste-Dialog mit aufnehmen

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#76]
Es wäre super, wenn man Datensätze, die eine URL generieren, in der Linkliste auswählen kann.

**Comment by tbaddade** [comment]
Feine Idee … Wenn es sich um YForm Datensätze handelt, wäre das auch jetzt schon möglich. Da gibt es Widget für.

**Comment by fietstouring** [comment]
Was für ein Widget ist da gemeint?

**Comment by tbaddade** [comment]
> Was für ein Widget ist da gemeint?

Siehe hier https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/var_yform_dataset.php#L4-L7

**Comment by fietstouring** [comment]
Vielen Dank, das funktioniert ja prächtig. Habe aber nirgends jemals davon gelesen, kann es sein dass das nicht dokumentiert ist oder hab ichs nur übersehen?

**Comment by fietstouring** [comment]
Und wurde das schon mal in einen der Text-Editoren eingebaut?

**Comment by tbaddade** [comment]
> Und wurde das schon mal in einen der Text-Editoren eingebaut?

Der [Redactor](https://github.com/FriendsOfREDAXO/redactor) wird etwas mitbringen. Wie es bei anderen Editoren ist weiß ich nicht.

**Comment by fietstouring** [comment]
Danke!

**Comment by tbaddade** [comment]
Ich schließe hier einmal, da die Auswahl der Datensätze über YForm mir sinnvoller erscheint.
