### ISSUE TITLE
Feature-Wunsch: generierte Pathlist je URL-Schema im Backend anzeigen

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#77]
Erleichtert das Debuggen und auch das Prüfen/Überfliegen der gewonnenen URLs:
* "Sind alle URLs vorhanden, die ich benötige?"
* "Werden URLs in der Pathlist generiert, die ich per Konfiguration ausschließen wollte?"

siehe auch: https://github.com/tbaddade/redaxo_url/issues/75

**Comment by tbaddade** [comment]
Das wird kommen. Habe ich auch schon oft vermisst, grad wen man ich Support leisten musste. Der Umweg über die pathlist kopieren etc. ist recht aufwendig.

**Comment by tbaddade** [comment]
generierte Urls werden auf einer Subpage angezeigt
