### ISSUE TITLE
In den Profilen zugewiesene Artikel vorm löschen schützen

### ISSUE THREAD

**Issue by tbaddade** [tbaddade/redaxo_url#78]
siehe aktuelles Projekt "fi.....s". Da werden Kategorien vorm löschen bzw. umwandeln zu normalen Artikeln geschützt.

Entsprechende Meldung in der Struktur anzeigen. Ähnlich wie `MEDIA_IN_USE`

**Comment by tbaddade** [comment]
close via 21d21d8d56909e6b8a76548a257527a4b41b899c

**Comment by TobiasKrais** [comment]
Ich glaube hier geht was schief. Schau mal auf der Testseite. Folgende Artikel IDs werden in Profilen der url Addons verwendet: 302, 1, 625 und 744. Bei diesen Artikeln ist das Löschen Button korrekt ausgegraut. Was läuft schief?
- Bei weiteren Artikeln wird das Löschen Button ausgegraut. Beispiele: 1026, 1057, 1074, 1023, 1062, 10
- Die Artikel lassen sich trotzdem löschen, wenn man sich die URL dazu selbst bastelt. Hier sollte man das Löschen über den EP "ART_PRE_DELETED" verhindern. (Codebeispiel hier: https://github.com/TobiasKrais/d2u_machinery/blob/ccffc473bf3f25f27261bcce6aba53e85071caef/boot.php#L10)

**Comment by TobiasKrais** [comment]
Vielleicht wäre es generell besser eine Fehlermeldung beim Löschvorgang zu bringen als das Löschen Button auszugrauen. Zwar finde ich das ausgrauen sehr elegant, aber bei einer Fehlermeldung kann man dem Nutzer mitteilen, warum er den Artikel nicht löschen kann und was somit vorher zu tun wäre.

**Comment by tbaddade** [comment]
Auch eine Fehlermeldung erscheint, wenn man eine korrekte Url nutzt.

https://github.com/tbaddade/redaxo_url/blob/21d21d8d56909e6b8a76548a257527a4b41b899c/boot.php#L67

Den Part werde ich aber noch mal überarbeiten müssen.

**Comment by TobiasKrais** [comment]
>     * Die Artikel lassen sich trotzdem löschen, wenn man sich die URL dazu selbst bastelt. Hier sollte man das Löschen über den EP "ART_PRE_DELETED" verhindern. (Codebeispiel hier: https://github.com/TobiasKrais/d2u_machinery/blob/ccffc473bf3f25f27261bcce6aba53e85071caef/boot.php#L10)

Das ist nicht ganz korrekt: es können über die gebastelte URL nur Artikel gelöscht werden, bei denen fälschlicherweise das Löschen Button ausgegraut wird. Wird es zu recht ausgegraut und die URL mit der Artikel ID gebastelt, kommt die Meldung, dass das URL Addon noch den Artikel verwendet - also so wie es sein soll.

**Comment by TobiasKrais** [comment]
Mein Fix fügt behebt das komplette Problem. Der Fix wird auf der dir bekannten Testseite von mir verwendet.

**Comment by tbaddade** [comment]
> Mein Fix fügt behebt das komplette Problem.

Danke dir
