### ISSUE TITLE
CSRF beachten wenn nötig

### ISSUE THREAD

**Issue by dergel** [tbaddade/redaxo_url#79]

**Comment by alexplusde** [comment]
Es geht ja im Wesentlichen darum, manipulierte Anfragen zu verhindern. rex_form kann damit doch inzwischen von Haus aus umgehen, muss man hier nur beim Profil-bearbeiten-Dialog einen CSRF-Token ergänzen?

**Comment by tbaddade** [comment]
Ich schließe mal … wenn noch etwas gefunden wird gern wieder öffnen

**Comment by alexplusde** [comment]
So wie's aussieht, ist es ja bereits drin für `delete` und `refresh`. Damit sollte es passen!
