### ISSUE TITLE
URL-Bezeichner vertauscht

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#8]
![image](https://cloud.githubusercontent.com/assets/3855487/16197113/14511fe2-3701-11e6-8af5-c756f90e97e3.png)

"zus. Pfade" und "Einschränkung" sind verkehrt zugeordnet.

**Comment by tbaddade** [comment]
close via https://github.com/tbaddade/redaxo_url/commit/3dfcb6b9b792ab26c4caee2370435babd9e1f558
