### ISSUE TITLE
Wunsch: Link-Picker-Widget

### ISSUE THREAD

**Issue by skerbis** [tbaddade/redaxo_url#87]

**Comment by tbaddade** [comment]
Kannst du es bitte genauer beschreiben?

**Comment by skerbis** [comment]
Die links die per url addon erzeugt werden in einer Linkmap darstellen, damit man sie ggf. in Modulen picken kann

**Comment by skerbis** [comment]
bzw. wie komme ich an eine Liste der durch das AddOn erstellten URLs mit Titel? ... Dann könnte ich eine Lösung für Quick Navigation realisieren, wie ich es kürzlich mit den zuletzt geänderten Artikeln gemacht habe.

**Comment by tbaddade** [comment]
Ich mache es meist anders. Beispiel Verlinkungen im Redactor. Dort lasse ich nach Klick auf einen Button (ähnlich Linkmap) im Popup die Liste der Datensätze via "YFORM_TABLE_DATA" Widget anzeigen. Das HTML sieht dann nach dem insert in das Textfeld so aus: 

`<a href="yakamara-addon://2">AddOn Title</a>` 

Diese Links (ähnlich wie `redaxo://2`) lasse ich dann via `OUTPUT_FILTER` entsprechend parsen und ersetzen.


```
public static function replaceLinks(\rex_extension_point $ep)
    {
        return preg_replace_callback(
            '@(yakamara-(addon|user))://(\d+)(?:-(\d+))?/?@i',
            function ($matches) {
                $url = '';
                switch ($matches[1]) {
                    case 'yakamara-addon':
                        $object = AddOn::get($matches[3]);
                        if ($object) {
                            $url = $object->getUrl();
                        }
                        break;
                    case 'yakamara-user':
                        $object = User::get($matches[3]);
                        if ($object) {
                            $url = $object->getUrl();
                        }
                        break;
                }
                return $url;
            },
            $ep->getSubject()
        );
    }
```

Die `getUrl` Methoden der Objekte (`class AddOn extends \rex_yform_manager_dataset`) besitzen diesen Code

```
    public function getUrl($urlParams = [])
    {
        return rex_getUrl('', '', array_merge(['addon-id' => $this->id], $urlParams));
    }
```

Die Urls aus dem Url-AddOn entstehen somit erst ganz am Schluss der tatsächlichen Ausgabe.

**Comment by skerbis** [comment]
Dann mache ich hier dicht. Danke, das hat mir geholfen.

**Comment by tbaddade** [comment]
Es wird ggf. mit der neuen Version einfacher. Die basiert auf DB-Tabellen und nicht auf eine einzelne physische Datei.
