### ISSUE TITLE
Redaxo > 5.6: Views werden nicht mehr als Tabelle zur Auswahl gestellt

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_url#88]
Ab Redaxo 5.6 werden nur noch echte Tabellen und keine VIEWs mehr zur Auswahl angezeigt.

**Comment by TobiasKrais** [comment]
Ursache: https://github.com/redaxo/redaxo/commit/c3b1ddeb60e8c4de85b4b8b4c3c07f1bb90a7b52#diff-043c74c6dcb9f93bd03809b49467087c

**Comment by TobiasKrais** [comment]
Hab auch bei Redaxo noch einen Issue aufgemacht: https://github.com/redaxo/redaxo/issues/1870

**Comment by alexplusde** [comment]
Hier muss dann, Stand aktuell, eine neue Methode zum Einsatz kommen. PR welcome.

**Comment by TobiasKrais** [comment]
Die Versionsabhänigkeit zur nächsten Redaxo Version müsste noch in der package.yml angepasst.

**Comment by tbaddade** [comment]
Warten wir erst einmal ab, welche Methoden definitiv in die nächste Core Version kommen.

**Comment by TobiasKrais** [comment]
Funktioniert in der aktuellen Redaxo Version sowohl mit URL 1.x, als auch 2.x wieder. Deshalb schließe ich den Issue.
