### ISSUE TITLE
Canonical-URL und hreflang-URL in yRewrite aktualisieren

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#9]
Wenn ich mich in `www.website.net/artikel/url-titel/` befinde, sollte yRewrite die aktuelle URL ausgeben und nicht den Container-Artikel `www.website.de/artikel/`

Gleiches gilt für generierte URLs, die unterschiedliche Sprachen haben. Wenn ich in 
`www.website.net/de/artikel/url-titel/` bin, sollte der hreflang-Eintrag von yRewrite `www.website.net/en/article/url-title/` ausgeben.

**Comment by tbaddade** [comment]
So weit ich das sehe, kann ich das aktuell nicht beeinflussen, da es keinen EP oder eine Api gibt.

> Wenn ich in 
> www.website.net/de/artikel/url-titel/ bin, sollte der hreflang-Eintrag von yRewrite www.website.net/en/article/url-title/ ausgeben.

Aktuell gibt yrewrite nur `www.website.net/en/` bzw. immer die Url der Startseite aus.
https://github.com/yakamara/redaxo_yrewrite/blob/master/lib/seo.php#L109

**Comment by alexplusde** [comment]
Das dachte ich mir schon. In meinen Projekten hat das jetzt auch keine Priorität, dennoch wollte ich darauf aufmerksam machen, sodass vlt. spätere Versionen der von yRewrite und URL das berücksichtigen können.

**Comment by tbaddade** [comment]
Sollte bereits erledigt sein.
