### ISSUE TITLE
SEO-Klasse - getTitle() Trennzeichen zwischen Titel und Artikel definieren

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_url#97]
Wir haben nicht immer "-", und das sieht dann komisch aus:
`Titel aus URL-Addon - Artikel / Server GmbH`

**Comment by tbaddade** [comment]
Url liefert nur noch den Titel des Datensatzes. Mag man den Titel noch anpassen, kann man dies über den EP `URL_SEO_TAGS` erreichen.
